### ISSUE TITLE
wordpress wrapper not working when user not logged in

### ISSUE THREAD

**Issue by CristyTarantino** [FrDH/mmenu-js#1001]
Hi,

The wordpress wrapper breaks the menu when applied and the user is not logged in.

This is the error in mmenu.wordpress.js

 ```TypeError: null is not an object (evaluating 'wpadminbar.style')
(anonymous function) — mmenu.wordpress.js:5
_initWrappers — mmenu.oncanvas.js:319
Mmenu — mmenu.oncanvas.js:55
switchMobileMenu — index.js:24
(anonymous function) — index.js:116
```

I guess it need to check if `wpadminbar` exists before accessing the style.

Thank you.

**Comment by FrDH** [comment]
Thank you for reporting the issue, should be fixed in 8.0.6.
Sorry for the trouble.
