### ISSUE TITLE
WordPress Plugin Is Missing Critical Closing Method Call

### ISSUE THREAD

**Issue by spenweb** [FrDH/mmenu-js#1002]
I had a previous version of mmenu WordPress plugin working. After I updated the plugin to the current paid-for version, the menu would not open after hitting the close icon ("close-btn"). I did a quick diff check of the `mmenu/js/mmenu.js` file of both versions and noticed that the current version removed a method call to close the menu (was on line 152). Here is the referenced code that went missing in the newest version:
```
$(document).on("click", ".close-btn", function() { 
             api.close(); 
            });
```
To fix this I simply used the old version of the mmenu.js file (the only difference is the mentioned closing method call). I am concerned that in the future I may update the plugin again and would rather not have to manually update the code every time. I would make a pull request, but I was unable to find the WordPress plugin repo, so please excuse me posting in this one (it is the closest I could find). Thanks.

**Comment by FrDH** [comment]
I did a quick sweep through various version of the plugin, but I don't think that has ever been part of the plugin. Could it be you added it manually?

**Comment by spenweb** [comment]
Thanks for the clarification. I am taking over a project where the previous developers have added/modified code in parent themes and plugins. Upon further review, I now see that they did in fact add code directly in your plugin to add a close icon. I have been trying to tract down the best way to close the menu using an outside script. What is the best way to close the menu without directly editing your plugin? I have been calling jQuery's click method on every element in the page without success of closing the menu.

**Comment by spenweb** [comment]
This jQuery one-liner stimulates the mmenu to close: `$(".mm-wrapper__blocker").trigger("mousedown");` It took me a while to figure it out. It caught me off guard due to the event listener in use being "mousedown", I am more used to it being "click". Thanks for your initial help!
