### ISSUE TITLE
WordPress plugin language and RTL

### ISSUE THREAD

**Issue by mstudioIL** [FrDH/mmenu-js#1004]
How I can translate the plugin? where I find POT file?
I have to change the "menu" word.
How I make the menu work from right to left?
I really do not understand how to work with on WordPress, how to I set it?
this the page I working on https://www.noganagarut.com/new/
the menu opens with the hamburger icon that come from different plugin and it stays on top of the menu.
Also, how it working with multi-languages sites? Specially Hebrew and English

**Comment by FrDH** [comment]
You can specify the title above the main panel in the "header" section (click the gear-icon to open the secundary options).
The menu should automatically detect a RTL website based on the HTML tag `<html dir="rtl">`.
To open the menu from the right, check the "right" option in the "position the menu" section.
You probably need to add some CSS to hide the hamburger icon when the menu is opened. Something like ````css
.mm-wrapper_opened #responsive-menu-button {
   display: none;
}
````
Hope this helps.

**Comment by mstudioIL** [comment]
thanks, the CSS is working, and I found the gear-icon, can the title be empty?

**Comment by FrDH** [comment]
Have you tried it? My first guess would be it defaults back to "Menu".

**Comment by mstudioIL** [comment]
Thanks, I will stay with the word I entered, if the do not want it I will try CSS or try non-breaking space
`&nbps;`
