### ISSUE TITLE
Wrong width calculations when absolute positioned elements found in html

### ISSUE THREAD

**Issue by 7iomka** [FrDH/mmenu-js#1006]
I use tippy plugin for some tooltips on the page.
Because of this your awesome plugin calculates size of available space wrong(
See the demo video
https://cl.ly/33c822a401c7

**Comment by 7iomka** [comment]
I read the docs, and I know workaround, in my case to set appendTo parametr of tippy plugin to a value  to another then body, but it's complicated to make and to find solutions for every kind of plugins, than append some dynamic elements direct into body
I'm very sad to see that bahavior.

**Comment by FrDH** [comment]
That looks weird :)
The plugin does not make any calculations for the available width, it's basically CSS powered.
Is there an online example I could have a look at?
