### ISSUE TITLE
When menu is collapsed, show the menu option when the user hovers over the item.

### ISSUE THREAD

**Issue by bluenose1970** [FrDH/mmenu-js#1007]
I have the following menu:

- Item 1
- Item 2
- Item 3

When the above is collapsed the menu shows an icon for each of the above, when the user hovers over the icon I would like to show the item text, for example "Item 1". When the user moves the hover away I would like to then not show the text.

**Comment by FrDH** [comment]
Like when using the title-attribute?
````html
<a href="/page.html" title="item 1">Item 1</a>
````

**Comment by bluenose1970** [comment]
Not quite. More where the item would slide out to so show a single box for Item 1 on hover over, the box for item would disappear when the hover out event.

**Comment by bluenose1970** [comment]
Similar as to how this website works:

[https://coderthemes.com/moltran/red-dark/](url)

If you collapse the menu on the above link then when you move the mouse over a menu option on the left hand side it will show a popup of the menu option available.

**Comment by FrDH** [comment]
That's not possible.
