### ISSUE TITLE
Navbar doesn't work with html element 

### ISSUE THREAD

**Issue by Razrael** [FrDH/mmenu-js#1009]
When using the navbar addon, mixed content with element names and HTML seems not possible or buggy.
When using something like 
```
navbars: [{
  position: 'top',
  content: [
    'prev',
    'title',
    '<div>test</div>'
  ]
}]
```
the handlers won't work, although the content is rendered correctly.
To be more concrete: the title won't get updated and the prev button doesn't react on clicks.
After removing the html element, everything works as expected.

**Comment by Razrael** [comment]
I guess I've found the issue.
This was working in older versions because of jQuery I think. But now, an actual HTML element is needed (like `$('<div>test</div>').get(0)`).
An error message in JS would be nice though, because it was failing without any error.

**Comment by FrDH** [comment]
The API methods that previously expected jQuery object (and now expect a(n array of) HTMLElement(s)), have a hook that the debugger hooks into so it can give a warning.
Unfortunately adding the content to a navbar has no hook for the debugger to hook into.
Looking at the code, I'd say the example you provided should work. 
I'll have to look into it if it doesn't work.

**Comment by Razrael** [comment]
The example in the original post does not work, it just fails without any error.
Providing an actual HTMLElement via `$('<div>test</div>').get(0)` works though. So this is no issue anymore.
But maybe you would like to add an error message for the first example, because there is no JS error. It just fails without any message in the console.

**Comment by FrDH** [comment]
Inserting plain HTML should work, I'll have to investigate why it isn't.
Thanks for reporting it.

**Comment by FrDH** [comment]
This is interesting, if you put the plain HTML first and the dynamic content last, all works as expected. I think `navbar.innerHTML += content` removes all events from sibbling elements.
I'll fix it in the next release.

**Comment by justlevine** [comment]
Not sure if this is the same issue, but v7.x let you _reference_ an htmlElement as well.

e.g. 
```
'navbars': [ {
			'position': 'top',
			'content': [ 'prev', '#mobile-menu-header, 'close' ],
			'height': 1
		},
```
would include `<div id="mobile-menuheader">...</div>`

In v8.x you now need to `const mobileMenuHeader = document.getElementById('mobile-menu-header);`, and then reference the variable aka `'content': ['prev', mobileMenuHeader', 'close']`

If it's a separate issue, lemme know and Id be happy to open up a new bug report.
