### ISSUE TITLE
Make navbar extendable

### ISSUE THREAD

**Issue by Razrael** [FrDH/mmenu-js#1010]
Please make the navbar plugin extendable, so we can plug in new components into `navbarContents`. (https://github.com/FrDH/mmenu-js/blob/master/src/addons/navbars/mmenu.navbars.ts#L26-L33)
I suggest to do it like with `Mmenu.addons`, so we can just add more pieces there. 

This would help to better structure project code.

**Comment by FrDH** [comment]
good idea :)
i'll put it on the TODO list
