### ISSUE TITLE
closeAllPanels() - Calling loses the animation effect.

### ISSUE THREAD

**Issue by bluenose1970** [FrDH/mmenu-js#1011]
I use the following code to reset a menu back to its starting position.

```
var api = $("#menu").data("mmenu");
api.closeAllPanels();
```

This works but I lose the animation effect when calling the above, is there any way to reset the menu and keep the animation effect also?

**Comment by FrDH** [comment]
I guess you could open the first panel:
````js
var $menu = $("#menu");
var api = $menu.data("mmenu");
api.openPanel( $("#menu").find(".mm-panel").first() );
````

If that doesn't give the desired effect, could you please provide a reduced online example? Preferrably a jsfiddle or codepen.

**Comment by bluenose1970** [comment]
Great, thanks!
