### ISSUE TITLE
slidingSubmenus:false not working

### ISSUE THREAD

**Issue by greenart2019** [FrDH/mmenu-js#1012]
I encountered this odd issue: slidingSubmenus was set to false, nothing happened when clicked on submenus. I tried the default example that come with the download, but no luck too. When I changed the mmenu version 7, it work fine to drop down the sub-options. What might cause the issue?

Thanks in advance!

**Comment by FrDH** [comment]
That's a bug :(
I'll fix it shortly

**Comment by FrDH** [comment]
Thanks for reporting the issue, should be fixed in 8.0.7
