### ISSUE TITLE
hamburger does not work properly

### ISSUE THREAD

**Issue by j0101s** [FrDH/mmenu-js#1013]
When clicking on hamburger icon, it turns into X and expands menu. But clicking on X does not shrink menu. Hash tag on X still remains as "#menu" whereas it should turn into "#page".

Your website's hamburger works well, but downloaded version(8.0.6) does not work well. Anymore manipulation needed? Then how?

`			<span id="hamburger" class="mm-sticky">
				<a href="#menu" class="mburger mburger--collapse">
					<b></b>
					<b></b>
					<b></b>
				</a>
			</span>`

**Comment by FrDH** [comment]
The idea is, that when the menu is opened, clicking anywhere outside it will close the menu.
On my site I added this JS:
````js
var menu = new Mmenu({
   // options
});
var API = menu.API;
var $burger = $('#hamburger').children( '.mburger' );

API.bind( 'close:finish', function() {
     setTimeout(function() {
        $burger.attr( 'href', '#menu' );
    }, 100);
});
API.bind( 'open:finish', function() {
    setTimeout(function() {
        $burger.attr( 'href', '#page' );
    }, 100);
});
````

For the record, this behavior will be the standard for the mburger webcomponent.

**Comment by j0101s** [comment]
Well I got the idea from your demo page: [https://mmenujs.com/demo/index.html?demo=sidebar]
I added css codes into demo.css like below and it worked. I think you need provide a guide for this stuff in hamburger page.

`body .hamburger	{
background:#4bb5ef;
color:#fff;
}
body .hamburger-text	{
font-size:16px;
}
.hamburger .hamburger-inner,.hamburger .hamburger-inner::after,.hamburger .hamburger-inner::before	{
background:#fff
}
.hamburger a[href="#page"]	{
display:none!important
}
.mm-wrapper_opening .hamburger a[href="#menu"]	{
display:none!important
}
.mm-wrapper_opening .hamburger a[href="#page"]	{
display:block!important;
left:0!important
}
`

**Comment by j0101s** [comment]
In demo/default.html, hamburger plugin works fine. But it does not work well in demo/advanced.html.  Clicking elsewhere on content page does not shrink menu. Button x is inside menu, which looks awkward.

**Comment by j0101s** [comment]
I can't apply your code in advanced.html in demo folder. The $ sign can't be used as 8.1.1 has no jquery. Can you show me how to apply your code in advanced.html?


``var menu = new Mmenu({
   // options
});
var API = menu.API;
var $burger = $('#hamburger').children( '.mburger' );

API.bind( 'close:finish', function() {
     setTimeout(function() {
        $burger.attr( 'href', '#menu' );
    }, 100);
});
API.bind( 'open:finish', function() {
    setTimeout(function() {
        $burger.attr( 'href', '#page' );
    }, 100);
});
``

**Comment by FrDH** [comment]
Could you create a jsfiddle or codepen?
Would be a lot easier :)

**Comment by j0101s** [comment]
From version 8, mmenu does not use jquery, right? The above code, you provided on 22 May, cannot be working since it does not use '$'.

`var menu = new Mmenu({
   // options
});
var API = menu.API;
var $burger = $('#hamburger').children( '.mburger' );

API.bind( 'close:finish', function() {
     setTimeout(function() {
        $burger.attr( 'href', '#menu' );
    }, 100);
});
API.bind( 'open:finish', function() {
    setTimeout(function() {
        $burger.attr( 'href', '#page' );
    }, 100);
});`

**Comment by FrDH** [comment]
The plugin might not need jQuery, but you can still have it in your website.
Anyway, if you want vanilla JS:
````js
var menu = new Mmenu({
   // options
});
var API = menu.API;
var $burger = document.querySelector('#hamburger').children();

API.bind( 'close:finish', function() {
     setTimeout(function() {
        $burger.setAttribute( 'href', '#menu' );
    }, 100);
});
API.bind( 'open:finish', function() {
    setTimeout(function() {
        $burger.setAttribute( 'href', '#page' );
    }, 100);
});
````

**Comment by j0101s** [comment]
Thanks for the codes and I applied it to advanced.html/demo in 8.1.1. But I still get errors. I attach a file(advanced2.html) with  those codes.

```
Uncaught TypeError: $burger.setAttribute is not a function
```

Please unzip advanced2.zip and put it under demo folder to run it.

line 164 modified
line 232 ~ 245 added codes

[advanced2.zip](https://github.com/FrDH/mmenu-js/files/3428179/advanced2.zip)
