### ISSUE TITLE
setSelected > hover not working on v8.0.7 

### ISSUE THREAD

**Issue by jmalatia** [FrDH/mmenu-js#1014]
The option setSelected::hover is not working... does not change background on mouse hover.  Tested with v8.0.7.

```
setSelected: {
	hover: true,
	parent: true
},
```

See this sample codepen.io
https://codepen.io/jmalatia/pen/dEZrOP

**Comment by FrDH** [comment]
Hi,

Thank you for bringing this to my attention, I'll have to investigate why it no longer works.

**Comment by FrDH** [comment]
found the bug, will be fixed in the next release
