### ISSUE TITLE
Dynamic content e.filter not a function

### ISSUE THREAD

**Issue by hypol** [FrDH/mmenu-js#1018]
Hello,

When following the [dynamic content tutorial](https://mmenujs.com/tutorials/dynamic-content.html) clicking on a link gives the following message :` e.filter not a function`.

It works when removing the target from the iniPanels api call :

`api.initPanels( );`

instead of 

`api.initPanels( panel );`

This is with 8.0.7

**Comment by FrDH** [comment]
Hi,
Thank you for bringing this to my attention, I'll have to investigate why this no longer works.

**Comment by FrDH** [comment]
Found the issue, the `initPanels` method (like the name implies) expects an array of panels:
`api.initPanels( [ panel ] );`

I'll update the website shortly.

**Comment by hypol** [comment]
Thanks !
