### ISSUE TITLE
App mode inside a toggable block - question

### ISSUE THREAD

**Issue by 7iomka** [FrDH/mmenu-js#1021]
Hi. It is possible to trigger manually opening menu with main items?
I mean that example https://mmenujs.com/demo/index.html?demo=app-settings
In my case I have an idea to make shopping filters inside a hidden div, and when user clicks to some icon trigger (not a mmenu link how is your example when is whole page is filled with app), i need to open this div with all inner content with mmenu slideable panels and main custom logic.
I would be grateful for you to show a minimal example of how this can be done.

**Comment by FrDH** [comment]
If I understand correct, you need an off-canvas menu filled with custom content, which is possible by default.
What have you tried? Is there an online example?

**Comment by 7iomka** [comment]
> If I understand correct, you need an off-canvas menu filled with custom content, which is possible by default.
> What have you tried? Is there an online example?
No, I not have any online examples(
I already have one mmenu on the page to call the main menu of the site
But the strict regulation of markup is not very suitable for the formation of various kinds of stylized static content inside a menu. In fact, I need a second non-off-canvas menu  with all the navigation I need, but that it is hidden and that I can call it by pressing a button of some kind, as can be done with the offcanvas menu.
I would be grateful for any minimalistic example of how to do this, because all the examples that you have in the documentation on the site suggest that the site is the entire application, not part of it.

PS: I don't need any styles with max-width from offcanvas, because i need fullwidth)
PPS: It very hard currently to fill menu with custom content. I mean to make any divs in the same level as list item without any events and content replacement. Single possible solution that I found is to pass class mm-divider to li
![image](https://user-images.githubusercontent.com/18473137/58913961-0b52e600-8726-11e9-9780-e5cf477117bb.png)

**Comment by FrDH** [comment]
Have you tried [the thumbnail grid tutorial](http://www.mmenujs.com/tutorials/thumbnail-grid.html)?
It should give a good idea of how to create anything other than a menu.
If you need it to be 100% wide, you could use the [fullscreen extension](http://www.mmenujs.com/documentation/extensions/fullscreen.html).

If this doesn't help, please create a (reduces) test case (preferrably using codepen or jsfiddle) otherwise I can't help but point to the tutorials and docs.

**Comment by 7iomka** [comment]
> Have you tried [the thumbnail grid tutorial](http://www.mmenujs.com/tutorials/thumbnail-grid.html)?

I managed to create several demo versions in which I have difficulty.
1) https://codepen.io/7iomka/pen/QXEqvr?editors=1010  - A variant with the use of **standard markup,** which implies a nested menu structure. The question is - how will I get back to the main (1st) slide? `api.openPanel( $settings );` will not work if $settings is a whole nav.
2) https://codepen.io/7iomka/pen/mZEMxd?editors=1010 - example from your tutorial with thumbnail grid.
 In this example, when switching to another panel on the same level, standard navbars headers and navigation "back" will not work (is not visible), because dependencies of nested elements are not known. How do I get a working navigation option in this case with or without manually manipulations?
In this example, there is no problem as in the first variant, because you can always call `api.openPanel($("#some-name-of-block"))` (it's not tested)

Thanks for any help!

**Comment by FrDH** [comment]
1) You can close the menu by clicking on any link that targets the page
`<a href="#my-page">close menu</a>`

2) I see the tutorial needs to be updated.
You can simply add an anchor in the panel that targets the parent panel:
`<a href="#panel-1">close panel</a>`
If you add the classname "Prev" to it, it's text and href will be used by the navbars add-on:
`<a href="#panel-1" class="Prev">close panel</a>`

Hope this helps.

**Comment by 7iomka** [comment]
> 1. You can close the menu by clicking on any link that targets the page
>    `<a href="#my-page">close menu</a>`

I don't need to close whole menu. I need to go to main panel from nested panel!

**Comment by 7iomka** [comment]
> 2\. I see the tutorial needs to be updated.
>     You can simply add an anchor in the panel that targets the parent panel:
>     `<a href="#panel-1">close panel</a>`
>     If you add the classname "Prev" to it, it's text and href will be used by the navbars add-on:
>     `<a href="#panel-1" class="Prev">close panel</a>`
I'm sorry, you mean, for have some titles and arrow icon button prev in navbar, when we use thumbnail grid example, we needed to create inside content of each panel minimum two hidden elements with class Title and Prev?

"Interesting" facts:
1) Add class "Prev" to an anchor inside content of panel, when this panel is opened, navbar button prev will appear(yes!), BUT. change it text to text of this anchor, and href attribute too.. I don't needed any text insde prev button, I like default layout behaviour. If I create link inside panel with class Prev but with empty text, prev button will not appear! One solution is to add a hacky css code like
```
.mm-btn_prev {
   text-indent: -9999px;
}
```
2) Add class "Title" to an anchor or some element inside content of panel, when this panel is opened, navbar title will change in text and href attr to corresponded..Same question - it is possible to create title dynamically? May be with an data-attribute of element of panel?
Thanks!

**Comment by 7iomka** [comment]
any news?

**Comment by FrDH** [comment]
> If I create link inside panel with class Prev but with empty text, prev button will not appear!

This should not be the case. I removed the text from the `<a class="Prev" />` and it seemed to work as intended.

>  is possible to create title dynamically?
I guess you could change it using the `openPanel:start` hook. I updated the demo here:
https://codepen.io/anon/pen/jjmZmE
