### ISSUE TITLE
The contents of the full menu can not be scrolled

### ISSUE THREAD

**Issue by Malin88** [FrDH/mmenu-js#1022]
Hi!
I created a menu with additional two header bars and two footer bars. In portrait orientation all is fine, there is a standard menu between header and footer. But when I change orientation on landscape, then the height of my all 4 additional bars is greater then the viewport height so, my menu is under them and I can not see it. I would like to do sth like min-height of `mm-menu` so if the height of the viewport is smaller then the menu height, then I could scroll all the content. There is any possibility to do this?

**Comment by FrDH** [comment]
That makes sense :)
You could use the `use` option for each navbar content to specify a media query when it should be used:
````js
new Mmenu( "#my-menu", {
    navbars: [
        {
            position: "bottom",
            content: [ "searchfield" ],
            use: "min-height: 400px"
        }
    ]
});
````
This will only show the searchfield-navbar if the window is higher than 400 pixels.
Or, you could schrink the navbars based on a media query using the css variables:
````css
@media(max-height: 400px) {
    .mm-menu {
        --mm-navbar-size: 30px;
    }
}
````

**Comment by Malin88** [comment]
Thanks for a reply, but this is not realy what I want to achive. I don`t want to hide navbars, I want to increase height of all menu to more then `100vh`. Right now, I have top navbars and bottom navbars with total height of 410px, but  on landscape orientation 100vh is always less then 400px. Even if I enforce to increase min height of `.mm-menu` container to 500px, then I still can`t scroll the content, becouse all of the children are absolute positioning :/

![Zrzut ekranu 2019-06-19 o 10 07 54](https://user-images.githubusercontent.com/1419451/59752999-89b19b00-9283-11e9-99d6-3a0fbf23fc0c.png)
![Zrzut ekranu 2019-06-19 o 10 07 38](https://user-images.githubusercontent.com/1419451/59753001-8a4a3180-9283-11e9-9291-6d06af90c12d.png)

**Comment by FrDH** [comment]
> I want to increase height of all menu to more then 100vh

That simply isn't possible due to the menu being `position: fixed`.

> becouse all of the children are absolute positioning

In the latest version, the "navbars" and "panels" children are no longer `position: absolute`, instead the menu has `display: flex`. But I doubt this will fix your issue.
