### ISSUE TITLE
Invalid Assignment

### ISSUE THREAD

**Issue by kaspar-allenbach** [FrDH/mmenu-js#1023]
When I want to bundle your package vie webpack I get the following error:

> ERROR in www/theme/js/blabla.min.js from UglifyJs
> Invalid assignment [./node_modules/mmenu-js/dist/core/_dom.js:9,0][www/theme/js/blabla.min.js:89,41]

What to do?

**Comment by FrDH** [comment]
If your packages usages uglifyJs, you might want to think about replacing it
From [the package page](https://www.npmjs.com/package/uglify-js):
> uglify-js only supports JavaScript (ECMAScript 5).
> To minify ECMAScript 2015 or above, transpile using tools like Babel.

Mmenu uses terser.
From [the package page](https://www.npmjs.com/package/terser):
> uglify-es is no longer maintained and uglify-js does not support ES6+.
> terser is a fork of uglify-es that mostly retains API and CLI compatibility with uglify-es and uglify-js@3.

**Comment by kaspar-allenbach** [comment]
Thanks. I'll check that out. Bundlers anc compilers are a big mistery to me.

**Comment by FrDH** [comment]
np. they can indeed be pretty hard to wrap your head around ;)

I just realized mmenu does not use terser to uglify the JS, but webpack...
If you are using webpack, you probably don't need uglify at all since webpack uglifies (or minifies or whatever) the JS itself.
