### ISSUE TITLE
No more than 2 columns slide open?

### ISSUE THREAD

**Issue by rossib94** [FrDH/mmenu-js#1025]
Hi,

Thanks for creating such a great plugin, we're nearly there with implementing what we are trying to achieve but I've stumped myself a bit.

I am using the JS plugin rather than the WordPress plugin but I am integrating it with a WordPress menu. I have a 3 level menu at the moment but the 3rd column won't slide out, when I click an option on the 2nd level that has children it just takes me to that 2nd level page.

When looking in the code, on the 1st level of the menu i have::
```html
<li id="menu-item-30" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-30 mm-listitem mm-listitem_selected-parent">
  <a href="http://parajetstaging.wpengine.com/?page_id=11" class="mm-listitem__text">
    <img src="http://parajetstaging.wpengine.com/wp-content/uploads/Store-Icon-1.svg" class="_mi _before _svg" aria-hidden="true">
    <span>Store</span>
  </a>
  <a class="mm-btn mm-btn_next mm-listitem__btn" href="#mm-0" aria-haspopup="true" aria-owns="mm-0">
    <span class="mm-sronly">Open submenu</span>
  </a>
</li>
```

but on the second level I only have::
```html
<li id="menu-item-32" class="menu-item menu-item-type-taxonomy menu-item-object-product_cat menu-item-has-children menu-item-32 mm-listitem">
  <a href="http://parajetstaging.wpengine.com/?product_cat=paramotors" class="mm-listitem__text">Paramotors</a>
</li>
```

It seems to be missing the::
`<a class="mm-btn mm-btn_next mm-listitem__btn" href="#mm-0" aria-haspopup="true" aria-owns="mm-0">
<span class="mm-sronly">Open submenu</span>
</a>`

Don't worry about the img being missing here, 2nd level isn't supposed to have an icon. Just so you know only 'Store' has children currently on the 1st level and then on the 2nd level you can use 'Paramotors' or 'Vittorazi Parts'

Any ideas why it isn't creating the 3rd level? or why it isn't creating the 2nd level the same as the first?

The link to our staging site is [http://parajetstaging.wpengine.com/](url)

Thanks,
Ross

**Comment by FrDH** [comment]
Could you post the HTML for the menu before the plugin makes its alterations? I cant access the staging site as it requires autorization.

**Comment by rossib94** [comment]
I've just figured it out. When turning mmenu off I realised my code that pulls the WordPress menu through was set to only show a depth of 2.

Sorry for wasting your time.
