### ISSUE TITLE
Layout Broken at Some Examples @ IE11 

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-js#1029]
Have a look at the examples site in IE11:

https://mmenujs.com/examples.html

Some of them are broken from a layout perspective, not functionally.

**Comment by xcartmods** [comment]
Read the docs about supported browsers !
https://www.mmenujs.com/documentation/
...No need to bombard Fred with issues.

**Comment by FrDH** [comment]
IE11 is indeed not supported as of version 8, you should be able to get it up and running (to some degree) with a bunch of polyfills though.

**Comment by julmot** [comment]
If you would have read what I mentioned at the light version you would have noticed that a.) All of the points are valid to be mentioned because it seems that they are all bugs b.) He wanted to receive separate issues per topic so I had to create a new issue for each of them.

In terms of your hint; I've read the docs. But I assume that all if the polyfills have been embedded in the plugin website itself, to make it possible to test it. Therefore, I would also assume that all examples work. If polyfills have not been added, this issue can be seen as feature request to add them, to make it testable and comparable to other plugins.

I would suggest that if you're annoyed by active discussions and bug reports, to unwatch this type of activity.

**Comment by FrDH** [comment]
The website uses version 7 :)
I'll see if I can grab a windows laptop at work tomorrow, don't have one here.

**Comment by julmot** [comment]
Thanks for your reply @FrDH. You're right. However, in this case there shouldn't be any issues, right? Since teh documentation says `Version 7 should work in Internet Explorer 10 and 11 without any shortcoming`.

Is there an archive of the documentation for v7? Or how does the API look like to be compatible with IE11?

**Comment by FrDH** [comment]
The docs for version 7 can be found [here](mmenu.frebsite.nl)

**Comment by julmot** [comment]
@FrDH This link referes to a [Not found](https://github.com/FrDH/mmenu-js/issues/mmenu.frebsite.nl) page

**Comment by FrDH** [comment]
fixed it

**Comment by FrDH** [comment]
I think the "layout issues" you are referring to are caused by the custom CSS added for the specific examples, they don't have a fallback for the CSS variables. Alle CSS in the plugin (v7) does have  a fallback.
In other words, these issues are not due to the plugin, but due to the customization for the example.

**Comment by julmot** [comment]
@FrDH So I just tried integrating v8, and got several JS errors, even though I'm running it through babel with configured IE11 support (e.g. `object doesn't support property or method "append"`) and I've integrated a [css-vars polyfill](https://www.npmjs.com/package/css-vars-ponyfill). The [polyfills](https://polyfill.io/v3/polyfill.min.js?flags=gated&features=Array.prototype.filter%2CArray.prototype.forEach%2CArray.prototype.map%2CElement.prototype.cloneNode%2Cdocument.querySelector) link mentioned on the website doesn't work.

I'll play with some polyfills, but if I can't get it to work in IE11 within the next hour I'm going to try out v7, even though it depends on jQuery.

**Comment by julmot** [comment]
Finally, with many different polyfills I could get v8 up and running:

For those of you who are having the same difficulties with this plugin in IE11, here's my polyfill code:

```
/* eslint-disable */
// Everything below is only necessary for Mmenu
import 'css-vars-ponyfill';
// Source: https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach
if (window.NodeList && !NodeList.prototype.forEach) {
  NodeList.prototype.forEach = function(callback, thisArg) {
    thisArg = thisArg || window;
    for (var i = 0; i < this.length; i++) {
      callback.call(thisArg, this[i], i, this);
    }
  };
}
// Source: https://github.com/jserz/js_piece/blob/master/DOM/ParentNode/prepend()/prepend().md
(function(arr) {
  arr.forEach(function(item) {
    if (item.hasOwnProperty('prepend')) {
      return;
    }
    Object.defineProperty(item, 'prepend', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function prepend() {
        var argArr = Array.prototype.slice.call(arguments),
          docFrag = document.createDocumentFragment();

        argArr.forEach(function(argItem) {
          var isNode = argItem instanceof Node;
          docFrag.appendChild(isNode ? argItem : document.createTextNode(String(argItem)));
        });

        this.insertBefore(docFrag, this.firstChild);
      }
    });
  });
})([Element.prototype, Document.prototype, DocumentFragment.prototype]);
// Source: https://github.com/jserz/js_piece/blob/master/DOM/ParentNode/append()/append().md
(function(arr) {
  arr.forEach(function(item) {
    if (item.hasOwnProperty('append')) {
      return;
    }
    Object.defineProperty(item, 'append', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function append() {
        var argArr = Array.prototype.slice.call(arguments),
          docFrag = document.createDocumentFragment();

        argArr.forEach(function(argItem) {
          var isNode = argItem instanceof Node;
          docFrag.appendChild(isNode ? argItem : document.createTextNode(String(argItem)));
        });

        this.appendChild(docFrag);
      }
    });
  });
})([Element.prototype, Document.prototype, DocumentFragment.prototype]);
// Source: https://github.com/jserz/js_piece/blob/master/DOM/ChildNode/before()/before().md
(function(arr) {
  arr.forEach(function(item) {
    if (item.hasOwnProperty('before')) {
      return;
    }
    Object.defineProperty(item, 'before', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function before() {
        var argArr = Array.prototype.slice.call(arguments),
          docFrag = document.createDocumentFragment();

        argArr.forEach(function(argItem) {
          var isNode = argItem instanceof Node;
          docFrag.appendChild(isNode ? argItem : document.createTextNode(String(argItem)));
        });

        this.parentNode.insertBefore(docFrag, this);
      }
    });
  });
})([Element.prototype, CharacterData.prototype, DocumentType.prototype]);
// Source: https://github.com/jserz/js_piece/blob/master/DOM/ChildNode/remove()/remove().md
(function(arr) {
  arr.forEach(function(item) {
    if (item.hasOwnProperty('remove')) {
      return;
    }
    Object.defineProperty(item, 'remove', {
      configurable: true,
      enumerable: true,
      writable: true,
      value: function remove() {
        if (this.parentNode !== null)
          this.parentNode.removeChild(this);
      }
    });
  });
})([Element.prototype, CharacterData.prototype, DocumentType.prototype]);
/* eslint-enable */
```

In my Webpack configuration I had to tell the Babel loader not to exclude the mmenu-js plugin. All other node modules can be ignored but not this one, since it doesn't ship ES5 code:

```
exclude: /node_modules\/(?!(mmenu-js)\/).*/,
```

And importing the plugin can't be done using normal CommonJS plugins as it doesn't expose UMD, so this is the only way to work with the plugin:

```
import 'mmenu-js/dist/mmenu'; // unfortunately no UMD plugin, exposes only window.Mmenu

new window.Mmenu(...)
```

Hope it helps.

Since I had to spend several hours, it would be amazing to get IE11 in a more "user friendly" way, either by adjusting the browser compatibility documentation by adding all the needed polyfills (the current link to polyfills.io doesn't cover all) or by shipping code without these advanced features. For example the `NodeList.forEach` that is used and where a polyfill is needed since Babel doesn't ship it can easily be fixed by adding `[.. XXX ]` around the `querySelectorAll`, e.g. `[...document.querySelectorAll('.mm-panels']`, this will create a native Array with existing `forEach`.

**Comment by FrDH** [comment]
Thank you for doing the research, I'll update the link to polyfills.io in the docs.
