### ISSUE TITLE
Fast clicking hides menu

### ISSUE THREAD

**Issue by julmot** [FrDH/mmenu-js#1030]
Just click a children link and the back menu fast after each other, you'll notice that sometimes the menu will disappear entirely, see this video that I've taken directly from the website in the latest Firefox:

![ezgif-5-fe2a52e59bcd](https://user-images.githubusercontent.com/8310677/60362432-28a36900-99e1-11e9-82d7-9442ca9a0bf3.gif)

**Comment by FrDH** [comment]
That can't be good, I'll have to do some testing.

**Comment by j0101s** [comment]
All versions(8.x.x) have the same problem. However your website(https://mmenujs.com) seems no problem. When are you going to fix it? It's pretty old.

**Comment by sbulhoesspiria** [comment]
Not sure if this is related but I can reproduce the same problem on this page
https://mmenujs.com/demo/index.html?demo=menu-advanced-4

Click fast on the burger menu and the page will eventually dissapear.

![mmenu](https://user-images.githubusercontent.com/51246662/91331485-cf77c680-e798-11ea-8588-6219142a484d.gif)

**Comment by FrDH** [comment]
Will probably be fixed in the next major release.

**Comment by FrDH** [comment]
should be fixed in the next major release
