### ISSUE TITLE
compatibility issue with ie 11

### ISSUE THREAD

**Issue by j0101s** [FrDH/mmenu-js#1031]
Vanilla js version(8.x.x) does not work on ie 11. Do we have to abandon ie 11? There are still people out there using that browser. Should use 7.x.x to avoid that problem?

**Comment by FrDH** [comment]
Check out the docs for browser support:
http://mmenujs.com/documentation/

Also, this issue might help you implement the correct polyfills:
https://github.com/FrDH/mmenu-js/issues/1029

For a quick fix, you could indeed use version 7, but it is no longer actively maintained or updated with new features.
