### ISSUE TITLE
Iphone XS Max - When scrolling the submenu options disappear.

### ISSUE THREAD

**Issue by hejuso** [FrDH/mmenu-js#1032]
Hi,
i'm having troubles with Iphone Xs Max when i try to scroll while i'm at a submenu.
![Image-11](https://user-images.githubusercontent.com/9479622/60518355-a87f4b00-9ce1-11e9-9924-8950b474afd9.jpg)

Thanks

**Comment by hejuso** [comment]
When i scroll, the subcategory elements start appearing and desappearing. It seems to be some specific problem of Safari on Iphone Xs Max, because i've tried with Iphone 6, X and Xr. The IOS version is 12.3.1

**Comment by FrDH** [comment]
Weird, I can't think of any reason for an iPhone Xs Max to behave so different from a smaller iPhone. Is it a specific issue for your website? Or do the examples in the download-pack (after adding a few extra menu items) have the same problem?
Unfortunately, I don't have an iPhone Xs Max available for testing :(
