### ISSUE TITLE
Draggable components inside menu

### ISSUE THREAD

**Issue by LedzZm** [FrDH/mmenu-js#1033]
Hi everyone. Recently i stumbled upon an issue with the mmenu. Let's say we want to have a draggable component inside the menu (in a panel let's say). This component will not be draggable because (i guess) event stopPropagation is used for the menu to close on document click. In that case how do i add a draggable component inside the panel?

Edit: The issue appears on touch devices.

**Comment by FrDH** [comment]
Have you tried disabling the `[scroll bug fix add-on](http://mmenujs.com/documentation/core/scroll-bug-fix.html)?
It uses `stopPropagation` on the `touchmove` event to prevent the body / page from scrolling while the menu is opened.

Also, if you're using the [drag add-on](http://mmenujs.com/documentation/addons/drag.html) (used to drag the menu open and swipe panels closed), you might want to disable it.

Hope this helps.
