### ISSUE TITLE
Navbar breadcrumbs broken padding

### ISSUE THREAD

**Issue by Zulcom** [FrDH/mmenu-js#1035]
Hello. If toggle breadcrumbs in top navbar, padding in breadcrums is zero.
Excepted behavior as showed in demo:
![image](https://user-images.githubusercontent.com/11247988/60753889-3f5e4700-a003-11e9-9b7b-e9acf227b606.png)
But in actual code padding is zero:
https://github.com/FrDH/mmenu-js/blob/2db4ae6df26a4c696d57d236a9073a9b4727b61b/src/addons/navbars/_navbar.breadcrumbs.scss#L2-L11

**Comment by FrDH** [comment]
Hi, you are correct.
This bug will be fixed in the next release.
Thank you for reporting it.

**Comment by FrDH** [comment]
should be fixed in 8.2
