### ISSUE TITLE
WP plugin issue on multisite

### ISSUE THREAD

**Issue by sjaakbanaan** [FrDH/mmenu-js#1036]
Hi, we've been using the mmenu plugin and standalone for a few years now and we love it! We do however have a strange issue right now on a live multisite WP installation. For some reason the plugin stops working properly after a few page loads / clicking around for a few minutes in the website. And it seems I can only fix it by (re)logging in. Are there any known multisite bugs? 

Here is what I know when it's broken:
- the js and css files are loaded properly;
- there's no DOM error;
- the code that's normally inserted into the DOM between the end of the head-section and the first content section is not there. Just like the 'close menu' code at the bottom;
- when i go the settings everything looks fine.

Hope you can help me.

**Comment by FrDH** [comment]
Hi,

Thanks for reporting the issue.
Sounds odd, I can't think of any reason the plugin would stop working after a few page-refreshes.

Are there more things breaking? Or just the mobile menu?
If other things also break, do they still break after disabling the mmenu plugin?

**Comment by sjaakbanaan** [comment]
Thanks for the quick reply. It's really only the mmenu plugin with strange behaviour. And it looks like it get's fixed as soon as i visit a page in the back-end (/wp-admin). I have to agree that this is really weird  so I'm going to try a few more things to get some more information.

**Comment by sjaakbanaan** [comment]
We couldn't find the cause so we decided to go with the standalone version instead of the WP plugin. All seems fine now!
