### ISSUE TITLE
Handle fixed elements that are not fixed on page load

### ISSUE THREAD

**Issue by sjaakbanaan** [FrDH/mmenu-js#1039]
Is there a way to handle elements that are not fixed or sticky on page load, but will become fixed or sticky after scrolling x px on a page? Thanks.

**Comment by FrDH** [comment]
The fixed elements add-on does two things on page load:
1. replace the classnames "Fixed" (or "Sticky") with "mm-fixed" (or "mm-sticky").
2. append the element to to `<body />`.

You could try something like this to do the same after scrolling:
````js
var fixed = document.querySelector('.my-fixed-elem');
var wrappr = fixed.parentElement;
window.addEventListener('scroll', (event) => {
   if (window.scrollY > 100) {
      // scrolled down
      fixed.classList.add('mm-fixed');
      document.body.append( fixed );
   } else {
      // scrolled up
      fixed.classList.remove('mm-fixed');
      wrapper.append( fixed );
   }
});
````

This is not perfect (and I havent tested it), but you might get the idea.
Hope this helps.

**Comment by sjaakbanaan** [comment]
Thanks, I'll play around with it next week.
