### ISSUE TITLE
Using mmenu-js with Angular

### ISSUE THREAD

**Issue by netdjw** [FrDH/mmenu-js#1040]
Is there any working example to using mmenu-js into an Angular project? (Not AngularJS).

I searched this repo's issues, the official documentation, homepage, but I only found AngularJS examples. What I'm looking for is how to integrate mmenu-js into my Angular 8.1 project?

Thanks a lot!

**Comment by FrDH** [comment]
What have you tried? 
The [angular wrapper](http://www.mmenujs.com/documentation/wrappers/angular.html) isn't all that elaborate and it is not specific for AngularJS. It only sets some options so clicking an anchor in the menu will close the menu and set the clicked anchor to being "selected".

**Comment by netdjw** [comment]
I tried nothing, just read the documentatations and not found part for Angular. Maybe this was a dummy thing, but I read first, code after. Can you add an example for Angular for the documentation? It can save very much time to start trying things. It could be very useful.

Thank you!

**Comment by umutau** [comment]
In Angular, I had a problem with creating more than one Panel, all menu goes in one panel and there is no sub menu. My code is below

`Mmenu.configs.classNames.selected = 'active';
    this.menu = new Mmenu( '#my-menu', {
      extensions: ['shadow-page'],
      wrappers: ['angular'],
      navbar: {
        title: 'My Nav'
      },
    });

    // Get the API
    this.api = this.menu.API;
  }
`

`  <nav id="my-menu">
    <ul>
      <li *ngFor="let item of navigationItems">
        <ng-container *ngIf="item.deep_links && item.deep_links.length > 0; else linkMenu">
            <span>{{ item.name }}</span>
            <ul>
              <li class="mm-listitem" *ngFor="let deepLinks of item.deep_links">
                <a [href]="deepLinks.link">{{ deepLinks.name }}</a>
              </li>
            </ul>
        </ng-container>
        <ng-template #linkMenu>
          <a [href]="item.link">{{ item.name }}</a>
        </ng-template>
      </li>
    </ul>
  </nav>

`

Not sure it is a bug or I am doing something wrong.

**Comment by umutau** [comment]
Looks like mmenu doesn't like the additional comments that Angular adding when we do ngFor or ngIf like '<binding..', I removed the logic .ts file and prepare list and then call mmenu.

**Comment by FrDH** [comment]
This is not going to work, the mmenu plugin is intended to be invoked on fixed HTML. It might work if you invoke it after Angulars first DOM manipulation, but after that, Angular will no longer work as expected (e.g. adding an item to `navigationItems` will probably not re-render the DOM).

**Comment by notaninvaliduser** [comment]
> What have you tried?
> The [angular wrapper](http://www.mmenujs.com/documentation/wrappers/angular.html) isn't all that elaborate and it is not specific for AngularJS. It only sets some options so clicking an anchor in the menu will close the menu and set the clicked anchor to being "selected".

Hello, im currently trying to use the AngularJS wrapper but im facing on of the issues you pointed out, the menu closes itself after clicking an anchor, i have been searching for a solution but haven't found one yet, any help is really apreciated, thanks in advance!
