### ISSUE TITLE
Issue with mmenu v6.1.8 and bootstrap v4.3

### ISSUE THREAD

**Issue by cmichael-de** [FrDH/mmenu-js#1041]
I have to deactivate (comment out) the bootstrap helper:
https://github.com/twbs/bootstrap/blob/master/scss/helpers/_screenreaders.scss

If I don't, the mmenu opens but doesn't show any navigation and displays only a white mmenu container.

Not sure if it's a mmenu bug.

**Comment by FrDH** [comment]
Is there an online example?
It would be kinda odd, but from the information you provided I guess your menu (the main UL) has the class "sr-only" applied to it, making it invisible due to the Bootstrap CSS

**Comment by cmichael-de** [comment]
Thanks and yes I have an example here: http://devonsodeck.de.w019533d.kasserver.com/

**Comment by cmichael-de** [comment]
Hi Fred, you are completly right, "sr-only" is the problem. It's not an issue with the mmenu there is a conflict between two contao extensions (I love and use the cms contao). Please close the issue. I found a workaround and maybe the extension developer can find a way to fix the conflict: https://github.com/contao-bootstrap/layout/issues/12
