### ISSUE TITLE
scrollBugFix error

### ISSUE THREAD

**Issue by jeongminjong** [FrDH/mmenu-js#1043]
Hi I am Korean
I'm trying to use mmenu.js in my portfolio site. I have a scrolling error. Can you please confirm what the problem is?

Background is scrolled when menu is opened

http://m.anderssonbell.cafe24.com/index.html
check with your mobile device

**Comment by FrDH** [comment]
I don't see any issues on my phone. Please provide more information on what you think is wrong.

**Comment by jeongminjong** [comment]
I solved the problem in another way. Thank you for the answer
