### ISSUE TITLE
Add dynamic menu in Angular 8.1

### ISSUE THREAD

**Issue by rohitpavaskar** [FrDH/mmenu-js#1045]
Adding dynamic content to angular project will not re-init panels.
Tried  initPanel and initPanels([]) both.
Will you please provide any link to do so.

**Comment by FrDH** [comment]
The mmenu plugin (like other .js plugins that alter the DOM) is very likely not compatible MVVM frameworks like Angular. The main issue is that mmenu moves and adds HTML, therefor Angular can no longer connect the template to the DOM. 
Stuff should (probably, to some degree) work if you do not add dynamic content.

**Comment by FrDH** [comment]
If you want, you could try the [mmenu light plugin](https://www.mmenujs.com/mmenu-light), it (almost) doesn't alter the HTML and is more likely to work out of the box with dynamic content.
