### ISSUE TITLE
Width issues, fixed width specified in CSS

### ISSUE THREAD

**Issue by brgrz** [FrDH/mmenu-js#1046]
Setting the following CSS variable

`	--mm-sidebar-expanded-size: 320px;`

does not affect all the places where width is used CSS. 

There are places where 440px is fixed, for instance

```
@media (min-width: 550px)
.mm-wrapper_opening .mm-menu_offcanvas.mm-menu_opened~.mm-slideout {
    -webkit-transform: translate3d(440px,0,0);
    transform: translate3d(440px,0,0)

```

If it is required to build from SASS to correctly calculated all of the width values then I believe the CSS variable should be removed because it doesn't work everywhere and it makes us falsly believe changing the variable will change all the widths.

**Comment by FrDH** [comment]
Have you tried it?
Is there an online example of it not working?

I tried the following and it appeared to work as intended:
````css
:root {
    --mm-sidebar-expanded-size: 300px;
}
````

I'll admit the overriding CSS selector (.mm-wrapper_sidebar-expanded:not(.mm-wrapper_sidebar-closed) .mm-menu_sidebar-expanded.mm-menu_opened ~ .mm-slideout) is a bit extensive, therefor I'm exploring other methods to adjust the size of both the menu and the page.
