### ISSUE TITLE
Custom Build WordPress wrapper won't load when compiling

### ISSUE THREAD

**Issue by apexwebdev** [FrDH/mmenu-js#1047]
Hi,
I'm creating a custom build for use with a custom wordpress theme and everything is good except for the WordPress wrapper.  Compiling from plugin direcotry using: 

`gulp custom --i ../custom-build/src --o ../custom-build/dist`

I get an error saying it won't load the wordpress wrapper.

Error in plugin "sass"
Message:
    ../custom-build/src/mmenu.scss
Error: File to import not found or unreadable: ../../mmenu-js/src/wrappers/wordpress/mmenu.wordpress.
        on line 60 of ../custom-build/src/mmenu.scss
>> @import '../../mmenu-js/src/wrappers/wordpress/mmenu.wordpress';
   ^`

I've checked the mmenu.scss file in my custom-build directory and the import path is correct.
`@import '../../mmenu-js/src/wrappers/wordpress/mmenu.wordpress';

Folder Structure
project
- custom-build
  - src
    - mmenu.scss
    - mmenu.js
- mmenu-js
  - dist
  - src
    - wrappers
      - wordpress
        - mmenu.wordpress.ts

Thoughts?

**Comment by FrDH** [comment]
There is not CSS for the wordpress wrapper, so trying to include (`@import`) it, will result in an error. What does your `mmenu.scss` file look like? The [default file](https://github.com/FrDH/mmenu-js/blob/master/src/mmenu.scss#L60) has the CSS for the wordpress wrapper commented out.

**Comment by FrDH** [comment]
Yes, that's the problem, you should not uncomment it (as there is no file to include).

**Comment by apexwebdev** [comment]
In the src/wrappers/wordpress/ directory there is a file 

mmenu.wordpress.ts

with the following code:
`
import Mmenu from '../../core/oncanvas/mmenu.oncanvas';

export default function(this: Mmenu) {
    this.conf.classNames.selected = 'current-menu-item';

    var wpadminbar = document.getElementById('wpadminbar');
    if (wpadminbar) {
        wpadminbar.style.position = 'fixed';
        wpadminbar.classList.add('mm-slideout');
    }
}
`
But I suppose I can do without it. Thanks for the help.

**Comment by FrDH** [comment]
There is a .ts file (javascript), you should `import` this in mmenu.js
But there is NO .scss file (css), so you should not `@import` it in mmenu.css

**Comment by apexwebdev** [comment]
I see what you're saying now.I was confused because it was included but commented out in the menu.scss file. Thank you for the clarification.
