### ISSUE TITLE
Issue when using WordPress with Divi theme

### ISSUE THREAD

**Issue by RobinMansson** [FrDH/mmenu-js#1051]
Hi,
I'm trying to implement mmenu on a WordPress site using the mmenu plugin for WordPress.
We're using the popular theme called Divi, and the plugin setup wen't smooth. The mmenu seem to initialize correctly. It properly takes over the default mobile menu.

But when I click on the arrow next to a parent menu item, it doesn't open up the sub-menu.
And when I manually browse to a sub-level page, and open up the menu, it correctly displays the sub-menu I'm currently on, but the arrow to navigate back to the parent menu doesn't do anything.

Do you have any idea what causes this?
An example can be found here:
https://poolside.bossgrand.se/

Our firm would like to buy a license, but we mainly use Divi for our projects.

**Comment by FrDH** [comment]
did you find a solution?

**Comment by RobinMansson** [comment]
Yes.
Divi takes over the click event on every anchor (a href="#"). So I wrote a script that dequed your mmenu.js and re-enqued it after Divi's scripts. So now it works perfectly.

**Comment by Yogeshgupta97** [comment]
> Yes.
> Divi takes over the click event on every anchor (a href="#"). So I wrote a script that dequed your mmenu.js and re-enqued it after Divi's scripts. So now it works perfectly.


Hi Robin,

I'm also facing the same issue in Divi Theme. Can you please share the script and guide me how to resolve the issue. It will really help me.
TIA

**Comment by RobinMansson** [comment]
<?php 
add_filter('et_builder_modules_script_handle', function(){
    if(!is_admin()){
        if ( !current_user_can( 'manage_options' ) || !isset( $_GET[ 'mmenu' ] ))
        $menu = get_option( 'mm_menu', false );
        {
            $version = get_option( 'mm_setup', array() );
            $version = isset( $version[ 'version' ] ) ? $version[ 'version' ] : 0;
            
            if ( $menu )
            {
                wp_dequeue_script( 'mmenu' );
                wp_enqueue_script( 	'mmenu', plugin_dir_url('') . 'mmenu/js/mmenu.js', array( 'jquery' ), $version, true );
            }
        }
    }
});

**Comment by Yogeshgupta97** [comment]
Can you help me where I've to add this code?

**Comment by RobinMansson** [comment]
> Can you help me where I've to add this code?

Either create a plugin or a child theme. Then you can add the code to your functions.php or plugin-initializer-file.

**Comment by Yogeshgupta97** [comment]
Thanks a ton Robin!
Issue is resolved now.

**Comment by Munna-0011** [comment]
Thanks a lot for the solution! It works also on one of my site :)

**Comment by wforte88** [comment]
> add_filter('et_builder_modules_script_handle', function(){
> if(!is_admin()){
> if ( !current_user_can( 'manage_options' ) || !isset( $_GET[ 'mmenu' ] ))
> $menu = get_option( 'mm_menu', false );
> {
> $version = get_option( 'mm_setup', array() );
> $version = isset( $version[ 'version' ] ) ? $version[ 'version' ] : 0;
> 
> ```
>         if ( $menu )
>         {
>             wp_dequeue_script( 'mmenu' );
>             wp_enqueue_script( 	'mmenu', plugin_dir_url('') . 'mmenu/js/mmenu.js', array( 'jquery' ), $version, true );
>         }
>     }
> }
> ```
> 
> });

Hi, @RobinMansson @Yogeshgupta97 and @Munna-0011 this code still working for you? In my site, with WP 5.5 and Divi 4.9 they doesn't work :-(
