### ISSUE TITLE
JS errors in IE even with recommended polyfills

### ISSUE THREAD

**Issue by mclarkos** [FrDH/mmenu-js#1053]
Even with the recommended polyfills, in IE 11, mmenu v8.2.2 fails with a Syntax Error. I believe this is due to use of arrow functions, which cannot be polyfilled. However there may be further issues that are masked by this initial error. The first line that fails is:

e.split(".").forEach((e, n) => {

**Comment by FrDH** [comment]
The recommended polyfills are currently not enough :(
Basically, IE supports `classList.add( classname )`, but not `classList.add( classname1, classname2 )`. This will be fixed soon, in the next version.

Furthermore, the plugin is transpiled down to ES5 (so, arrow functions should be turned in to normal functions), the examples and demo files are not transpiled, so they might not work in IE.

For now, you could give the [develop branche](https://github.com/FrDH/mmenu-js/tree/develop) a try.

**Comment by mclarkos** [comment]
Thanks for the reply, and good to hear you're working on fixes for IE.
However if you look at dist/mmenu.js, arrow functions are present. Does this mean transpilation isn't correctly removing arrow functions?

**Comment by polycode-nz** [comment]
Came looking for the same problem.. ugh these old browsers. Just FYI, was using mmenu-light and the web page for this version also doesn't work in IE 11. http://mmenujs.com/mmenu-light

**Comment by FrDH** [comment]
Fortunately (for me) there are no mobile devices with IE11 (are there??) :)
You could ofcourse simply check for IE < 12 and not fire the plugin. Something like this.
````js
if(navigator.userAgent.indexOf('MSIE')!==-1
|| navigator.appVersion.indexOf('Trident/') > -1){
    alert( "old browser" )
} else {
   new Mmenu("#my-menu");
}
````

**Comment by polycode-nz** [comment]
Bit more of a problem than that for me for two reasons:

1) This project only uses the "mobile" version of a menu for all devices/screens.
2) The syntax error stops all the other JS working even when appended last. 

I use CodeKit and linked files to build/compress into one JS file.

**Comment by mclarkos** [comment]
Yes, I agree with @polycode-nz on both points. In my case, there is a "desktop" menu mode but it only kicks in on relatively large browser sizes.

**Comment by FrDH** [comment]
The syntax error doesn't stop other JS if it is not executed, that's what the `if` was for:
````js
if(navigator.userAgent.indexOf('MSIE')!==-1
|| navigator.appVersion.indexOf('Trident/') > -1) {
````

But I agree the thing should simply work :), even in IE11.
Have you tried the [develop branche](https://github.com/FrDH/mmenu-js/tree/develop) yet? I'll be merged into the master branche soon.

**Comment by mclarkos** [comment]
I haven't tried the develop branch, sorry. I've actually moved back to mmenu v7 for now.
In terms of the conditional, I believe you would have to prevent loading mmenu.js rather than the instantiation. The parsing of mmenu.js seemed to fail (the originally reported error), then a second error occurred when attempting to instantiate because Mmenu was undefined.

**Comment by FrDH** [comment]
NP, v8 was initailly intended for modern browsers only :)

**Comment by polycode-nz** [comment]
@FrDH 

Hey Fred, sorry I'm a a bit green - I've only ever used your menu by including mmenu-light.js in the project.

I included https://raw.githubusercontent.com/FrDH/mmenu-js/develop/dist/mmenu.js file but it had some errors in Chrome (t.enable is not a function). Was that expected to work or I need to do more?

As an aside, the [polyfill link](https://polyfill.io/v3/polyfill.js?flags=gated&features=Array.prototype.filter%2CArray.prototype.forEach%2CArray.prototype.map%2CElement.prototype.cloneNode%2Cdocument.querySelector) in the docs can't find any polyfills for those setting.

**Comment by FrDH** [comment]
If you're using the mmenu.js plugin, you can not use the code from mmenu-light.js to invoke it :)

For mmenu.js:
````html
<script src="path/to/mmenu.js"></script>
<script>
   var menu = new Mmenu("#my-menu");
</script>
````
For mmenu-light.js:
````html
<script src="path/to/mmenu-light.js"></script>
<script>
   var node = document.querySelector( "#my-menu" );
   var menu = new MmenuLight( node );
   menu.enable( "(max-width: 600px)" );
   menu.offcanvas();
</script>
````

**Comment by FrDH** [comment]
Version 8.3 should work (with the polyfills included) in IE 11.
