### ISSUE TITLE
In mobile view 

### ISSUE THREAD

**Issue by anandfront1992** [FrDH/mmenu-js#1054]
mmenu.js:1 Uncaught TypeError: Cannot read property 'classList' of undefined

**Comment by FrDH** [comment]
Is there an online example? The demo files appear to work so have no idea where to start searching without some more information.

**Comment by nerdess** [comment]
@anandfront1992 this happened to me when i did not have a wrapper around the page content. check out this guide: https://mmenujs.com/tutorials/off-canvas/
