### ISSUE TITLE
Licensing unclear

### ISSUE THREAD

**Issue by nafg** [FrDH/mmenu-js#1055]
https://www.mmenujs.com/download.html says

> The mmenu.js plugin is free to use for **personal or non-profit usage.** You can purchase a license if you want to use it in a commercial project (**including plugins, themes and templates you plan to sell**).

[emphasis mine]

The last examples -- "plugins, themes and templates you plan to sell" -- leave room to interpret that payment is needed only if you are effectively reselling the code as code. On the other hand "personal or non-profit usage" seems to imply that payment is only not needed if you are not deriving financial benefit from it. Also, it's unclear if "non-profit usage" means "usage that one is not profiting from and does not intend to" or "usage for a non-profit [organization]." (I assume the former but it could technically mean the latter.)

Those specific examples are repeated a bit further down:

> By purchasing ONE "Multiple websites license", you are allowed to include the mmenu.js plugin in ONE product (for example a plugin, theme or template) for sale. 

On the other hand, https://www.mmenujs.com/support/contact.html says

> You can purchase a license if you want to **use it in a commercial website.**

which implies that if I use it in a website I am profiting from then a license is required. That is also the wording in the license price table.

My particular situation is that I'm developing a webapp for multiple non-profit organizations (currently 2 and I'm not sure what the prospects are for growth. It happens to be that I'm actually not billing for the time I'm spending getting it set up and configured (partially because I wasn't specifically requested to). On the other hand it increases the overall profitability and marketability of the system.

That said, I didn't open a github ticket to ask about my specific situation, but to suggest making the wording more precise and unambiguous.

**Comment by nafg** [comment]
On that note, what constitutes 1 commercial project -- would my situation count as 1 or 2?

**Comment by nafg** [comment]
I see on github the license is https://creativecommons.org/licenses/by-nc/4.0/ which has a partially broken link to https://creativecommons.org/faq/#does-my-use-violate-the-noncommercial-clause-of-the-licenses, which answers my questions to some degree but not completely.

**Comment by nafg** [comment]
I guess that also means there's an attribution requirement. What would that entail exactly?

**Comment by FrDH** [comment]
Thank you for the feedback, I'll see if I can clarify the website later on.

Having read your situation, I'd say one "single website license" would do as you're developing one end-product that only you commercially benefit from (as it "increases the overall profitability and marketability").

The attribution part is easy: just leave the copyright header (in mmenu.js) intact :)

**Comment by nafg** [comment]
Thanks!
