### ISSUE TITLE
Problem with all 3.0 versions for mmenu Contao module

### ISSUE THREAD

**Issue by Cleanerrr** [FrDH/mmenu-js#1056]
Hi,
i'm using mmenu in my meny Contao projects, but with last versions have some problems.
First, with last Contao 4.8 and last mmenu module 3.0.2 I have strange behavior of my web site. I have menu with submenu. Mmenu module presents first level menu with right arrow for opening wanted submenu item. Every time when we open next submenu item, all web site move up, sometimes down. 
Second problem is with first web site loading. When we open web site just for one sec we can see all mmenu items list on the left side. This list push all web site down and after one or two second everything is OK. 
For some project I tried to downgrade module version to 2.1.1 and in this case i solved all this problems.

**Comment by magic-77** [comment]
Hi,
i'm using newest Version (8) with Contao (4.7.6) too. The best solution is to modify the navigation template and inject scripts manually. See here https://www.isskd.de/

**Comment by FrDH** [comment]
I'm not the owner of the contao plugin so I honestly have no idea.
