### ISSUE TITLE
How to use parent menu without link magento

### ISSUE THREAD

**Issue by davirs** [FrDH/mmenu-js#1057]
Hi! I'm using this menu at magento. 
My menu has many levels, and it's the default magento menu.

When the menu render, the top level gets your category link. 
I need set this way:
If the top level has subcategories, the menu must remove the category link for the top level and set link only for subitens.. 

I think this menu already support this but I couldn't do this.

Can you help me?

![Screenshot_10](https://user-images.githubusercontent.com/4355062/64481322-64606900-d1b0-11e9-9cbf-3336aea510b3.png)

**Comment by FrDH** [comment]
This is the default behavior if you change your `<a>` to a `<span>`. Have a look at [the tutorial](http://mmenujs.com/tutorials/off-canvas/the-menu.html)

**Comment by FrDH** [comment]
If you're any good with regexp, I guess you could `<?php str_replace() ?>` any anchor with in the top level with a span.
Or, you could use JS to do the same thing, something like this:
````js
var menu = document.querySelector('#my-menu ul');
menu.children.forEach(( li ) => {
    let anchor = li.children[0];
    let span = document.createElement("span");
    span.innerHTML = anchor.innerHTML;
    li.insertBefore(span, anchor);
    anchor.remove();
});

new Mmenu( "#my-menu", {
   // options
});
````

Haven't tested it but should give you an idea of how to achieve the desired result.

**Comment by davirs** [comment]
thank you! This way will solve the problem
