### ISSUE TITLE
mmenu.js not supports marge JS

### ISSUE THREAD

**Issue by davirs** [FrDH/mmenu-js#1058]
I'm testing this menu with magento 1.9X
The menu works fine with magento and it's very easy do configure.
The problem is when js files marge is on. The script brokes at front end and stop works.

![Screenshot_21](https://user-images.githubusercontent.com/4355062/64629355-6e10e900-d3c9-11e9-8298-58301032ff9f.png)
someone can help me with this issue?

**Comment by FrDH** [comment]
Are you getting any errors in the console?
I'm not that familiar with Magento but in general I don't think mergin with other files should be an issue.

**Comment by davirs** [comment]
magento uses prototype and jquery. The code must have no conflicts. 
When the magento marge all files I see mmenu code at the file, but there is some incompatibility.. looks like the js load well but did nothing..

When I open your code at dreamweaver I receive some allerts like this:

![Screenshot_27](https://user-images.githubusercontent.com/4355062/64648614-a0ced780-d3f1-11e9-8152-ffdca988f516.png)
![Screenshot_23](https://user-images.githubusercontent.com/4355062/64648615-a0ced780-d3f1-11e9-8c73-524ea0b82ece.png)
![Screenshot_24](https://user-images.githubusercontent.com/4355062/64648616-a0ced780-d3f1-11e9-93c9-3cd39885af85.png)
![Screenshot_25](https://user-images.githubusercontent.com/4355062/64648617-a0ced780-d3f1-11e9-9713-615d61f659d1.png)
![Screenshot_26](https://user-images.githubusercontent.com/4355062/64648618-a1676e00-d3f1-11e9-8071-bf9890d5ac30.png)

And the minified js code looks like it's broken:
![Screenshot_31](https://user-images.githubusercontent.com/4355062/64648727-e8edfa00-d3f1-11e9-97dd-f3bd0699a0c2.png)
![Screenshot_30](https://user-images.githubusercontent.com/4355062/64648728-e8edfa00-d3f1-11e9-9cf3-11bb94d1276f.png)

**Comment by FrDH** [comment]
The "errors" are code styling errors, a good practice but not required and won't crash the script. If the merge tool aborts due to these errors, maybe you can configure it not to.
I'll have a look at these code styling errors but they have low priority to be fixed.

Why do you think the minified js is broken? Because of the colors? Editors often cant figure out how to properly color minified code.

**Comment by davirs** [comment]
Your code is very good and you use the best code standards!
Magento merge and minify doesn't work well with codes without ";" end of each statement.
When the code is minified, all spaces are deleted. Therefore, in browser rendering, some statements will merge and lose their function in the code, probably returning an error.
And when the file be merged, another code file will start immediately above the JS code. An error can interfere with the entire rendering.

Does it make sense what I said? I am committed to isolating the code park and will be back later

**Comment by davirs** [comment]
this site shows me a lot of information about what I need to fix and the positions of missing semicolon

http://jsutility.pjoneil.net/

![image](https://user-images.githubusercontent.com/4355062/65381885-930e3180-dcd0-11e9-843d-36bef8ee84f4.png)

**Comment by FrDH** [comment]
I believe removing the semicolon is a pretty standard thing in minifying scripts. So I'm not sure whether this is a shortcoming in Magento (a lot of scripts would break if an optional semicolon suddenly is required) or you're doing something wrong (I don't know Magento that well).

But if you need, you could try to create a custom build from the `.ts` files and skip the minifying part.
