### ISSUE TITLE
Problem with "rubber" effect on Apple device's

### ISSUE THREAD

**Issue by lexahead** [FrDH/mmenu-js#1060]
Hi! I found a problem with work this amazing (it's true!!) menu on Apple devices. First I see this in my project, but then, when trying to repeat on your site (mmenujs.com) - problem repeat!
Anyway browser - Chrome or Safari!
So!
On iPhone or iPad (in my case iPhone 7 plus and iPad Air (last iOs)) swipe menu from down to up, (menu must be longer than device screen!) - menu list jumps under the top of the device screen and frozen!! Links to submenu working, but top menu points are not returning from under the upper frame!
Cure for this - close menu and open again! Then all working fine while the next time repeats this action! 
On android phones - this problem is absent!
Sorry for so longer description!
![mmenujs1](https://user-images.githubusercontent.com/55308848/64904512-d74b7180-d6d3-11e9-8d7d-3874be6e53d0.jpg)
![mmenujs2](https://user-images.githubusercontent.com/55308848/64904513-d74b7180-d6d3-11e9-8d29-dc257ca6d413.jpg)

**Comment by FrDH** [comment]
Hi, thanks for reporting the issue.
It appears you don't even need to scroll / swipe fast, slowly dragging the panel also freezes the scrolling.
I'll have to investigate, for now: Try disabeling the `scrollBugFix` add-on and see if it helps. Will probably introduce some new unwanted behavior (it's there for a reason), but might help solve the issue:
````js
new Mmenu( "#my-menu", {
    scrollBugFix: false
});
````

**Comment by lexahead** [comment]
Hi! Thank you so much! 
This magic code correct this problem!
But I wrote a little different:

            document.addEventListener(
                "DOMContentLoaded", () => {
                    new Mmenu( "#menu", {
		       "extensions": [
                        "pagedim-black",
			"shadow-page"

                   ],
-->>   	        "scrollBugFix": false,			
                       "iconbar": {   etc.
 
Thanx again!
BR,
Alex

**Comment by FrDH** [comment]
> Disabling the scrollBugFix add-on will probably introduce some new unwanted behavior (it's there for a reason)

Could you try the menu at mmenujs.com again? I think I fixed it.

**Comment by lexahead** [comment]
mmenujs.com - All works fine!!
Thank you again!

**Comment by FrDH** [comment]
ok cool, will publish the update soon

**Comment by FrDH** [comment]
version 8.4.0 is now available.
