### ISSUE TITLE
Navbar still visible when sidebar is collapsed (+ duplicated background)

### ISSUE THREAD

**Issue by Benreuveni** [FrDH/mmenu-js#1061]
Howdy!

I'm trying to integrate this into my website and I'm honestly struggling. I've made some headway looking at the advanced example on this git, but have run into a few issues I'm not sure how to tackle. I can't seem to find any help on this, so please forgive me.

Here's a Fiddle: https://jsfiddle.net/Tooltip/d8unrbk7/21/

Basically, when the sidebar collapses, it still seems to be visible "behind" the page. How can I hide all but the left-most area that's meant to be visible?

Also, I've noticed that the navbar seems to duplicate my background. I've tried all I can think of to eliminate this issue, but haven't had any luck.

Thanks a ton!

**Comment by FrDH** [comment]
Try adding a background color to the `body`, the menu needs some solid background to hide itself behind.
````css
background: url("https://www.benreuveni.com/sandbox/images/side-bar.svg") right repeat-y, url("https://www.benreuveni.com/sandbox/images/background.svg") no-repeat;
background-color: #111;
````

**Comment by Benreuveni** [comment]
Excellent, that did the trick! Thank you.

I noticed a couple more things, the duplicated background is still happening, and it seems to be related to how the menu is initially rendered on page load. If the page is larger than the view (i.e. horizontal scroll bar), the background-image will duplicate just off screen. And same for vertical. 

There should never be a horizontal scroll on this layout because it's a grid with a single column. 
(I tried assigning the nav to its own column but it didn't take.) It also seems like the menu lets the page hover over and obscure it in this case which is strange.

You can see it in the fiddle if you make the preview pane about half your screen, then scroll right. 

couple of examples:

![duplicated_background](https://user-images.githubusercontent.com/12500072/65042475-82e80200-d91e-11e9-8ece-9b1c01970eb4.png)
![duplicated_background2](https://user-images.githubusercontent.com/12500072/65042524-9f843a00-d91e-11e9-91ba-7713e70db600.png)

Any ideas?

**Comment by FrDH** [comment]
About the horizontal scroll, see if going back to version 8.2 helps.
The double background might be due to the page (`.mm-page') has `background: inherit`.
Try moving the `background` from the `body` to `#page`.

**Comment by Benreuveni** [comment]
OK, so moving background images and background-color to #page worked in removing the duplicate.

I downgraded to v8.2 and I'm still getting scrolling. 

In addition, I noticed another issue where the navbar extends beyond the page content. Playing around with it a bit, it seems like when the navbar is opened, it lengthens the page (from 1024 to 1581 for example). This is noticeable specifically when Sidebar is enabled. 

OK after some investigation, when sidebar is disabled and the nav-bar is opened, it definitely resizes the page. Also, since it takes you to the top of the page and you cant scroll while the navbar is open, it's possible the effect below is happening, we just can't ever see it.

When Sidebar is enabled, I think the navbar is still resizing the page for itself, but not for the rest of the content and then we get the effect in the image below. It becomes more pronounced the more content there is on the page (i.e. the more you can scroll).

![duplicated_background3](https://user-images.githubusercontent.com/12500072/65195500-2a5f5480-da45-11e9-8358-4f344866f71f.png)

Sorry, I feel like I'm breaking all sorts of things, and it's totally possible it's because of the way I've written the site, but I feel like it's pretty straight-forward. Just a 1x5 grid and some divs.

Thanks for helping with these issues.

**Comment by FrDH** [comment]
Is there an online example?
See if some of your css is overriding the mmenu css. For example 
````css 
body > * {
   position: relative !important;
}
```` 
will mess up the menu.
Hope this helps.
