### ISSUE TITLE
Issue with mobile devices and sub menus

### ISSUE THREAD

**Issue by mrdigitalau** [FrDH/mmenu-js#1062]
Hi Fred,

I am having an issue with making the submenus work on mobile devices. Specifically my Samsung s10 using latest version of Chrome.

I followed your tutorial to a tee and the menu works wonderfully on a desktop device
When I then opened the website on my mobile, the menu displayed but the arrows for the sub menu didn't. It looked as if it was being cut off.

I ended up fixing it by removing "position:fixed" from .mm-menu_offcanvas from the css file and it seemed to fix it. I am not sure if this is a bug or it's just happening it me?

See pics before and after here: https://imgur.com/a/GuY7J70

I am wondering if you've encountered this before?

Cheers!

**Comment by mrdigitalau** [comment]
After removing position:fixed, I cant scroll down now, of course, so silly of me to suggest it.
Have you got any idea why the menu would be getting cut off so we can't see the dropdown arrows on mobile devices? Cheers

**Comment by mrdigitalau** [comment]
FYI - I just reverted to version 7.3.3 and the issue now resolved.
I am not sure if this issue is just because of my set up but just thought you should know.

**Comment by FrDH** [comment]
Do you have the same issue on mmenujs.com ?
Could you create an online example I could have a look at?

The menu appears to be working OK on Chrome on an iPhone (don't have access to any other phone at the moment).

**Comment by VitAm1nKa** [comment]
Hello! 

> Hi Fred,
> 
> I am having an issue with making the submenus work on mobile devices. Specifically my Samsung s10 using latest version of Chrome.
> 
> I followed your tutorial to a tee and the menu works wonderfully on a desktop device
> When I then opened the website on my mobile, the menu displayed but the arrows for the sub menu didn't. It looked as if it was being cut off.
> 
> I ended up fixing it by removing "position:fixed" from .mm-menu_offcanvas from the css file and it seemed to fix it. I am not sure if this is a bug or it's just happening it me?
> 
> See pics before and after here: https://imgur.com/a/GuY7J70
> 
> I am wondering if you've encountered this before?
> 
> Cheers!

I found hoe to resolve your problem! Change Header tag "viewport" like this: `width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no`

**Comment by mrdigitalau** [comment]
Hey @VitAm1nKa , thank you. 
I can confirm that 
`
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">`

Fixes the issue I mentioned with the latest version of mmenu.

Thank you @FrDH for an amazing plugin.

Cheers!

**Comment by andrewmenich** [comment]
For future readers: 

Although this solution works, it's not best practice as it disables a feature that most users expect (pinch to zoom). If you must use this, I suggest only changing the viewport meta property when the menu is open: 

```js
   const menu = new Mmenu("#main-navigation");
   const menuAPI = menu.API;
   const viewportMeta = document.getElementById('viewport-meta');
   const defaultViewport = viewportMeta.getAttribute('content');
   const staticViewport = "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no";

    menuAPI.bind('open:start', function(){
        viewportMeta.setAttribute('content', staticViewport);
    });
    menuAPI.bind('close:start', function(){
        viewportMeta.setAttribute('content', defaultViewport);
    });

```

**Comment by meanderix** [comment]
As far as I can tell, setting `minimum-scale=1.0` is sufficient for the menu to render correctly. This will allow users to zoom in on the page with `user-scalable=yes`.
