### ISSUE TITLE
Issue with setSelected addon (hover and current not working)

### ISSUE THREAD

**Issue by yesh** [FrDH/mmenu-js#1063]
hello there,

I'm trying to get the current menu item selected with auto detect from url, but neither `hover` nor `current` options are working.
only the `parent` option is working, successfully adding the `mm-listitem_selected-parent` class.

are those options not compatible with some other addons in use (eg. colums)?

also I'm using mmenu without the standard html wrapper structure, because it is working inside an always visible sidebar, extending with new columns for the submenus.

to test the `current` option I'm using the link `http://example.local/red.php`

this is the init code:

## JS
```
const node = document.querySelector('.menu'),
          menu = new Mmenu(node, {
            columns: true,
            offCanvas: false,
            navbar: false,
            setSelected: {
              hover: true,
              current: true,
              parent: true
            },
            extensions: [
              "fx-panels-slide-0"
            ]
          })
```

## HTML
```
<nav class="menu">
  <ul>
    <li><a href="#" class="menu__item">Lorem</a></li>
    <li><a href="#" class="menu__item">Ipsum</a></li>
    <li>
      <span class="menu__item">Dolor</span>
      <ul>
        <li>
          <a href="#" class="menu__item">Xyz</a>
        </li>
        <li>
          <a href="#" class="menu__item">Hipsum</a>
        </li>
        <li>
          <span class="menu__item">Black</span>
          <ul>
            <li>
              <a href="#" class="menu__item">1</a>
            </li>
            <li>
              <a href="#" class="menu__item">2</a>
            </li>
          </ul>
        </li>
        <li>
          <a href="#">Asd</a>
        </li>
      </ul>
    </li>
    <li><a href="http://example.local/red.php" class="menu__item">Red</a></li>
  </ul>
</nav>
```

is this a bug? or am I doing something wrong?

**Comment by yesh** [comment]
btw, I'm using version 8.4, is it in beta?

**Comment by FrDH** [comment]
Its not in beta, the commit WIP came from the develop branche.

Are you sure `http://example.local/red.php` is not a local URL? I can't visit it.
I had a look at the `hover` option on mmenujs.com and it appears to work as intended (the menu item colors when hovering over it). 

I think the `current` option should work with this setup. If you can provide a working example, I can do some debugging.
