### ISSUE TITLE
Submenu is not opening in Divi theme in wordpress

### ISSUE THREAD

**Issue by Yogeshgupta97** [FrDH/mmenu-js#1064]
I'm using mmenu wordpress plugin in Divi theme Wordpress. In mobile view sub-menu is not opening.

**Comment by FrDH** [comment]
That's unfortunate, please give this solution a try:
https://github.com/FrDH/mmenu-js/issues/1051

**Comment by Yogeshgupta97** [comment]
Thanks for your reply. #1051 issue is same issue that I'm facing write now.
