### ISSUE TITLE
WordPress plugin problems with wpadminbar

### ISSUE THREAD

**Issue by seyoum** [FrDH/mmenu-js#1065]
When I use the WordPress plugin I get problems with the "wpadminbar" being pushed down when the menu opens.

![mmenujs and weadminbar problem](https://user-images.githubusercontent.com/15233794/66745120-79e74380-ee7e-11e9-9a87-d7d1958ffa1f.gif)

You can test it [here](https://eid.ufc.mybluehost.me/wptest/)if you want (note you have to resize screen smaller to see the menu button.)

I am using a completely unmodified version of the [underscores](http://underscores.me) framework and I have not made any changes to the theme. I also do not have any other plugins running. It is a completely fresh installation so it should be fairly easy to replicate.

Please advise.

**Comment by seyoum** [comment]
I think I might have solved it with:

```
.site-header {
	background-color: transparent;
	box-shadow: 0 4px 12px 0 rgba(0, 0, 0, 0.05);
	padding: 10px;
	position: sticky;
	top: 0;
	left: 0;
	right: 0;
	z-index: 99989;
}
// If user is logged in push down #page to make room for the admin bar
body.logged-in #page {
    top: 32px;
    z-index: 99990;
    width: 100%;
    position: relative;
}

@media screen and (max-width:782px) {
    body.logged-in #page { top: 46px; }
}
```

But I will have to test further to be sure. I just wanted to give a heads up.

**Comment by FrDH** [comment]
There's not much I can do about this. The WP admin bar is positioned relative to its first ascending parent that has a `transform` css property (which defaults to the `<body>`), when the menu opens, a `transform` is applied to the `<div id="page">`. You could try to override some CSS for when the menu is opened:
````css
html.mm-wrapper_opened body {
    padding-top: 0 !important;
}
html.mm-wrapper_opened #page {
    padding-top: 40px !important;
}
````

Hope this helps.
