### ISSUE TITLE
menu is not working in Ipad 1

### ISSUE THREAD

**Issue by rajeshoptiinfo** [FrDH/mmenu-js#1066]
Any update on this? I haven't had any other complaints so I'm going to assume this issue is due to something on your end.

_Originally posted by @FrDH in https://github.com/FrDH/mmenu-js/issues/427#issuecomment-143031775_

-----------------

i have used mmenu in lots of sites and suddently i hve come to know from clients that menu is not working in Ipad 1 which has safari and ios version 9.3...

**Comment by FrDH** [comment]
Have you tried debugging anything? Are there any errors in the console?
I can't think of a reason for the plugin not to work on an iPad 1 using iOS 9.3
Is the menu on mmenujs.com working on those iPads?

**Comment by rajeshoptiinfo** [comment]
mmenujs.com is also not working on ipad1, i have replaced mmenu js with older version(jQuery mmenu v7.2.2) and it works...

**Comment by FrDH** [comment]
My guess is, iOS 9 needs polyfills for lacking js features, but without some more information about why it isn't working, I can't fix anything (I don't have access to an iPad 1)

**Comment by FrDH** [comment]
If anyone can debug why the iPad 1 isn't working, I'd be happy to provide the needed fix.
