### ISSUE TITLE
The menu gets stuck when scrolling

### ISSUE THREAD

**Issue by MaryMiu** [FrDH/mmenu-js#1068]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14906765/67090851-59e4b680-f1d5-11e9-9e7c-033e7d35ab81.gif)

It can be fixed?

**Comment by FrDH** [comment]
A bit more information would be helpfull. I tried to reproduce the issue but could not get it not to work.
What device are you using? What are the exact steps to reproduce the issue?

**Comment by MaryMiu** [comment]
Iphone 5S, IOS12.3.1, Safari
Open the menu and scroll

**Comment by FrDH** [comment]
I don't have access to an iPhone 5S (and using browserstack everything appears to work as intended).
You could try to disable the `scrollBugFix` add-on and see if that fixes the issue:
````js
const menu = new Mmenu({
    scrollBugFix: false
})
````
It should probably not be disabled, but at least then we'll be closer to fixing the issue.
