### ISSUE TITLE
Size of submenu changes after clicking on a subpage

### ISSUE THREAD

**Issue by matthaa** [FrDH/mmenu-js#1071]
Using the demo site in actual download package (version 8.4.0) the size of submenu (.mm-listview, .mm-navbar) changes after clicking on a subpage to size 440px. Therefore it is not possible to use the menu in sizes smaller than 580 Pixel.
![mmenu1a](https://user-images.githubusercontent.com/6637510/67429440-73746c80-f5e0-11e9-90df-79f3d194d8c7.png)
![mmenu2a](https://user-images.githubusercontent.com/6637510/67429453-796a4d80-f5e0-11e9-8584-6ad6f2d5f0bd.png)
How to fix this?
Thanks.

**Comment by matthaa** [comment]
The screenshots above are taken from Google Chrome on MacOS using dev tools. The problem also occurs with Chrome on Android. With Safari on iOS everything seems to be fine (I can only test this by using Xcode Simulator).

**Comment by matthaa** [comment]
Seems to be a bug in Version 8.4.0. Using dist/mmenu.js of version 8.2.3 everything works as expected.

**Comment by matthaa** [comment]
to reproduce the issue you have to use Chrome dev tools (toggle device toolbar and choose for example iPhone X) or use an android phone with Chrome. First view is ok but after clicking on the arrow of a menu item with subpages („About us“) the size is not correct any longer. You will notice that the menu item „The team“ has lost its arrow and the Back Link (above: „About us“) is not centered. I copied the source (8.4.0) to here: https://dev.matthaa.de/mmenu/demo/default.html
Using dist/mmenu.js from Version 8.2.3 does not produce this behavior.

**Comment by FrDH** [comment]
Another fix appears to be changing `width: 80%;` to `width: 80vw;`, I guess that shouldn't break anything.

**Comment by matthaa** [comment]
I can confirm that after adding minimum-scale=1.0 to the viewport tag it works. Thanks.
