### ISSUE TITLE
setSelected not working properly in latest version 8.4.1

### ISSUE THREAD

**Issue by udarts** [FrDH/mmenu-js#1072]
I trying to get the setSelected to work, but so far the correct classes are not set, e.g. mm-listitem_selected, mm-listitem_selected-parent

So the submenu doesn't stay open on the correct url.

The documentation is not very clear on this.

Cheers

**Comment by FrDH** [comment]
What have you tried so far?
By default you only need to add the classname "Selected" to the `<li>`.
Check https://mmenujs.com/tutorials/off-canvas/the-menu.html (under "Selected item").

**Comment by udarts** [comment]
Hi, thanks for your reply.

I had it setup as mentioned in the documentation, with the selected classname, and I can see the submenu li has the "selected" class, but the submenu remains closed.

Do I need to add the addons folders, etc also in my project js folder, or just the mmenu.js?

**Comment by FrDH** [comment]
So did you add the classname "selected" or "Selected"?
Please provide an online example because I simply can't guess why it isn't working on your end.

**Comment by udarts** [comment]
I added selected (not with cap S), should it be with cap S?

**Comment by udarts** [comment]
So, I had to add the Selected (with caps).
Now it works.
Thanks.
