### ISSUE TITLE
How to disable sliding for Vertically opening submenu?

### ISSUE THREAD

**Issue by Pemson18** [FrDH/mmenu-js#1074]
I have three level menu with first two level sliding but the thrid level is a vertical submenu and opens under the level 2, but In Mmenu when I try to expand the level 3 submenu it slides from right to left. Please provide a fix.

**Comment by Pemson18** [comment]
Also I'm using two columns

**Comment by FrDH** [comment]
I think the two should be compatible, is there an online example? Preferable a codepen or something similar

**Comment by Pemson18** [comment]
https://codepen.io/pemson-pereira/pen/QWWagaL

**Comment by Pemson18** [comment]
Please navigate to about us > the team

**Comment by FrDH** [comment]
I'll see if this bug can be fixed, just note that you will have to upgrade to version 8.x to get it working.

**Comment by FrDH** [comment]
Sorry for the long delay. Should be fixed in version 8.5.7
