### ISSUE TITLE
Since 8.3.0, 2 cosmetic bugs with Mobile Chrome 78 and Safari 13

### ISSUE THREAD

**Issue by pozhonk** [FrDH/mmenu-js#1076]
Since version 8.3 (and still with 8.4.1), I have 2 cosmetic bugs with Chrome 78 and Safari 13. They can be reproduced with the demo file default.html.
These bugs were not there with version 8.2.3.

These bugs happen only **in mobile phone format only**. It is found with iPhone iOS 13, I don’t have an Android phone to validate the bug with Chrome. I checked everything with the desktop version of Safari 13, Chrome 78 (and also 75) and Firefox 70 with the adaptive view, and a viewport of 320 pixels.

**1-** With Chrome, see the picture below with 2 cosmetic bugs. Long title items are not truncated. The “About Us” submenu item has no “>” symbol on the right. Sometimes, these bugs don't show on the first run, if so, click on a submenu then go back to the parent menu.

After investigation, it is only the script that introduced this bug, not the CSS file. Using version 8.2.3 of the JS script and keeping version 8.3 (or 8.4.1) of the CSS file returns a normal behavior.
![Chrome78-mmenu830-bug-js](https://user-images.githubusercontent.com/57560151/68527662-a65d7680-02e9-11ea-9f82-af1b178b5cd6.png)

**2-** With Safari, see the picture below. I edit the title "The Team" for a long title menu “The Super Long Menu Title Introducing the Team”. This long title is truncating the first letter on the left instead of doing it on the right, displaying “ong Menu Title Introducing the T”. For narrow screens, it should display “The Super Long Menu Title Introduc…”.
 
After investigation, this time it is version 8.3 CSS file that introduced the bug, not the JS file. Using version 8.2.3 of the CSS file with version 8.3 (or 8.4.1) of the JS file returns a normal behavior.
![Safari13-mmenu830-bug-CSS](https://user-images.githubusercontent.com/57560151/68527642-70b88d80-02e9-11ea-8e8c-328073f4f6df.png)

**Comment by FrDH** [comment]
Please check if the demo file has a viewport meta tag that restricts the user from scaling the page,
for example:
````html
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
````

This might fix the first issue.

For the second issue, I found that removing `display: flex;` from the title enables the ellipsis to work, but now the text is aligned to the top of the navbar instead of the middle.
I guess I could add a `line-height` so the text is aligned to the middle, but I'm not a big fan of that kind of workaround.

I'll see if I can find a better fix. Let me know if you find any helpfull information.

**Comment by pozhonk** [comment]
Thank you for your quick answer.

Indeed, defining the following viewport has solved the cosmetic bug with Chrome:
`<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=no">`

Changing the user-scalable from yes to no is the solution.

Next, the cosmetic bug happening with Safari is now affecting Chrome and Firefox the same way. It seems to be a direct consequence of the user-scalable definition. Thanks to your idea, I have found a workaround that is working on all 3 browsers in mobile viewport.
On the CSS file, I add 2 more 'flex' settings for the navbar title:
`.mm-navbar__btn:not(.mm-hidden)+.mm-navbar__title:last-child{
	padding-right:50px;
	display: inline-flex;
	flex: 0 0 auto;
}`

'display: inline-flex;' does not seem to be mandatory here (it works fine without it), but I prefer to add it to avoid any problem.

However, submenu titles in the navbar are not centered anymore but aligned on the left instead. Long titles are still not truncated but the overflow is hidden on the right. Maybe you will find a better solution in the future to add an ellipse and center the submenu titles again. 
Today, I can live with that.

**Comment by FrDH** [comment]
Try the new version 8.4.3

**Comment by pozhonk** [comment]
One word: PERFECT.
Version 8.4.3 solves the cosmetic bug in mobile Safari, Chrome and Firefox and everything behaves as expected.
Thank you.
