### ISSUE TITLE
When closing mmenu, element does not reflow.

### ISSUE THREAD

**Issue by ok-ttc** [FrDH/mmenu-js#1077]
I have a page with mmenu on the left, a topbar and a css-grid beneath that.

The topbar is set to width 100%.

When minimizing mmenu, the topbar does not reflow properly. When the page loads, the right end of the bar is rendered off the viewport with exactly the width of mmenu. Chromium renders the bar correct on load, but after closing and opening mmenu, it isn't stretched 100% across anymore, but is short by exactly the width of mmenu.

This means that when mmenu is minimized, not all elements on the page reflow properly.

Here screenshots of the Chromium problem:

On load:
![bug_mmenu_reflow_1](https://user-images.githubusercontent.com/57516345/68617381-debea980-04cf-11ea-887b-21baa1e81ee0.png)

After minimizing mmenu
![bug_mmenu_reflow_2](https://user-images.githubusercontent.com/57516345/68617443-fbf37800-04cf-11ea-8fef-d772676de92e.png)

And the same for Firefox:

On load (I pasted the horizontal scrollbar in to show the overflow):
![bug_mmenu_reflow_3](https://user-images.githubusercontent.com/57516345/68617985-0a8e5f00-04d1-11ea-8275-80e039c821ae.png)

After minimizing mmenu (note also the missing icon on the right):
![bug_mmenu_reflow_4](https://user-images.githubusercontent.com/57516345/68618031-24c83d00-04d1-11ea-8c20-3401af1f3928.png)

What can be the issue?

**Comment by FrDH** [comment]
First thing that come into mind is the viewport meta tag, make sure you have one with "scalable=no" in it:
````
<meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=no">
````

If that doesn't help. Is there an online example I could have a look at?

**Comment by ok-ttc** [comment]
Thank you for your response. Apart from the "initial-scale", I already had that.

Here is an example: [top-menu-bug-example.zip](https://github.com/FrDH/mmenu-js/files/3863555/top-menu-bug-example.zip)

Just unpack it and run the index.html. When closing and opening MMenu, the top-bar does not resize as it should.

**Comment by FrDH** [comment]
Sorry for the late reply. Did you find what was causing the issue?
Does it help if you remove any of the styles applied to the top-bar? There are also a couple of js errors in the console, see if fixing those help.
