### ISSUE TITLE
mmenu.js settings overwritten continually

### ISSUE THREAD

**Issue by SJNBham** [FrDH/mmenu-js#1079]
We're using mmenu 5.3, WordPress 5.3, and hosting with WPEngine. We're trying to add some additional options like a close button, custom search placeholder text, etc. We can make the changes to mmenu.js and the site reflects the new features. However, usually in less than a minute, our changes are removed and the options are set back to only what is specified in the mmenu GUI settings screen. We're not using the "Save and Publish" option after we add our custom options directly to the mmenu.js file. Even if we don't change anything, the mmenu.js file appears to be "modified" continually (same with mmenu.css). So two questions:

1) How can we prevent the mmenus.js file from being overwritten continually so we can retain our options added after setting the GUI settings?

2) Even better, is there a place to add the additional options so they're added to the GUI settings instead of having to add them back any time a change is made in the GUI?

Thanks for any info you can pass along.

**Comment by FrDH** [comment]
The plugin saves the mmenu.js and mmenu.css files only after saving the changes, I can't think of any reason for it to happen automatically.
There currently is no way to add additional options, If you're not going to override the JS using the GUI, you could ofcourse uninstall the plugin right after saving and copying the .js and .css file and include them manually in your project.

**Comment by SJNBham** [comment]
Hi Fred,

When I disable the mmenu.js WordPress plugin, the files stop getting modified automatically. I suspect it has something to do with a script that's loaded when you access the WordPress dashboard. When I'm logged in and viewing the website, the files don't seem to update. But when I go to any screen in the WordPress dashboard, the mmenu.js file gets updated/modified about every 10 seconds. If I stay out of WordPress altogether and just monitor the file via FTP, it never changes - even with teh mmenu.js plugin enabled.


_____________________________________
Steven Niedermeyer

Web Systems Analyst
Information Technology Services
City of Bellingham, Washington
sjniedermeyer@cob.org
1+ (360) 778-8058
www.cob.org<http://www.cob.org>



My incoming and outgoing email messages
are subject  to public disclosure requirements per RCW 42.56

　

________________________________

**Comment by SJNBham** [comment]
Would it be better to use the non-WordPress version of mmenu.js?  I see the change log for the WordPress plugin hasn't been updated for a year.  [https://mmenujs.com/wordpress-plugin/changelog.html](https://mmenujs.com/wordpress-plugin/changelog.html) while the non-WordPress version appears to still be receiving regular updates: 
[https://mmenujs.com/docs/changelog.html](https://mmenujs.com/docs/changelog.html)

I was mistaken in my opening comment for this issue - we're actually using mmenu version 2.8.2 (WordPress plugin).

**Comment by FrDH** [comment]
The two serve a different purpose. If you're looking for an easy to implement solution that doesn't require much frontend development, I'd go for the WP plugin. If you're familiar with frontend development (especially javascript) and are willing to learn how to use the plugin, I'd go for the .js plugin.

**Comment by SJNBham** [comment]
OK - my preference would be to use the WordPress plugin. Is there a way to get the latest updates incorporated into the WordPress plugin? Also, how can I determine why the manually configured options keep getting overwritten - even when I'm not using the mmenu plugin save option?

**Comment by FrDH** [comment]
Sorry for the late reply, the WP plugin will be updated in time to use the latest version of the .js plugin. That however does not automatically mean it will have all options available. The WP plugin is intended to be an easy to use wrapper, meaning the options are intentionally limited with (hopefully) good defaults.

**Comment by webmaster-cob** [comment]
Thanks for the update. I needed to move on to another solution that has faster support turnaround for now. Might circle back around once the WordPress version receives an update.
