### ISSUE TITLE
class="Selected" not working in 7.3.3

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/mmenu-js#1080]
Fred
This code section use to work.    i have tried a few things but when i review the HTML in the chrome debugger the class is not there.    

it never highlights that list item.    i use the API method in different files and that works. 

      <li class="Selected" ><a onclick="window.location = '?';">
          <img class="avatar-med" src="avatar/All" alt="All" class="avatar">All Rooms</a></li>

thanks

**Comment by FrDH** [comment]
That's odd, that should work as intended.
Is there an online example I could have a look at?
