### ISSUE TITLE
Bootstrap modal with backdrop not working

### ISSUE THREAD

**Issue by udarts** [FrDH/mmenu-js#1081]
Hi,

I am using your plugin and also need to use modal from bootstrap, but when opening the modal, the popup itself is behind the backdrop, this is due to the position of a parent element(s).

I can fix it by not using the backdrop, but I would like to use it.

I know that your plugin also uses position for several reasons.

Is there a way to still use it?
I haven't found a solution for it, so if someone has an idea on how to do this?

**Comment by udarts** [comment]
Ok, I think I have a solution (not sure if its the correct one). As the modals I use have data from the database. After they are rendered (via php). I move them with jquery to just before the body closing tag.

If there is any other solution for this, I am open for suggestions.

**Comment by FrDH** [comment]
Is there an online example?

**Comment by Edsol** [comment]
same problem, any fix?

**Comment by FrDH** [comment]
Without an online example, there is not much I can investigate, you could have a look at the basic tutorial for more insight in how the plugin works:
https://www.mmenujs.com/tutorials/off-canvas/

Hope this helps.

**Comment by vuong-bse** [comment]
I resolved it with https://github.com/FrDH/mmenu-js/issues/898
