### ISSUE TITLE
Mobile browser address bar overlaps on fullscreen mmenu.js

### ISSUE THREAD

**Issue by SJNBham** [FrDH/mmenu-js#1082]
Trying to use the full screen options for mmenu.js via the WordPress plugin. When the full screen mmenu opens, some mobile browser top bars cover the top section of the mmenu. So if you have the menu search option turned on or a logo, it's obscured by the browser top bar.  You can reproduce with:

Android 9 + Chrome 78.0.3904.96 = overlaps
iOS 13.1.2 + Safari + iPhone 5E = overlaps

Test site: [https://cityofbellingh.wpengine.com/](https://cityofbellingh.wpengine.com/)

This might be related: [https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser)

**Comment by SJNBham** [comment]
Would be great if there was a way to even add some padding at the top so the mmenu still takes up the whole screen, but the search/breadcrumb bars are displayed a bit further down the screen so they don't get overlapped.

**Comment by FrDH** [comment]
Have you tried changing the `top` value for the menu?
````css
.mm-menu {
   top: 20px !important;
}
````

**Comment by SJNBham** [comment]
That does push the menu down, but the mmenu no longer is full screen. Meaning the page under the mmenu is dsiplayed (e.g. sliver of the logo and other mobile menu icons. I was hoping for a way to push the content of the mmenu down a bit to provide some top padding and avoid the overlap while keeping the mmenu filling the entire screen.

**Comment by FrDH** [comment]
For now this is the only solution I think. Browsers should simply obay the 100vh correctly.
