### ISSUE TITLE
Show full breadcrumb 

### ISSUE THREAD

**Issue by SJNBham** [FrDH/mmenu-js#1083]
I'm trying to get the breadcrumb in the mmenu panel to not shorten with ellipses. I'd like the breadcrumb to push down to additional rows if needed when the trail becomes too long for a single line. I attempted to achieve this with the following CSS changes. Everything seems to work except the submenu loses its ability to scroll. Here's a test site. 

To reproduce the scrolling issue, open the site in a mobile browser on a phone in landscape orientation, open the mobile menu, and navigate to: Menu > Government > Departments (the departments aren't scrollable). 

To observe the desired breadcrumb behavior navigate to: Menu > Services > Housing and Human Services (you'll see the breadcrumb continues on the next line).

[https://cityofbellingh.wpengine.com/](https://cityofbellingh.wpengine.com/)

```
.mm-wrapper_opening .mm-menu_position-bottom {z-index:1000;}
.mm-navbar {
	height:auto !important;
}
/*Trying to temporarily address the mobile browser toolbar overlap issue*/
.mm-navbars_top {
	position:relative !important;
       margin-top:70px;
}
.mm-panels, .mm-panels>.mm-panel {
	position:relative !important;
       top:0px;
}
.mm-menu_navbar_top-2 .mm-panels {
	position:relateive;
       top:unset;
}
.mm-navbar__breadcrumbs {
	white-space:normal;
       text-overflow:unset;
       overflow:auto;
}
.mm-tabstart {display:none;}

```

**Comment by FrDH** [comment]
You can't change the `position` to `absolute`. This isn't going to work.

**Comment by SJNBham** [comment]
Is there some alternate CSS that will allow for the full breadcrumb to show and retain the rest of the mmenu functionality?

**Comment by FrDH** [comment]
Not really, not without changing the entire idea of how the css is set up.

but if you really want, you could try something like this:
````css
.mm-menu {
   display: flex;
   felx-direction: column;
}
.mm-navbars_top {
   position: relative;
}
.mm-panels {
   flex-grow: 1;
   position: relative;
}
````

With this, the navbars should be allowed to have a variable height and the panels should still slide and scroll as intended.
Just note that I did not test this and it might introduce new issues when combined with other options.

**Comment by SJNBham** [comment]
OK - rather than take the risk of breaking other features and diverging from the base code, I'll get by with shortening my menu options for now. It'd be great to have the option for the breadcrumb to grow in the WordPress plugin in the future. Thanks for your time on this.
