### ISSUE TITLE
Adding back to main menu (start point) on click on submenus

### ISSUE THREAD

**Issue by taljance** [FrDH/mmenu-js#1088]
Hello ...
Maybe there is already solution, I searched in issues (current/finished) but no luck.

Is there way on 2nd lvl or submenu opened on right to be added button which will bring menu on start point, without closing? see pic below.

![image](https://user-images.githubusercontent.com/8223010/69498021-9b0e6b80-0ee3-11ea-99d6-0673015b85b5.png)

Thanks in advance! Plugin ROCKs!

**Comment by FrDH** [comment]
You can use the navbars add-on to add some HTML, any anchor that targets the a panel will open it. Assuming the main panel has `id="main-panel"`, this will open it: `<a href="#main-panel"></a>`.

Something like this:
````js 
new Mmenu("#my-menu", {
   navbars: [{
      content: ["prev", "title", "<a href='#main-panel'>Main panel</a>"]
   }]
})
````

Hope this helps.

**Comment by taljance** [comment]
Hello...thanks for the reply, 
but, like this I lose search from content from navbars addon

![image](https://user-images.githubusercontent.com/8223010/69503419-c14efe00-0f19-11ea-9697-4f7656ff1677.png)

Need like this if its possible, "like custom" link inside subfolders not on main (first view of all main folders and outside from navbars addon as I need search box there.

Thank you in advance.

**Comment by FrDH** [comment]
You can put both the searchfield and the buttons in the navbars add-on. To disable the added button on the main panel, I guess you could hook into the "openPanel" method using the API.
