### ISSUE TITLE
Uncaught TypeError: Cannot read property 'children' of undefined - keyboardNavigation

### ISSUE THREAD

**Issue by ajay0130** [FrDH/mmenu-js#1089]
Hi,

I am using jQuery mmenu v5.1.2 & jquery-1.11.3.min.js, and i have struck in a issue for accessibility, the issue i am getting in 'jQuery mmenu keyboardNavigation add-on'
(jQuery.mmenu/5.7.4/addons/keyboardnavigation/jquery.mmenu.keyboardnavigation.min.js)

please follow the below mention error.

TypeError: this.$pnls is undefined (getting in firefox)

Uncaught TypeError: Cannot read property 'children' of undefined (getting in chrome)

please help to get ride of this issue..

**Comment by FrDH** [comment]
If you're using version 5.1.2, you can't use addons from 5.7.4
I'd strongly recomment updating to a newer version (7 if you want to stick to the jQuery plugin).

**Comment by ajay0130** [comment]
Thanks for letting me know.
