### ISSUE TITLE
iOS with menu open, main content can be slid over menu on touch drag to left

### ISSUE THREAD

**Issue by jmalatia** [FrDH/mmenu-js#1092]
With mmenu open AND the list of menu items is long enough for the menu to scroll, if you touch on a menu item (for example dead center horizontally), hold and drag to the left, the main body content of the web page will slide over with your drag (the overlay stays in place).  Tested on iOS Safari and Chrome.  This does not happen if the list of menu items is not long enough to scroll.

This happens on the main mmenu home page as well as in our website (using v8.4.0).

![image](https://user-images.githubusercontent.com/5606334/70554468-c8455580-1b42-11ea-94ef-e6d84a37d1a0.png)

![image](https://user-images.githubusercontent.com/5606334/70553981-d5ae1000-1b41-11ea-8e9c-775dc0f6a964.png)

![image](https://user-images.githubusercontent.com/5606334/70554092-16a62480-1b42-11ea-8c03-830a60fa1ceb.png)

![image](https://user-images.githubusercontent.com/5606334/70554686-3ab63580-1b43-11ea-832a-1380570fcf66.png)

**Comment by FrDH** [comment]
I've seen that behavior before, but now I can't reproduce it. You could try if adding this helps:
````css
html {
   height: 100%;
    overflow: hidden;
}
body {
   height: 100%;
   overflow: auto;
}
````
