### ISSUE TITLE
Change menu under seo requirements

### ISSUE THREAD

**Issue by maria-anik** [FrDH/mmenu-js#1093]
Hi!
I am immensely grateful for your work! 
I'm from Russia, I'm sorry for the mistakes!

The requests of seo-specialists are senseless and merciless) The essence of the problem.

They want the parent section to have a link in the source code, but there is no transition on it as if there was a "span".
https://prnt.sc/qa8s7a

That is, by clicking go to the subsection. (e.g. # menu_ul_660) https://prnt.sc/qa8wyb
All in order to open a section in a new tab when right-clicking. And hover https://prnt.sc/qa9ijh. 

I found an example - https://jsfiddle.net/djlerman/3zs1mo3x/ 

I'm use jquery-2.1.3. My code https://prnt.sc/qa97c4
I tried to repeat the example, but the openPanel function throws an error
https://prnt.sc/qa98yv
How to fix it?
If this problem is would resolved, I'm going to simulate a click on the arrow when I click on the link
https://prnt.sc/qa9dv7

What do you think?
Thanks for the help!!

**Comment by FrDH** [comment]
I don't really understand the question.

**Comment by maria-anik** [comment]
Hi!

I need to intercept the click event on the link and trigger a click on the arrow.
I try to control submenu switching, but I get an error.

function openPanel returns an error. 
Is the problem in the argument passed or not?
my code
https://prnt.sc/qrtlr9
my errors
https://prnt.sc/qrtm2k
my menu 
https://prnt.sc/qrtor1
