### ISSUE TITLE
not working with bootstrap4

### ISSUE THREAD

**Issue by j0101s** [FrDH/mmenu-js#1095]
Bootstrap 4 modal does not work properly with mmenu-js. It pops up then all stops. Screen turns into grey and there is nothing I can click and escape. All I have to do is reload the page.

I think there might be more conflicting problems between mmenu-js and bootstrap4. You need check it out thoroughly.

**Comment by FrDH** [comment]
Is there an online example I could have a look at?

**Comment by j0101s** [comment]
Here it is. Click "Run" to see the result and then click "Open modal" in blue button in result area.

https://www.w3schools.com/code/tryit.asp?filename=GA63PR13BZ1G

**Comment by FrDH** [comment]
Try moving the modal to outside of the "page" (`<div id="page">`) and specify `"#page"` for the offCanvas.page.selector config option.

````js
new Mmenu("#my-menu", {
   // options
}, {
   // config
   offCanvas: {
      page: {
         selector: "#page"
      }
   }
});
````

https://www.w3schools.com/code/tryit.asp?filename=GA8XR1YW77W3

**Comment by j0101s** [comment]
It works well.
