### ISSUE TITLE
customElements is not defined mburger

### ISSUE THREAD

**Issue by davirs** [FrDH/mmenu-js#1097]
Guys, I have this issue only at edge or IE. How Can I solve this problem?

![image](https://user-images.githubusercontent.com/4355062/70926789-78680200-200c-11ea-8f69-e7b1259a5127.png)

![image](https://user-images.githubusercontent.com/4355062/70926635-38088400-200c-11ea-99c0-695201ca9d5b.png)

**Comment by lkraav** [comment]
See https://webcomponentsjs.org you need polyfills.

**Comment by FrDH** [comment]
IF you need support for IE or edge, you could also use the CSS version:
https://mmenujs.com/mburger/tutorial-css.html

**Comment by lkraav** [comment]
Polyfills correct URL is https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs
