### ISSUE TITLE
unbind

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/mmenu-js#1098]
Fred
I see and use bind to call a function on close.

   var api = $("#my-menu").data( "mmenu" );
       api.bind( "close:finish", function() {
          console.log( "Finished closing panel: ");
       });

yet i  can not seem to get it to unbind or be replaced. 
looked everywhere and could not find a solution. 
please advice.

thanks
bill a

**Comment by FrDH** [comment]
There is no unbind method, but I guess you could add a condition to your function. Something like this:
````js
var gogogo = true;
var api = $("#my-menu").data( "mmenu" );
api.bind( "close:finish", function() {
   if (gogogo) {
      console.log( "Finished closing panel: ");
   }
   gogogo = false;
});
````

**Comment by pigsinspace** [comment]
Thanks Fred
will try that
