### ISSUE TITLE
if there is submenu, replace anchor tag with span tag

### ISSUE THREAD

**Issue by Egretta** [FrDH/mmenu-js#1099]
my menu

```
<ul id="main-menu">
<li><a href="https://kenovoeesti.ee/en/">Home</a></li>
<li><a href="https://kenovoeesti.ee/about-us/">About us</a></li>
<li><a href="https://kenovoeesti.ee/products/">Products</a>
<ul class="dropdown-menu">
<li><a href="https://kenovoeesti.ee/products/?c=01-hooks">Hooks</a></li>
<li><a href="https://kenovoeesti.ee/products/?c=02-tracks">Tracks</a></l>
...

```
with the older - version 7, this script below worked very well, it changed `<li><a href="https://kenovoeesti.ee/products/">Products</a>` to `<li><span href="https://kenovoeesti.ee/products/">Products</span>` if there is submenu.

```
if($(window).width() <= 939){
     $('#main-menu li:has(.dropdown-menu) > a').replaceWith(function() {
return '<span>' + $(this).text() + '</span>'
 });
}
```

i can't figure out, why it is not working with v.8? please check this site [https://kenovoeesti.ee/contact/](url) with developer tool.

**Comment by FrDH** [comment]
This is jQuery, has nothing to do with the mmenu plugin.

**Comment by Egretta** [comment]
it turns out that code still changes  `<li><a href="https://kenovoeesti.ee/products/">Products</a>` to 
`<li><span href="https://kenovoeesti.ee/products/">Products</span>` , but in mobile menu, the entire 'product' item doesn't merge - item text and number next to it, stay separately. in ver. 7 it merged. 
is that still not related to plugin?
