### ISSUE TITLE
sticky navbar jumpy on Safari (Desktop & iOS)

### ISSUE THREAD

**Issue by kaspar-allenbach** [FrDH/mmenu-js#1101]
I setup mmenu-js just like in the tutorial also with the mhead-js plugin.

Now the menu bar  flickers and jumps right from the start. I fleshed out my code until the bare-bones and it seems to be mmenu-js. Because if I remove the firing of the mmenu-js it is all fine.

That's just the standard code. there is nothing to it.

I wanted to recreate it in codepen. but the new `mmenu-js` is not in cdnjs

**html**

```
<body {{attr(pageAtrributes)}}>
    <div id="my-page">
        <div id="my-header">
            <nav id="my-menu">
                <ul>
                    {% include '_atoms/navList' %}
                </ul>
            </nav>

            <a href="#my-menu">Open the menu</a>

        </div>
        <div class="content" id="my-content">
            {% block content %}{# all the content #}{% endblock %}
        </div>
    </div>
    {% include '_incl/docScripts' %}
    {% include '_atoms/googleBodyScripts' %}
</body>
```
**css**
```
#my-header {
  position: sticky;
  top: 0;
  line-height: 44px;
  text-align: center;
  background: red;
  z-index: 100;
}
.hamburger {
  position: absolute;
  top: 0;
  left: 0;
}
```

**js**

```
document.addEventListener(
  "DOMContentLoaded", () => {
    new Mmenu("#my-menu");
  }
);
document.addEventListener(
  "DOMContentLoaded", () => {
      new Mhead( "#my-header", {
          scroll: {
              pin: 100
          }
      });
  }
);
```

Firefox: 
![Dec-30-2019 19-38-20](https://user-images.githubusercontent.com/762213/71595595-91100600-2b3c-11ea-8c61-a9d7a81c68bb.gif)

Safari:

![Dec-30-2019 19-40-102](https://user-images.githubusercontent.com/762213/71595593-91100600-2b3c-11ea-9f40-5ec25fed8691.gif)

**Comment by FrDH** [comment]
Is there an online example I could have a look at? Did you test it on an actuall mobile device, or just using the devtools?

**Comment by kaspar-allenbach** [comment]
I've abandoned the plugin. I've spent hours figuring out what intereferes with it. I've implemented mmenu quite a few times and never had this. I just couldn't get behind what's the problem.
