### ISSUE TITLE
IE10: The property "mmParent" of an undefined or null reference cannot be retrieved

### ISSUE THREAD

**Issue by magic-77** [FrDH/mmenu-js#1102]
Hi,
even if using all Polyfills the compiled skript fails here at Window 7, IE 10

```
if(e.dataset.mmParent?n=m(this.node.pnls,e.dataset.mmParent)[0]:(t=e.mmParent)&&(n=t.closest(".mm-panel")),!t||!t.matches(".mm-listitem_vertical"))
```

**Comment by FrDH** [comment]
I'll see if this can be fixed, but IE10 is not that high on the priority list for support. If you absolutely need it to work, you might want to consider using the legacy (jQuery) version of mmenu:
https://github.com/FrDH/mmenu-js/tree/legacy

**Comment by FrDH** [comment]
Please give version 8.4.6 a try.

**Comment by magic-77** [comment]
Hi @FrDH many thanks for the Fix. I'm testing it and give you Feedback

**Comment by magic-77** [comment]
Hi @FrDH , many thanks for the Fix. It works. Good Work!
