### ISSUE TITLE
IE Compatibility: Compiled Script uses "let"

### ISSUE THREAD

**Issue by magic-77** [FrDH/mmenu-js#1103]
Hi,
i can only point to the place at the compiled script.
Seems that some part of code isn't transpilled. This breaks mmenu-js

```
let a=new S(s,e,t),o=je(a.node.menu);
```

**Comment by FrDH** [comment]
Thank you for reporting the issue, I'll fix it shortly.

**Comment by FrDH** [comment]
Please give version 8.4.6 a try.

**Comment by magic-77** [comment]
Hi @FrDH many thanks for the Fix. I'm testing it and give you Feedback

**Comment by magic-77** [comment]
Hi @FrDH yes it works now. Many thanks!
