### ISSUE TITLE
Sticky navbar with CSS transition issue

### ISSUE THREAD

**Issue by sjaakbanaan** [FrDH/mmenu-js#1106]
I'm currently using the mmenu WP plugin in a Bootstrap site where the navbar has the class 'sticky-top'  and I'm also adding a 'transition: all .2s ease-out;' for some animation fx when scrolling. But the navbar gets really jumpy on menu open/close with this CSS transition on it. Removing this fixes it, but I rather keep the smooth CSS transition. Any tips? Thanks.
PS. Let me know if you'd like to see an example, the site is currently in dev so no public URL.

**Comment by FrDH** [comment]
An online example would help, preferrably reduced to the conflicting elements.
