### ISSUE TITLE
Crashing iOS browser

### ISSUE THREAD

**Issue by trentpattern** [FrDH/mmenu-js#1107]
I just inherited this site to maintain www.apo.co.nz and the menu works fine except on iOS iPhones where opening the menu causes the tab to crash.

This behavior is the same on safari and chrome on the iPhone.

I think it might be to do with the amount of CSS Transforms, but haven't been able to resolve it by modifying the style sheets.

Any help would be appreciated.

**Comment by FrDH** [comment]
I haven't heard about browsers crashing due to too many transforms before.
You could try to upgrade to a later version of the plugin and see if that helps (you're currently using 5.6.4, the latest jQuery version is 7.3.3, you can find it here: https://github.com/FrDH/mmenu-js/tree/legacy)
