### ISSUE TITLE
Width of menu too big in Chromium-based browsers

### ISSUE THREAD

**Issue by dpfahlbusch** [FrDH/mmenu-js#1108]
Hey,
there is a strange behavior of mmenu in chromium-based browsers:
I set up the plugin like it is described on the webpage.
In Firefox everything works fine, but in chrome-based browsers, the width of the off-canvas menu gets  too big.

Not quite sure, but maybe the webkit-transform causes some problems

Version i'm using: 8.4.6

**Comment by FrDH** [comment]
Does the sollution in this issue help?
https://github.com/FrDH/mmenu-js/issues/1062

**Comment by dpfahlbusch** [comment]
Awesome, solved my problem!

Ty for the plugin @FrDH !
