### ISSUE TITLE
mmenu.polyfills.js removed in 8.4.5 ?

### ISSUE THREAD

**Issue by yangkennyk** [FrDH/mmenu-js#1110]
was the combined polyfills removed on purpose in 8.4.5?

I was referencing it before. Is there a recommended way to reference it now or do I need to run a gulp task?

**Comment by FrDH** [comment]
I don't know why, must have been accidentally.
For now, you can run `gulp polyfill` in the commandline, or manually copy/paste the .js files in the `src/polyfills` directory into a new .js file.

**Comment by FrDH** [comment]
They're back in 8.4.7 :)
Thank you for bringing it to my attention.
