### ISSUE TITLE
Expand a single submenu below its parent item not working

### ISSUE THREAD

**Issue by whitedevils** [FrDH/mmenu-js#1113]
I want to have a submenu already expanded in my mmenu, i add class "vertical" to `<li>` parent but the submenu is not opened. What i'm doing wrong?
Thanks

[default.txt](https://github.com/FrDH/mmenu-js/files/4215194/default.txt)

**Comment by FrDH** [comment]
I had a look at the file, the classname to make a submenu expand below its parent is `Vertical` (with a capital "V").
If you want it to be expanded by default, add the class "Selected" to it or one of its descendants LIs.
Hope this helps.
