### ISSUE TITLE
Chrome, Opera & Firefox display issues

### ISSUE THREAD

**Issue by lansd** [FrDH/mmenu-js#1117]
I absolutely to hate to ask for support as I'd prefer to solve all integration issues myself. I've done some due diligence on these problems prior to making this post. For two weeks I've had mmenu-js integrated and working well on Chrome mobile. But then I started to test on Firefox and Opera....

1) This may be a known issue but the menu displayed via the www.mmenujs.com web site will not scroll vertically on Opera. And the counters do not show up. This is on a Nexus5 Android phone + the newest Opera.

1b) Note: on a desktop browser the default top "menu" text is center aligned. However, on all 3 mobile browsers the "menu" text is right aligned. This, to me, seems to related to the chevrons of the sub-menus disappearing after one second on my phone. 

2) The remainder of the issues can be checked on https://www.okino.com.

2a) On Chrome mobile, the counters and chevrons disappear after one second once the "menu" title appears at the top of the menu. Scrolling works okay.

2b) On Firefox mobile, vertically scrolling does not work, no counters and no chevrons for the sub-menu entries.

2c) On Opera, vertical scrolling works for a few seconds then it locks up and no counters or chevrons.

I'm all ears on suggestions as how to approach these issues beyond what I've been testing and changing so far. Thanks!

**Comment by FrDH** [comment]
I tried, but could not reproduce any of the issues on an iPhone (safari, chrome and ff).
As all issues are touch-device related, please try changing the viewport meta-tag:
````html
<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />
````
The issue mostly is that the viewport should not be scalable.
If you find anything that helps solve your issues, please let me know.

Hope this helps.

**Comment by lansd** [comment]
Thanks for your swift follow up.

Prior to seeing your post I spent a few hours using a divide & conquer method to try and find out what, if anything, may have been the issue. I stumbled across the issue long before I whittled the entire site down to this single test page:

http://www.okino.com/test.htm

Basically, on that page, the 640 pixel image causes the Mmenu to lock up (not scroll vertically) on Firefox. And it'll cause the menu to be rendered too wide, thus offsetting the "Menu" text and chevrons.

For the "viewport" statement, a while back I didn't want to prevent viewport scaling from our website visitors (for a few pages which may need scaling) so I took out the no-scalable and max-scale keywords. 

Opera still has some issues. I took note that it has the "Force enable zoom" UI option enabled by default, whereas with Firefox and Chrome I had to enable that manually.

**Comment by vincequeiroz** [comment]
I have the same issue in the [demo](https://mmenujs.com/demo/index.html).

When I navigate in menu, the width of header is broken.
![image](https://user-images.githubusercontent.com/651325/75994327-917ca280-5ed9-11ea-8d51-b886950920d9.png)

If I close and open again, the with of header is fixed.
![image](https://user-images.githubusercontent.com/651325/75994508-d9032e80-5ed9-11ea-9fe1-1468c903a0f0.png)

**Comment by FrDH** [comment]
ill check and update the meta tag on the demos.
Thanks for bringing it to my attention.

**Comment by FrDH** [comment]
Anorher approach that appears to be working, is to set the overflow on the HTML to "hidden" (and some additional css to re-enable scrolling in general):
````css
html, body {
	width: 100%;
	height: 100%
}
html {
	overflow: hidden;
}
body {
	overflow: auto;
}
````
