### ISSUE TITLE
Problem with Bootstrap wrapper

### ISSUE THREAD

**Issue by ArniPL** [FrDH/mmenu-js#1120]
Hi,

We've encountered a bug related to Bootstrap wrapper. Then, we've noticed that it also occurs on your demo page here: https://mmenujs.com/demo/index.html?demo=bootstrap-navbar

Basically, after clicking to open the submenu, entire page can now be scrolled in both axes, and mmenu alignment is broken (container is wider than visible part). So after going back to base menu level, you can't open the submenu again. See the video below.

Do you know what could be causing this? Thanks!

![Demo](https://user-images.githubusercontent.com/3541132/75686015-d6b39100-5c9b-11ea-93f6-6c16ec20de52.gif)

**Comment by Scorpovi4** [comment]
Seems like problem with viewport
Try to use this in your head section:  

<meta name="viewport" content="width=device-width minimum-scale=1.0 maximum-scale=1.0 user-scalable=no" />

**Comment by ArniPL** [comment]
@Scorpovi4 Thank you. Yes, this is a usable workaround. We're gonna use this for now. But what if the developer intends webpage to be scalable? I think the bug exists regardless.

**Comment by Scorpovi4** [comment]
@ArniPL Another approach - another plugin...
