### ISSUE TITLE
Link to the TileView extension still exists in mmenu.scss

### ISSUE THREAD

**Issue by graycrow** [FrDH/mmenu-js#1124]
I'm using a TileView extension and would prefer it to stay in the codebase, but since it's removed let's remove it completely - `mmenu.scss` still tries to import `tileview.scss` and my build fails.

https://github.com/FrDH/mmenu-js/blob/68d6f1b37180f0e6a59afb37051bc6520cbfd898/src/mmenu.scss#L56

**Comment by graycrow** [comment]
Also there are some remains of tileview in `_includes.scss`, starting from the following line:
https://github.com/FrDH/mmenu-js/blob/68d6f1b37180f0e6a59afb37051bc6520cbfd898/src/_includes.scss#L95

**Comment by FrDH** [comment]
Thanks.
That's odd, the first should have been removed. The second is an automatically generated file, will be removed also.

**Comment by FrDH** [comment]
removed it in 8.5.1
