### ISSUE TITLE
Close current mmenu panel or close panel by id

### ISSUE THREAD

**Issue by Scorpovi4** [FrDH/mmenu-js#1125]
I need to cutomize own back button to close panel if opened panel and close menu if  panel is menu.

Close all pannels solutions below but I want to close only current opened panel because my menu has 3 levels.

```
api.bind("openPanel:start", panel => {
        $(".js-mmenu-back").unbind("click");
        $(".js-mmenu-back").bind("click", function() {
            console.log("close panels");
            api.closeAllPanels();
        });
    });

    api.bind("closeAllPanels:after", panel => {
        $(".js-mmenu-back").unbind("click");
        $(".js-mmenu-back").bind("click", function() {
            console.log("close");
            api.close();
        });
    });
```

**Comment by FrDH** [comment]
With the `slidingSubmenus` option set to `true` (the default value), you can not really close a panel, you can only open its parent.
If the structure of your menu is in a logical order, you might get away with something like this:
````js
var $menu = $("#my-menu").mmenu();
$(".js-menu-back").bind("click", function() {
    var $parent = $menu.find(".mm-panel_opened-parent");
    if ($parent.length) {
        api.openPanel( $parent.last()[0] );
    } else {
        api.close();
    }
});
````

Haven't tried it, but something like this should work.

**Comment by Scorpovi4** [comment]
It works with a little changes, thanks.
