### ISSUE TITLE
Search not working properly when not using sliding submenus

### ISSUE THREAD

**Issue by diogopaludo** [FrDH/mmenu-js#1127]
Recently I've been testing the menu and noticed that the search option works fine with the option of sliding submenus activated, but with the submenus in a "tree visualization" it does not filter for the submenus. At first I thought the problem happened with links, but searching for "subfolders" also does not bring the desired results.

Using the playground this problem can be simulated.

![Capturar](https://user-images.githubusercontent.com/19171267/76643530-f5cfdf80-6533-11ea-9873-4575a1c2b77f.JPG)

**Comment by FrDH** [comment]
Thanks, I'll look into it.

**Comment by FrDH** [comment]
Should be fixed in version 8.5.3

**Comment by diogopaludo** [comment]
Just tested the new version and it works perfectly. Thank you!
