### ISSUE TITLE
No dividing line below submenu Title (Firefox mobile browser)

### ISSUE THREAD

**Issue by sanmiguel2019** [FrDH/mmenu-js#1128]
I have a strange problem. Everything is fine in my desktop, however there is a problem in Firefox mobile browser.

I open menu (screenshot 1) and everything looks good good. Then I open a submenu and there is no line below submenu title (screenshot 2).

When I return to the main menu, one part of the line below the main menu title is darker (screenshot 3).

I tried to increase z-undex inside of:

```
.mm-spn.mm-spn--navbar ul:before {
...
z-index:99999999;
...
}
```

Now there is a line below submenu title in Firefox mobile but when I return to main menu, one part of the line is darker in all browsers now, even in my desktop.

I spent a long time playing with z-indexes but no success. Any ideas?

![mmenu2](https://user-images.githubusercontent.com/54183931/76659477-74497300-656e-11ea-9898-07be88436507.png)

**Comment by FrDH** [comment]
wrong repository, but that's OK :)
https://github.com/FrDH/mmenu-light

The mmenu light plugin is a bit limited in its possibilities due to the minimum amount of HTML being altered. I'll see if I can make some improvements.
Thank you for reporting the issue.
