### ISSUE TITLE
href="# mm-1" url is created, which has a negative effect on seo

### ISSUE THREAD

**Issue by enderimen** [FrDH/mmenu-js#1131]
@FrDH, These created urls (href = "# mm-1") cause traffic on the site. This is seen as a bad experience for SEO.

`<a class="mm-btn mm-btn_next mm-listitem__btn mm-listitem__text" href="#mm-0">
      About us
      <span class="mm-sronly">Open submenu</span>
</a>`

I got the code sample above from your page.

is there a solution for this?

**Comment by FrDH** [comment]
These URLs are craeted with JS and their behavior is handled with JS, how does that cause traffic (other then maybe bots)?

**Comment by andreamoro** [comment]
The worse it can happen is an internal link, for which I don't expect huge traffic and close-to-0 SEO impact. 
Interested to understand where you got the example, which you can still decorate with a rel="nofollow" if the OP has concerns.
