### ISSUE TITLE
LazySubmenus second and subsequent levels not working

### ISSUE THREAD

**Issue by marcoDallas** [FrDH/mmenu-js#1132]
mmenu version 8.5.3.
If LazySubmenus  is set to true, the submenus are not correctly shown. When the first level submenu is opened, the subsequent ones are always visible.

See this fiddle for an example, open "About us" to see the bug https://jsfiddle.net/fromfree/d1obLzwp/8/

The configuration:
```
new Mmenu("#menu", {
  "extensions": [
    "pagedim-black"
  ],
  "counters": true,
  searchfield: {
    placeholder: 'search',
    noResults: 'no results'
  },
  navbar: {
    titleLink: "anchor"
  },
  "navbars": [
    {
    "position": "top",
    "content": [
      "searchfield"
    ]
    },
    {
    "position": "bottom",
    content: [
      "<p><b>footer</b></p>"
    ]
    }
  ],
    lazySubmenus: {
    load: true
  }
}, {});
```

**Comment by FrDH** [comment]
Hi,  thank you for reporting the issue.
I'll have to do some investigation.

**Comment by FrDH** [comment]
Should be fixed, but the changes might need some better testing :)
Could you give 8.5.4 a try?

**Comment by marcoDallas** [comment]
Thank you for the new version!
In 8.5.4 is still a bug in third and subsequent submenus:
![immagine](https://user-images.githubusercontent.com/4239183/80030438-7a752c80-84e8-11ea-9ee7-3863785cfdeb.png)

updated fiddle:
https://jsfiddle.net/fromfree/d1obLzwp/9/

**Comment by FrDH** [comment]
Your fiddle has bad HTML, the submenu (<ul>) is not inside the parent (<li>).
Fix that and it works as intended.

**Comment by marcoDallas** [comment]
Sorry, my bad. I can confirm that version 8.5.4 works, thank you!

**Comment by pvernekar-cci** [comment]
Is this resolved? After applying lazySubmenus to true, it only hides the 3rd level sub menus. 2nd Level is still visible.
