### ISSUE TITLE
Class inheritance/overwriting?

### ISSUE THREAD

**Issue by andreamoro** [FrDH/mmenu-js#1134]
@FrDH great work overall. Thanks for that.

I've been implementing the 3.0 version and I notice that as opposed to the 1.0.9 I was using till a moment ago.

As a general feedback, that would be nice if the script could inherit from previously attached class if any.

As a problem, I unsuccessfully tried to overwrite the color of the title in the menu with
```
    --mm-spn-title-color: #000;
    --mm-spn--navbar-color: #000;
```
I'm not sure why this is not working considering that a `--mm-spn-title-text-transform: uppercase;` works fine.
Any idea?

**Comment by FrDH** [comment]
Hi,

I assume you're talking about the mmenu-light plugin? (it has its own repo here: https://github.com/FrDH/mmenu-light)

Are  you sure `--mm-spn-title-text-transform: uppercase` actully does anything? That variable isn't used at all...
`--mm-spn-title-color` and `--mm-spn--navbar-color` are also not (any more?) used by the plugin.

Anyway, if you want to change the colors for the navbar, try this:
````css
.mm:after {
    opacity: 1;
    color: blue;
}
````
Hope this helps.

**Comment by andreamoro** [comment]
Hi,
Yes I was talking about the light version.

Apologies, you are right in saying the variable does anything. I was having the local override still on in an attempt to find out the class to manage.
That does not do anything.

I'll try the above.

Andrea

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
Could very well be the CSS needs more specificity to actually do anything, but without an online example I can only guess to what could help you.
