### ISSUE TITLE
Deprecated: contextual_help is deprecated since version 3.3.0!

### ISSUE THREAD

**Issue by wavehamza** [FrDH/mmenu-js#1135]
Deprecated: contextual_help is deprecated since version 3.3.0! Use get_current_screen()->add_help_tab(), get_current_screen()->remove_help_tab() instead. in /home/urbanmobility/public_html/wp-includes/functions.php on line 5088

The Backoffice is showing an error after an update of the WordPress Core to Version 5.4.

Best regards.

**Comment by FrDH** [comment]
should be fixed in the last update
