### ISSUE TITLE
The problem of multiple menus

### ISSUE THREAD

**Issue by 438833** [FrDH/mmenu-js#1138]
When creating two or more menus, there is a problem with the blocker node.

https://jsfiddle.net/438833/j84gdy7m/

When accessing the second menu, the classes mm-wrapper_opened mm-wrapper_blocking mm-wrapper_background are not added to the body.

This is due to the fact that the first menu closes after the second is initialized.

Is there a fix way?

**Comment by FrDH** [comment]
Hi, thanks for reporting the issue.
This is only an issue when you're opening the second menu from inside the first menu, so it probably is a timing issue, I'd have to look into that.
