### ISSUE TITLE
How to hook an event after mmenu is fully initialized?

### ISSUE THREAD

**Issue by CribAd** [FrDH/mmenu-js#1139]
I need to copy some HTML to a mmenu-panel once after it is fully initialized.

Tried the hook "setPage:after" from the offcanvas add-on, but that fires too early.
Other hooks fire every open/close, I need it just once.

**Comment by FrDH** [comment]
you could just do it after invoking the plugin:
````js
new Mmenu("#my-menu");
document.querySelector("#my-panel").append( newContent );
````
Would that not work?
