### ISSUE TITLE
backButton closing the page after closing the menu 

### ISSUE THREAD

**Issue by usernein** [FrDH/mmenu-js#1140]
I'm using the add-on backButton with backButton.close == true
It closes normally the submenus, but when i try to close the menu it closes then go back to the last opened page

[Screen record](http://usernein.souunick.com/mmenujs-issue-back-button.mp4)

OS: Android 6.0.1
Browser: Via Browser (uses Android WebView), but it also happens with Chrome Android 
WebView version: 80.0.3987.162

mmenu-js version: from the commit [f316ed7](https://github.com/FrDH/mmenu-js/blob/f316ed7541c875cd09d50722ee1cffdd5eb11055/dist/mmenu.js)

**Comment by FrDH** [comment]
Hi,
That's odd, does this also occur in other browsers?

**Comment by usernein** [comment]
I asked some friends for testing and they said it's working on:
- [Firefox 68.7.0](https://t.me/VegaData/609499)
- Bromite (Chromium-based) v81

**Comment by gaaytrimaa** [comment]
@usernein has pointed the correct thing. The back button works properly on submenus but when closing the main **menu**, the page goes back to the previous page after closing the main menu.
This bug if sorted out will make this menu ideal to implement in single page applications.

**Comment by gaaytrimaa** [comment]
@FrDH please resolve this bug as it is creating problem in making single page applications. After closing the **MAIN** **menu** the webpage goes back to the previous page. I have used this menu in one of my production apps so please help me. I would be very thankful to you.
