### ISSUE TITLE
How to toggle menu from different component or js script event ?

### ISSUE THREAD

**Issue by sushant-ht** [FrDH/mmenu-js#1142]
in demo i see that you have given href to activate slideout menu. and when i click on page anywhere he mneu slides-in. if had to control slide in and slide out event from different event like if page is loaded or not than i cna slide out menu and if error automatically slides in. user dont have to click anywhere.

is there option for this ?

**Comment by FrDH** [comment]
I'm not sure I understand the question, but if you manually want to open and close the menu, try using the [API](https://mmenujs.com/docs/core/api.html), like this:
````js
// Fire the plugin
const menu = new Mmenu( "#my-menu" );

// Get the API
const api = menu.API;

// Open the menu
api.open();

// Close the menu
api.close();
````

Hope this helps.
