### ISSUE TITLE
Currently selected menu item should not lose emphasis color when hovered

### ISSUE THREAD

**Issue by devhitech** [FrDH/mmenu-js#1143]
Having the following set for the mmenu-js:
```
        setSelected: {
            current: "detect",
            hover: true,
            parent: true
        },
```
the currently selected menu item (`current: "detect"`) correctly gets the `--mm-color-background-emphasis` color, and the hovered menu items (`hover: true`) also correctly get the `--mm-color-background-emphasis` color.

However when the 2 actions above are combined, thus when hovering over a currently selected menu item, the `emphasis` color is lost. In this case the `emphasis` color should remain visible.

**Comment by FrDH** [comment]
This is by design actually :)

**Comment by devhitech** [comment]
What's the reasoning behind it though?

It seems counter intuitive that the item which is both selected and hovered loses the emphasis color.

Take for example the selected menu item from this Google page: https://developers.google.com/web/fundamentals/accessibility

While hovering the selected menu item (Accessibility), it keeps the selected emphasis color, same goes for the language drop-down in the top-right corner. Most UIs seem to follow this pattern.

**Comment by FrDH** [comment]
Ok, I might have misunderstood the question; If the item is both selected and hovered, it should be emphasized. I'll have a look at it later on. Thank you for bringing it to my attention.

**Comment by FrDH** [comment]
Please give version 8.5.6 a try, whould be fixed.

**Comment by devhitech** [comment]
Works great! Thank you for the quick fix!
