### ISSUE TITLE
WP plugin: 404's on mmenu options page

### ISSUE THREAD

**Issue by sjaakbanaan** [FrDH/mmenu-js#1144]
Just downloaded v2.9.1 en the backend was giving four 404 errors on js files. An example path of one of the files:
`https://www.website.com/wp-content/plugins/mmenu/mmenu/jquery.mmenu.all.css?ver=5.4.1`
So i guess it's a relative path issue? I fixed it for now by uploading the mmenu folder again inside the mmenu folder so the path: `wp-content/plugins/mmenu/mmenu/` actually exists and I don't have to edit any files.

**Comment by FrDH** [comment]
Thank you for letting me know,
That's an odd issue, I'll have a look at it shortly.

**Comment by sjaakbanaan** [comment]
Thanks for the reply @FrDH , I probably did something wrong when unpacking because I see that 'mmenu' folder in the zip file as well. It felt like a bug because the `/mmenu/mmenu/` folder structure seemed weird but I should've double checked. Sorry for this.
