### ISSUE TITLE
How to include polyfills for IE11?

### ISSUE THREAD

**Issue by tanc** [FrDH/mmenu-js#1146]
There seems to be some confusing information around polyfills for IE11 and whether they are included or not. The last time I checked in an earlier version of 8.x.x there was a polyfills.js file (or similarly named) in the dist directory. Currently that doesn't seem to be the case in version 8.5.11.

I've also read that you can compile the polyfills with a gulp command. There is also some information in the README.md that says to use external polyfills from polyfill.io.

Can you explain exactly how compatibility with IE11 is supposed to work? And ideally update the documentation on the mmenu site to include steps if it is more complicated than including a js file? Thanks!

**Comment by FrDH** [comment]
The polyfills file should be present in the dist directory. If it isn’t, something probably went wrong during the compilation.
I’ll fix it shortly.

**Comment by FrDH** [comment]
should be present in the new release.

**Comment by spoink** [comment]
I've downloaded the latest version (8.5.12) and still don't see the polyfill file in the dist folder although I do see it on the master branch.

**Comment by FrDH** [comment]
That’s odd,
Where did you download it from?

**Comment by tanc** [comment]
I don't see the `mmenu.polyfills.js` file either when I download the latest release from the releases page on github

**Comment by spoink** [comment]
https://github.com/FrDH/mmenu-js/archive/v8.5.12.zip

**Comment by FrDH** [comment]
Weird, sorry about that.
it's present in 8.5.13

**Comment by tanc** [comment]
Confirmed that the `mmenu.polyfills.js` file is included in the `dist` folder of the `8.5.13` release and when included on a page it allows mmenu to work on IE11 without errors. Thanks!
