### ISSUE TITLE
Hide or Disable Default Navbar Menu

### ISSUE THREAD

**Issue by BigSamu** [FrDH/mmenu-js#1149]
Hi all,

One short question. I am using the Navbars Add-On for including a customized Navbar for a web app I am developing. However, when using that Add-on, I don't know how to hide or disable the default navbar included on the Core Configuration **without losing the headings to go back when accessing to sub-menus**. 

In other words, if I use the `add: false` property and I have dropdowns menus for an item in specific when clicking on that item, I would not be able to get back, because the Default Navbar will be hidden due too the `add: false` property, which indeed has the back arrow for going back the main menu. 

Did I make myself clear? Any suggestions to work around this issue??

Regards,

Samuel

**Comment by FrDH** [comment]
Hi, 
I don't think I understand. You want to hide the default navbar, but not loose the default navbar?
Is there an online example I could have a look at?
