### ISSUE TITLE
Open directly to submenu from outside mmenu

### ISSUE THREAD

**Issue by Mulegoat** [FrDH/mmenu-js#1150]
Hi there,

I'm have an off-canvas menu with a few subpanels. The off-canvas menu is initialized the usual way by clicking a link with href="#mymenu"

There are some parts of my site where i wish to fire the plugin to open to a specific subpanel. I've seen that you can do this using the Selected Class option but I need more contorl than this and need to deeplink to subpanels without creating multiple menus if possible. 

Is there an easy way to do this? 

My current code:

`         var mymenu = $("#menu-location-primary_navigation");
          
          mymenu.mmenu({
             // options
              extensions  : [ "effect-slide-menu", "pagedim-black", "pageshadow"],
              counters  : true,
              offCanvas: {
              position: "right",
              zposition: "front"
            },
            onClick: {
              preventDefault: null,
              close: true
            },
            classNames: {
              fixedElements: {
                fixed: "fixed-header"
              }
            },
            scrollBugFix: {
              fix: true
            },
            navbars: [
              {
                position  : 'top',
                content   : [
                  'prev',
                  'title', 
                  'close'
                ]
              }
            ]

          }); 
`

**Comment by FrDH** [comment]
Using the [API](https://www.mmenujs.com/docs/core/api.html), you can open a panel before opening the menu. For example:

````js
const menu = new Mmenu( "#my-menu" );
const api = menu.API;

document
    .querySelector("#some-button")
    .addEventListener("click", e => {
        const panel = document.querySelector( "#my-panel" );
        api.openPanel( panel );
        api.open();
    });
````

Hope this helps.

**Comment by Mulegoat** [comment]
Many thanks, worked perfectly!
