### ISSUE TITLE
Bootstrap wrappers - drop-down

### ISSUE THREAD

**Issue by fklee** [FrDH/mmenu-js#1151]
I was wondering why my dropdown-item does not receive active style in mmenu ? 

As I can see in https://github.com/FrDH/mmenu-js/blob/master/dist/wrappers/bootstrap/mmenu.bootstrap.js Line 80. I can't see the function add active to one of the elements of dropdown menu ? 
It is normal as dropdown couldn't be active.

Thanks in advance for your answer.
FKL

**Comment by FrDH** [comment]
I don't think I understand the issue, is there an online example that could clearify the problem?

**Comment by fklee** [comment]
Sorry,
So to reproduce it, create bootstrap menu with dropdown element and as the active page is one of the dropdown element (element is noted as active in bootstrap "a") In mmenu, the element is not catched as active.

I add two printscreen of code, as it could help you to understand.
- https://snipboard.io/J1DlfY.jpg  Dropdown-menu content (with active item)
- https://snipboard.io/cMu9gy.jpg  Mmenu content (with not selected)

**Comment by FrDH** [comment]
Ok I understand, the script needs to transfer the "active" class from the `<a>` to the `<li>`.
I'll see if I can fix this shortly.

**Comment by fklee** [comment]
Hi, have you planned a date to correct this bug for a new release ? Thanks

**Comment by FrDH** [comment]
I believe this shoudl already work:
https://github.com/FrDH/mmenu-js/blob/master/src/wrappers/bootstrap/mmenu.bootstrap.ts#L119
