### ISSUE TITLE
Menu level arrow click redirecting the page in chrome responsive dev tool and android devices

### ISSUE THREAD

**Issue by vidit-anjaria** [FrDH/mmenu-js#1153]
I have checked on 2 instances on my local and I found that when we resize the window with chrome dev tools without toggling into responsive mode menu is working fine and m able to traverse all the levels. When I tried to open the responsive tool and checking the drawer there, is creating some issue and clicking on the arrow is redirecting to the page instead of taking to the next level drawer.

I am not sure this is due to the core library or due to module.

**Comment by tanc** [comment]
I've tracked the problem down to this line:
```
  <meta name="viewport" content="width=device-width minimum-scale=1.0 maximum-scale=1.0 user-scalable=no" />
```
It would appear that Chrome needs `minimum-scale=1.0` for it to work correctly.

To replicate the issue:

1. Open the `/demo/default.html` page and resize Chrome to 340 wide
2. Toggle open the menu and click through to a depth of 3 (About us > The team) and note that everything works fine
3. Edit line 7 and change it to:
```
  <meta name="viewport" content="width=device-width initial-scale=1.0" />
```
4. Reload the page and again toggle open the menu and try to click through to a depth of 3. Note that after 'About us' you cannot see the arrow next to 'The team' to get to the third level.
5. Open the same page in Firefox and resize to 340 wide. 
6. Toggle open the menu and note that everything works as expected.

I maintain a Drupal module and unfortunately most Drupal themes don't set the `minimum-scale`. It's possible I could work around this in the module by forcing it on but I'm hoping there might be a solution within mmenu.

**Comment by tanc** [comment]
It looks like this was already discussed: #1062 
I think I'll do something similar in the javascript of the Drupal module and dynamically add the `minimum-scale` value to the viewport.

**Comment by FrDH** [comment]
I believe a `minimum-scale` of `1` is sufficient to fix this issue.
