### ISSUE TITLE
Mmenu in Bootstrap 4's dropdown

### ISSUE THREAD

**Issue by nht10** [FrDH/mmenu-js#1155]
Hi, I am trying to make Mmenu work in Bootstrap 4's dropdown. When user click on a Bootstrap 4's dropdown button, it will show a Mmenu instead of a default Bootstrap 4's dropdown.

I tried to combine theme here with Bootstrap Wrapper: [https://codepen.io/nht910/pen/xxZPMwP](https://codepen.io/nht910/pen/xxZPMwP).

But it doesn't work.

Can you guys please help me to archive it? 

Thank you so so much.

**Comment by FrDH** [comment]
I'm not sure I understand what you're trying to do, but the codepen seems incomplete or broken (it just shows an unstyled list).
