### ISSUE TITLE
Potential issue with Turbolinks wrapper for Rails

### ISSUE THREAD

**Issue by javiervg** [FrDH/mmenu-js#1156]
Awesome library, thanks for making it and sharing it. 

It might be an issue with our implementation, but seems to point that the wrapper might not doing things correctly. 

We have Rails 5.2.2, Turbolinks 5.1.1, Webpacker 5.1.1.  Using same HTML, https://mmenujs.com/examples.html

In JS:
function initMenu() {
    new Mmenu("#my-menu", {wrappers: ["turbolinks"]});
}
$(document).on('turbolinks:load', initMenu);

The menu loads perfectly the first time but after visiting a link inside the page the JS on the menu does not work quite well (no console errors).

We have tried loading differently, with npm, with CDN, etc. Loading other JS code seem to load fine. The mmenu-light library works without a problem. 

Thanks in advance for your help and have a wonderful day

**Comment by FrDH** [comment]
I'm not really up tp date with my knowledge of turbolinks, are they still using the events `turbolinks:before-visit` and `turbolinks:load`?

If you can, please create a pull request for the turobolinks wrapper if you find a solution.

**Comment by javiervg** [comment]
Thanks for the response and help. We tried turbolinks:before-visit, turbolinks:load, 'ready', running function directly, with delays, reinitializing it with a variable tag, removing the the whole html nav bar element, etc. And have not been able to get it to work after clicking on a link.

After clicking on a link. without the wrapper, wrappers: ["turbolinks"], the menu is left open, and the JS does not work. With the wrapper, the menu is closed and is able to open once, but does not work after. If you have any ideas maybe around reinitialization, we can give a try, and we will see if we can get something to work. Thanks a lot and have a nice day.
