### ISSUE TITLE
Unable to start scrolling on submenus on version 8.5.13

### ISSUE THREAD

**Issue by systemshock89** [FrDH/mmenu-js#1157]
Hello!

I don't can scroll on submenus in mobile Chrome or desktop Chrome devtools with mobyle mode.

I have the this problem on version 8.5.13.
On the mobile browser Chrome menu does not scroll.
scrollBugFix option to false - does not solve the problem.
Version 8.5.8 also has this problem.

On desktop Chrome if testing on mobyle devtools - only in version 8.5.4 it will normally scroll by the mouse wheel, or by touch.
And it only works if scrollBugFix : false.

**Comment by systemshock89** [comment]
my config:
`document.addEventListener(
    "DOMContentLoaded", () => {
        // Mmenu
        new Mmenu( "#mmenu", {
            // options
            "slidingSubmenus": false,
            "scrollBugFix": {
                "fix": false
            },
            "navbar": false, 
            "extensions": [
                "border-full", 
                "multiline", 
                "pagedim-black", 
            ],
            "navbars": [
                {
                    "position": "top",
                    "content": Array.from(document.querySelector("#mmenu-top-buttons").children)
                },
                {
                    "use": (document.querySelector("#mmenu-socials") ? true : false),
                    "position": "bottom",
                    "content": (document.querySelector("#mmenu-socials") ? Array.from(document.querySelector("#mmenu-socials").children) : null)
                },
            ],
        }, {
            // configuration
            offCanvas: {
                page: {
                    selector: ".page"
                }
            },
            language: "ru"
        });
    }
);`

**Comment by diogopaludo** [comment]
I encountered the same problem. When a submenu takes the whole screen in mobile, the only way to scroll down is by the narrow scroll bar or closing and opening the menu. It seems "touch" does not work on the submenus. Is that the desired behavior? Can I change this in some way not specified in the documentation?

Config:
<script>
new Mmenu(
	document.querySelector('#menu'),
	{
		extensions: [ 'theme-dark','multiline', 'pagedim-black' ],
		sidebar: {
			expanded: '(min-width: 1000px)'
		},
		setSelected: true,
		slidingSubmenus: false,
		searchfield: {
			placeholder: '',
			noResults: ''
		},
		navbar: { 
			add: false 
		},
		navbars: [
			{
				content: [
					'<a></a>', 
					'<a></a>',
					'close'
				]
			},
			{
				content: [
					'searchfield'
				]
			}, {
				type: 'tabs',
				content: [
					'<a></a>',
					'<a></a>'
				]
			}
		]
	}, {
		searchfield : {
			clear: true
		},
		navbars: {
			breadcrumbs: {
				removeFirst	: true
			}
		},
		openingInterval: 0
	}
);
</script>
<style>
	:root {
		--mm-sidebar-expanded-size: 300px;
	}
	.mm-menu {
		--mm-listitem-size: 30px;
		--mm-navbar-size: 30px;
	}
	.mm-navbar_tabs span {
		display: inline-block;
		margin-left: 8px;
	}
	@media (max-width: 450px) {
		.mm-navbar_tabs span {
			display: none;
		}
	}
	.mm-listitem_vertical>.mm-listitem__btn {
		height: auto;
		bottom: auto;
	}
</style>

**Comment by diogopaludo** [comment]
In my case, with my config, I was able to ajust this behavior by adding a custom style:
.mm-panel {
    overscroll-behavior: auto;
}

**Comment by systemshock89** [comment]
> In my case, with my config, I was able to ajust this behavior by adding a custom style:
> .mm-panel {
> overscroll-behavior: auto;
> }

Great! It's work for me too. Thanks!
