### ISSUE TITLE
 mmenu-light tutorial completly wrong

### ISSUE THREAD

**Issue by blotfi** [FrDH/mmenu-js#1158]
Thank you for this open source mmenu-light tool

Please reconsider your tutorial
https://mmenujs.com/mmenu-light/tutorial.html
there are many bugs.

do not name "my-menu" or... stick to "menu" because all of your css use them
also do not use const but var
use class= instead of id= in the right parts
take the working example of  mmenu-light-master.zip
mmenu-light-master\demo
which works correctly and put it in the tutorial

This tutorial would be better if it relays on the demo code

**Comment by FrDH** [comment]
Hi,

I'm sorry if you had trouble understanding the tutorial, but where did you read the HTML (and thus js and css) for the tutorial would be compiant to the demo files?

About the "bugs":
- Throughout the entire tutorial, the name "my-menu" is used.
- Why don't you want to use `const`? It is supported as of IE11.
- There is nothing wrong with using an `id` for uniquely identifiable elements.

Hope this helps.

**Comment by javiervg** [comment]
> Please reconsider your
> https://mmenujs.com/mmenu-light/tutorial.html
> 
> it is full of bugs!
> 
> do not name "my-menu" or... stick to "menu" because all of your css use them
> also do not use const but var
> use class= instead of id= in the right parts
> take the working example of mmenu-light-master.zip
> mmenu-light-master\demo
> which works correctly and put it in the tutorial
> 
> Instead of helping me, the tutorial make it worse
> until I discovered that I have to rely only on the demo

@blotfi , you do not need to be such a jerk. I found the documentation on these libraries pretty awesome, and helpful. For an open source project, it is great.

**Comment by blotfi** [comment]
> Hi,
> 
> I'm sorry if you had trouble understanding the tutorial, but where did you read the HTML (and thus js and css) for the tutorial would be compiant to the demo files?
> 
> About the "bugs":
> 
> * Throughout the entire tutorial, the name "my-menu" is used.
> * Why don't you want to use `const`? It is supported as of IE11.
> * There is nothing wrong with using an `id` for uniquely identifiable elements.
> 
> Hope this helps.

thank you for your comments and explanations
I am sorry if I have been so direct.
I didn't figure out it was a project made by only one person
I suggest you to correct the tutorial using only the demo code (which works great) whereas the code in the tutorial doesn't work (on Chrome) and gave multiple errors
best regards

**Comment by blotfi** [comment]
> > Please reconsider your
> > https://mmenujs.com/mmenu-light/tutorial.html
> > it is full of bugs!
> > do not name "my-menu" or... stick to "menu" because all of your css use them
> > also do not use const but var
> > use class= instead of id= in the right parts
> > take the working example of mmenu-light-master.zip
> > mmenu-light-master\demo
> > which works correctly and put it in the tutorial
> > Instead of helping me, the tutorial make it worse
> > until I discovered that I have to rely only on the demo
> 
> @blotfi , you do not need to be such a jerk. I found the documentation on these libraries pretty awesome, and helpful. For an open source project, it is great.

I didn't go through the documentation, I am talking about the tutorial.
Sorry for being so direct
