### ISSUE TITLE
Put the menu inside a custom sliding sidebar

### ISSUE THREAD

**Issue by flanderboy** [FrDH/mmenu-js#1159]
Hello everyone, I need to put the menu inside a my custom sliding sidebar, I try to set offCanvas: false but the menu is hidden. I try to open it after sliding end (mmenu.open();) but do not work.

Thanks
Stefano

**Comment by FrDH** [comment]
If you set `offCanvas` to be `false`, the menu will have `position: absolute;` and `top`, `right`, `bottom`, `left` set to `0`.
Meaning, you must place it in a container that has a fixed height (for example `100%`) and `position: relative`.

Hope this helps.
