### ISSUE TITLE
Conflict with Tawkto script

### ISSUE THREAD

**Issue by boldison** [FrDH/mmenu-js#1161]
We have an issue where the mmenu script seems to be conflicting with a script used for an online chat with Tawk.to (https://www.tawk.to/).

If I hide the mmenu script, the Tawkto widget displays fine but as soon as I load that in again the Tawkto widget displays for a split second and then the content of that widget empties and it is gone leaving an empty iframe.

Same issue across browsers.

Any ideas why this could be happening? Tawkto have naturally said we need to get mmenu to fix the issue.

**Comment by FrDH** [comment]
Could be due to the plugin wrapping the HTML in a single DIV, try [the tutorial](https://www.mmenujs.com/tutorials/off-canvas/) (the part about "the page").
