### ISSUE TITLE
Problems with anchor links

### ISSUE THREAD

**Issue by Dow2nunder** [FrDH/mmenu-js#1162]
The anchor links will only called once. The second call on the same page will do nothing.

It could be tested on following website:

http://hpc-campus.com/

Open menu and select "Our team" -> the url will change, but the menu stay open and the browser will not go to the anchor.

Open menu and select "Contact" -> the new page will  called.

Open menu and select "Our team" -> the front page will be called and the browser moves to the anchor link.

Open menu and select "About us" -> the url will change, but the menu stay open and the browser will not go to the anchor.

Following software is used:

Drupal 7 website
Subtheme of bootstrap 3.4.1
https://www.drupal.org/project/responsive_menu (for mmenu)

Any help would be appreciated.

Regards

Wilfried

**Comment by FrDH** [comment]
If you link to a hash (`href="#somthing`"), the page will not reload but just append the hash to the url.
This is default browser behavior. Remove the hashes and you should be find I think.

**Comment by FrDH** [comment]
This is due to the default settings for clicking anchors. Try using the `onClick.close` (and maybe `onClick.preventDefault`) options: https://www.mmenujs.com/docs/core/options.html

Also, try the "page scroll" add-on:
https://www.mmenujs.com/docs/addons/page-scroll.html
