### ISSUE TITLE
Bootstrap target="null"

### ISSUE THREAD

**Issue by dannyboy** [FrDH/mmenu-js#1164]
When adding the **wrappers: ["bootstrap"]** the mmenu menu links add a target="null" attribute. Is this a bug? How can I get rid of this?

**Comment by FrDH** [comment]
It probably is a bug, this should have prevented undefined attricutes from being copied, but I guess it needs some finetuning:
````js
if (typeof anchor.getAttribute(attr[a]) != 'undefined') {
````

**Comment by nolyboms** [comment]
+1

i am adding "high priority"-tag to this bug.

**Comment by nolyboms** [comment]
+1

i am adding "high priority"-tag to this bug.

**Comment by nolyboms** [comment]
+1

i am adding "high priority"-tag to this bug.

**Comment by FrDH** [comment]
Should be fixed in version 8.5.15
