### ISSUE TITLE
Inline Styles Blocked By CSP

### ISSUE THREAD

**Issue by edd-smith** [FrDH/mmenu-js#1166]
When closing the menu, the JS attempts to apply an inline style. 

However, if you have a CSP (Content Security Policy) in place. This will be blocked. 

In the JS, i believe the code responsible is...

`S.node.page.setAttribute("style", S.node.page.mmStyle), e.vars.opened = !1, e.trigger("close:finish");`

I believe mmenu-js needs to be adapted to work with CSP's.

**Comment by FrDH** [comment]
Thank you for the heads up, I'll see if the script can go without it.

**Comment by FrDH** [comment]
should be fixed in 8.5.16
