### ISSUE TITLE
Combining used scripts into one file

### ISSUE THREAD

**Issue by rolecs** [FrDH/mmenu-js#1167]
Hello. My minifier script combines all used scripts in one file and puts it in folder /min/scripts_20c48c8bb0.min.js, so this breaks module import addresses:
`import Mmenu from '../../core/oncanvas/mmenu.oncanvas';
import options from './_options';
import configs from './_configs';`

Is it possible to combine used scripts into one file with all this modular system?

**Comment by FrDH** [comment]
You can use the file, it already is compiled (and minified):
https://github.com/FrDH/mmenu-js/blob/master/dist/mmenu.js

And for the css this file:
https://github.com/FrDH/mmenu-js/blob/master/dist/mmenu.css

**Comment by rolecs** [comment]
thx
