### ISSUE TITLE
menu not open on IPad mini

### ISSUE THREAD

**Issue by chenchen2003** [FrDH/mmenu-js#1168]
The menu doesn't open on IPad mini. I also checked the examples on mmenujs.com, and it doesn't work.

**Comment by chenchen2003** [comment]
append is Jquery function, it should be appendChild for the DOM elements

**Comment by FrDH** [comment]
`append` is a newer method for HTMLElements: https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append
You can manually include the needed polyfills from https://github.com/FrDH/mmenu-js/tree/master/src/_polyfills or simply use the combined polyfills from https://github.com/FrDH/mmenu-js/blob/master/dist/mmenu.polyfills.js
