### ISSUE TITLE
Divider (Bootstrap)

### ISSUE THREAD

**Issue by nolyboms** [FrDH/mmenu-js#1169]
Not working when using with Bootstrap...

````html
<li class="Divider">Section</li>
````

**Comment by FrDH** [comment]
Could you share your HTML? I believe bootstrap requires the classname `dropdown-divider`. This class is transported from the bootstrap nav to the mmenu menu.

**Comment by nolyboms** [comment]
Indeed, divider is recognized in dropdowns but a) just adds a li.mm-divider without content and b) are only transported from dropdowns.

**Comment by FrDH** [comment]
The Bootstrap wrapper probably the most out of scope part of the entire package, I really dont want to do more Bootstrap specific exceptions. You could manually rewrite the HTML (either with PHP or JS) and make it meet the mmenu requirements.
