### ISSUE TITLE
Type tabs (Bootstrap)

### ISSUE THREAD

**Issue by nolyboms** [FrDH/mmenu-js#1171]
How to make tabs work with bootstrap? This doesn't work...

```
<div class="collapse navbar-collapse" id="mcmenu">
...
</div>

<div class="collapse navbar-collapse" id="mcmenu2">
...
</div>
```

**Comment by nolyboms** [comment]
How to make tabs work with bootstrap? This doesn't work...

'<div class="collapse navbar-collapse" id="mcmenu">
...
</div>

<div class="collapse navbar-collapse" id="mcmenu2">
...
</div>
'

**Comment by nolyboms** [comment]
How to make tabs work with bootstrap? This doesn't work...

```
<div class="collapse navbar-collapse" id="mcmenu">
...
</div>

<div class="collapse navbar-collapse" id="mcmenu2">
...
</div>
```

**Comment by FrDH** [comment]
I'm not sure what you mean, could you share some more HTML en be more specific with what you're trying to accomplish?

**Comment by nolyboms** [comment]
Here is an another example code...

``
<div class="collapse navbar-collapse" id="mmenu">
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabOne</a></li>
		</ul>
	</div>
	
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>


new Mmenu(document.querySelector('#mmenu'),  {

(..)

navbars: [
	{
		type: 'tabs',
		content: [
    		'<a href="#tabOne">Menu</a>', '<a href="#tabTwo"><i class="fas fa-user"></i><span>Login</span></a>'
 		],
			position: "top",
		
	},

(..)

}
``

What i am trying to do is to have two tabs but i tried any possible way and none worked.
Looking into mmenu.js it seems that we have to assign the trigger id to the element with class navbar-collapse or it won't work.
Having two .navbar-collapse elements is also not possible.

One possible solution without to break the code would be maybe if we could do this so we weouldn't break bootstrap nav too:

``
<div class="collapse navbar-collapse" id="mmenu">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item __this_belongs_to_tabOne__"><a class="nav-link" href="">Link tabOne</a></li>
			<li class="nav-item __this_belongs_to_tabTwo__"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>
``

Or do you have an alternative way in mind?

**Comment by nolyboms** [comment]
Here is an another example code...

`
<div class="collapse navbar-collapse" id="mmenu">
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabOne</a></li>
		</ul>
	</div>
	
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>


new Mmenu(document.querySelector('#mmenu'),  {

(..)

navbars: [
	{
		type: 'tabs',
		content: [
    		'<a href="#tabOne">Menu</a>', '<a href="#tabTwo"><i class="fas fa-user"></i><span>Login</span></a>'
 		],
			position: "top",
		
	},

(..)

}
`

What i am trying to do is to have two tabs but i tried any possible way and none worked.
Looking into mmenu.js it seems that we have to assign the trigger id to the element with class navbar-collapse or it won't work.
Having two .navbar-collapse elements is also not possible.

One possible solution without to break the code would be maybe if we could do this so we weouldn't break bootstrap nav too:

`
<div class="collapse navbar-collapse" id="mmenu">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item __this_belongs_to_tabOne__"><a class="nav-link" href="">Link tabOne</a></li>
			<li class="nav-item __this_belongs_to_tabTwo__"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>
`

Or do you have an alternative way in mind?

**Comment by nolyboms** [comment]
Here is an another example code...

```
<div class="collapse navbar-collapse" id="mmenu">
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabOne</a></li>
		</ul>
	</div>
	
	<div id="tabOne">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>


new Mmenu(document.querySelector('#mmenu'),  {

(..)

navbars: [
	{
		type: 'tabs',
		content: [
    		'<a href="#tabOne">Menu</a>', '<a href="#tabTwo"><i class="fas fa-user"></i><span>Login</span></a>'
 		],
			position: "top",
		
	},

(..)

}
```

What i am trying to do is to have two tabs but i tried any possible way and none worked.
Looking into mmenu.js it seems that we have to assign the trigger id to the element with class navbar-collapse or it won't work.
Having two .navbar-collapse elements is also not possible.

One possible solution without to break the code would be maybe if we could do this so we weouldn't break bootstrap nav too:

```
<div class="collapse navbar-collapse" id="mmenu">
		<ul class="navbar-nav ml-auto">
			<li class="nav-item __this_belongs_to_tabOne__"><a class="nav-link" href="">Link tabOne</a></li>
			<li class="nav-item __this_belongs_to_tabTwo__"><a class="nav-link" href="">Link tabTwo</a></li>
		</ul>
	</div>
</div>
```

Or do you have an alternative way in mind?

**Comment by nolyboms** [comment]
By the way... a bootstrap_example.html would be a very very helpful asset to all bootstrap users.

**Comment by nolyboms** [comment]
Just saying in general...maybe a bootstrap_example.html would be a good idea to help all the bootstrap users..
