### ISSUE TITLE
I can't close a dropdown instance

### ISSUE THREAD

**Issue by numanagit** [FrDH/mmenu-js#1173]
Hi there, I'm using dropdown submenus in a horizontal parent menu (I want to mantaint it as horizontal). So, I created the instances of submenus with mmenus to open with dropdown addon. The problem is, when I set offCanvas -> blockUI to false, I'm not abble to close the dropdown.

Here is my conf:

`document.addEventListener('DOMContentLoaded', () => {

  const menuAccesoriosNauticos = new Mmenu(
    '.accesorios-nauticos-menu',
    {
      offCanvas: {
        blockUI: false,
      },
      setSelected: {
        hover: true,
      },
      navbar: {
        title: 'Accesorios Náuticos',
      },
      dropdown: {
        drop: true,
        position: '.accesorios-nauticos>a',
      },
      autoHeight: true,
    },
    {
      offCanvas: {
        page: {
          selector: '#wrapper',
        },
        clone: true,
      },
    }
  );`

Could you help me?

**Comment by FrDH** [comment]
The UI blocker is the only default way to close a menu.
If you set the `dropdown.event` option to "hover", the menu should open on mouseenter and close on mouseleave.
Or you could use the navbars add-on to add a "close" button.

But besides that, the menu works as intended.
