### ISSUE TITLE
Uncrawlable Link - <a class="mm-navbar__title">

### ISSUE THREAD

**Issue by markustobler** [FrDH/mmenu-js#1176]
Google Lighthouse has a problem with the link `<a class="mm-navbar__title">` !

Is there a way to use a other html element?

**Comment by FrDH** [comment]
No, I'll see if I can let it link to the main panel, so there always will be a `href` attribute.

**Comment by gravytrainhub** [comment]
any update on this issue?

**Comment by FrDH** [comment]
This might be fixed in the next major release. But for now it has low priority as it actually isn't much of a problem.
Lighthouse reports it as an uncrawlable link, but at that point (when it doesn't target a panel) it should not be crawlable.

**Comment by TheMangoTrain** [comment]
Is there a way to specify a custom external URL for the first-panel top navbar?

Essentially we want a "Register & Save!" type of link at the very top of the first panel, with an external link as href. For logged-in users, we just hide the navbar on first panel.

We are able to configure the text like so, but would like to be able to define a custom URL here too:
```
        mobileMenu = new Mmenu( document.getElementById("mobileMenu"), {
            "offCanvas": false,
            navbar: {
                title: "Register & Save 20%!",

                // Possible to define a custom link url here???
            }
        })

**Comment by FrDH** [comment]
No, not by default.
I guess you could write some JS to alter the href attribute of the first panel after firing the plugin.
Something like this:
````js
const navbar = document.querySelector("#mobileMenu .mm-panel .mm-navbar__title").href = "http://www.google.com";
````

**Comment by xcrap** [comment]
Are you guys going to fix this for any release, we have lighthouse errors conserving to this and the excessing dom elements.
