### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by simoneconti** [FrDH/mmenu-js#1177]
Hello everyone,
I have a typescript project and I use:

`import Mmenu from 'mmenu-js';`

but I get a

`Could not find a declaration file for module 'mmenu-js'`

Can you export the typings?
Thank you.

**Comment by olivier65** [comment]
Why was this issue closed with no explanation? As of today it is still impossible to import Mmenu in this way. It **should** be possible!

**Comment by Nicolas-PredictaLab** [comment]
Still an issue I guess.

**Comment by masi** [comment]
Odd that a project written in TypeScript has no typings for client code.

Why has the ticket been closed?

**Comment by xcrap** [comment]
Yeah, still have the same issue.
/mmenu-js/dist/mmenu.js' is not a module.
