### ISSUE TITLE
dynamic menus causes DOM leak

### ISSUE THREAD

**Issue by pigsinspace** [FrDH/mmenu-js#1178]
Fred
using version 7
we have a menu with a lot of submenus.    we dynamically build the menu since it is not always the same with each user click.  

so we need to remove all of the previous dynamically generated menu items on close.

i have 2 ways i have come up to do that.   

method 1:
 $('#my-list li').remove();
 $( "div" ).remove( ".mm-hidden" );

method 2:
    $('#my-list li').remove();
    var api = $("#taskDialog").data( "mmenu" );
    var mmenuActual = api.getInstance();
    var $panels = mmenuActual.$pnls.children();
    $panels.not(":first").remove();

Both seem to generate the same results.   

will either cause issues?
is there a simpler way to do this?
will this work on the newer versions of mmenu?   

thanks 
bill
licensed user of mmenu.

**Comment by FrDH** [comment]
removing panels or listitems should not be mutch of a problem, but it also isn't taken in consideration during development, so I can't guarantee it will always work. 
In the current and future versions, adding and removing panels and listitems should be even less prone to error, but again, it isn't a key feature so no guarantees.
