### ISSUE TITLE
Unfortunately not compatible with WPML

### ISSUE THREAD

**Issue by mediumbuddha** [FrDH/mmenu-js#1179]
Hi,
I have create a new menu in WordPress so that I can add the language switcher as menu element. In WPML I have selected languages as list (not dropdown).
In the mobile menu, only the first (of two) language option is displayed. Also, after switching the language, the displayed option doesn't change...
You can check this behavior on https://vinsdumonde.blog.
It would be nice to look into that... 
I am using the latest version of Mmenu (2.9.2).
Best regards,
Mat

**Comment by FrDH** [comment]
Thank you for reporting this. I'll have a look later on.

**Comment by mediumbuddha** [comment]
Hi , so how do you see the thing?.. Is it something you may be working on soon?
Best regards, Mat
