### ISSUE TITLE
Close option

### ISSUE THREAD

**Issue by mediumbuddha** [FrDH/mmenu-js#1180]
Hi,
When I select "use full width" mmenu, there is no close element in order to just put the menu away without selecting a menu element. I think that it would be necessary in order to make it more user friendly.
I am using Mmenu 2.9.2 (latest at this time).

Best regards,
Mat

**Comment by FrDH** [comment]
Not 100% sure at the moment (I'll check later on), but there should be an option "Add a button that closes the menu" in the "Header options" section.

**Comment by mediumbuddha** [comment]
Hello,
You are right. It is just that the option is quite hidden and visually placed at some other setting element.
Best regards,
Mat
