### ISSUE TITLE
Turbolinks Wrapper Not Working - Rails 6

### ISSUE THREAD

**Issue by MatthewKennedy** [FrDH/mmenu-js#1181]
Using the menu-js as per the documentation in a Rails 6 app I can get it to work on first page load, but if Turbolinks is used via a page navigation, then the method below will not work.

```
<script>
    document.addEventListener(
        "DOMContentLoaded", () => {
            new Mmenu( "#my-menu", {
                wrappers: ["turbolinks"]
            });
        }
    );
</script>
```

This will work, but the div that provides the overlay to close is not inserted into the DOM and other issues occur.
```
<script>
    document.addEventListener(
        "turbolinks:load", () => {
            new Mmenu( "#my-menu", {
                wrappers: ["turbolinks"]
            });
        }
    );
</script>
```

I'm using a brand new Rails 6 app nothing else in there, the menu works fine on first page load, but if you navigate using the internal inks then after than the menu is gone to hell.

It would be great if someone could fire up a fresh Rails 6 app, walk through the install process and test the Turbolinks wrapper and document how to set it all up.

**Comment by asimsikka** [comment]
Hi @MatthewKennedy , we also have the same issue with rails 5.2.2 . The wrapper does not work with latest turbolinks https://github.com/FrDH/mmenu-js/issues/1156 . Were you able to solve above?

**Comment by MatthewKennedy** [comment]
@asimsikka I'm still looking into it, it seems I can get the menu to fire, but it looks like some other parts of the JavaScript do not load in with Turbolinks, like the JavaScript that inserts the overlay blocker that you click to close the menu, and some other JavaScript that adds the relevant classes to the DOM elements.

At this stage I'm also finding the turbolinks wrapper does nothing to improve the situation in any way.

If I make any real progress I'll let you know.

**Comment by MatthewKennedy** [comment]
There is a very strange behaviour going on here, where the first Turbolinks use it works, but after that it brakes, but not fully, the menu is operating but the rest of the DOM has not been set up.

So the blocker is not inserted, the DOM is not re-arranged and wrapped as it should be.

Still looking into this, any pointer welcome.

**Comment by MatthewKennedy** [comment]
@asimsikka https://youtu.be/WqDoDfBewDw

**Comment by asimsikka** [comment]
@MatthewKennedy it looks great. Thanks for going the trouble of making the video, really appreciate it. I will give it a go later today and let you know how it worked out. 

I just have one question, after the turbolinks load do clicking on the links in menu also work? That was one of the bugs I had.

**Comment by MatthewKennedy** [comment]
Hi @asimsikka I have just tested that the links work, and they do, the links when clicked will load the new internal page using Turbolinks just fine.
