### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by Messa1** [FrDH/mmenu-js#1183]
Hey there. 

I know that IE 11 is almost dead now. But a customer use it.
I got this error.

Syntax Error
![Bildschirmfoto 2020-09-28 um 20 09 03](https://user-images.githubusercontent.com/3908658/94469480-7ac7d100-01c6-11eb-8c9d-afdc3f5c286c.png)
![Bildschirmfoto 2020-09-28 um 20 08 58](https://user-images.githubusercontent.com/3908658/94469484-7bf8fe00-01c6-11eb-9fff-c5ba1945a235.png)

This code line shows the error
`"DOMContentLoaded", () => {`

My code
```
// MMMenu

   document.addEventListener(
	"DOMContentLoaded", () => {
		new Mmenu( "#menu", {
		   "extensions": [
			  "pagedim-black",
			  "position-right"
		   ],
		   navbar : {
				title : " "
			},
		   "navbars": [
			  {
				 "position": "top",
				 "content": [
					"prev",
					"title"
				 ]
			  },
			  {
				 "position": "bottom",
				 "content": [
					"<div class='navshort'></div>",
				 ]
			  }
		   ]
		});
	}
)
```

**Comment by jhoell** [comment]
I have the exact same issue.

**Comment by Messa1** [comment]
**Update:**

With my new code i got now **Object doesn't support property or method 'append**' on IE11

```
document.addEventListener("DOMContentLoaded", function() {
    
        new Mmenu( "#menu", {
           "extensions": [
              "pagedim-black",
              "position-right"
           ],
           navbar : {
                title : " "
            },
           "navbars": [
              {
                 "position": "top",
                 "content": [
                    "prev",
                    "title"
                 ]
              },
              {
                 "position": "bottom",
                 "content": [
                    "<div class='navshort'></div>",
                 ]
              }
           ]
        });     

} );
```

**Comment by Messa1** [comment]
Update 2: 
@jhoell Load this script in your document and it works -> 
https://polyfill.io/v3/polyfill.min.js?features=Array.prototype.forEach%2CElement.prototype.matches%2CElement.prototype.prepend%2CElement.prototype.closest%2CElement.prototype.append%2CElement.prototype.before%2CNodeList.prototype.forEach
