### ISSUE TITLE
Is there a way to link between panels? 

### ISSUE THREAD

**Issue by jennykb** [FrDH/mmenu-js#1184]
I'm using my menu to accompany and explain an online gameboard; the different panels and subpanels of the menu offer rules and variations of play. So the user stays on a single page and clicks forward and back between different menu panels. I'm wondering if there's a way to directly link from one panel to another, within the menu itself. 

```
<nav id="menu">
  <ul class="">
	  	<div class="menu-content"></div>
	  	<li><a href="" class="">The Basic Game</a>
   			<ul>
		   		 <li class=""><a href="">Round 1: <strong>Opening Oracle</strong></a>
		   		 <ul><div class="menu-content">Round 1 description - would love to link from here directly to the open panel of Round 2</div></ul>
		   		 </li>		   		 
		   		 
		   		 <li class=""><a href="">Round 2: <strong>Roundabout</strong></a>
		   		 <ul><div class="menu-content">Round 2 description</div></ul>
		    	         </li>
	    	 
		   		 <li class=""><a href="" id="keep-stop-start">Round 3: <strong>Keep, Stop, Start</strong></a>
		   		 <ul><div class="menu-content">Round 3 description</div></ul>
		   		 </li>
		   		 
		   		 <li class=""><a href="">Round 4: <strong>Closing Question</strong></a>
		   		 <ul><div class="menu-content">Round 4 description</div></ul>
		   		 </li>
	   		</ul>
	   	</li>
    </ul>
</nav>
```

I'd love to be able to link directly from the Round 1 description to the Round 2 description, rather than having to click back from Round 1 to the parent menu and then click forward into Round 2.

The menu in action can be seen here: https://emergentgame.com/freeplay-reduced-case.php

**Comment by jennykb** [comment]
Arrgh... can't seem to make the code format properly in the post. Screenshot of code attached:
<img width="984" alt="Screen Shot 2020-09-28 at 10 25 37 PM" src="https://user-images.githubusercontent.com/35789475/94505677-9d171a00-01d9-11eb-9455-43dc3c8d57a3.png">

**Comment by FrDH** [comment]
By default, any anchor that links to a panel, will open the panel:
````html
<nav id="menu">
    <ul id="first-panel">
        <li><a href="#second-panel">Open second panel</a></li>
    </ul>
    <ul id="second-panel">
        ...
    </ul>
</nav>
````

**Comment by jennykb** [comment]
Brilliant, thanks so much.
