### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by olivier65** [FrDH/mmenu-js#1185]
On the [Fire the plugin](https://mmenujs.com/tutorials/off-canvas/fire-the-plugin.html) page you refer to `api.open()` and `api.close()` methods that don't seem to exist anymore. Mmenu version is 8.5.17

**Comment by FrDH** [comment]
Both the `open` and `close` methods should still be present. Have you tried using them? Are you getting any errors?

**Comment by olivier65** [comment]
They are totally not there and of course I do get an error when trying to use them. However, after some debugging I narrowed it down to `offCanvas: false` and now I see in the docs that `open` and `close` are methods of the offCanvas add-on, so that makes sense.
I wish there was a mode in which the menu can be opened and closed but as a floating window, i.e., absolutely positioned, without messing up the rest of the page. But I can probably implement that myself.
