### ISSUE TITLE
Can't close sidebar menu on desktop

### ISSUE THREAD

**Issue by jennykb** [FrDH/mmenu-js#1186]
I'm trying to recreate something similar to the mmenu.js demo, which starts with an open sidebar menu but which can be collapsed upon clicking the hamburger/X menu. The menu is working perfectly in almost every way, except that clicking the X doesn't collapse the sidebar. What am I missing/doing wrong?

My menu code: 
```
document.addEventListener(
        "DOMContentLoaded", () => {
            new Mmenu( "#menu", {
	            columns: false,
                
                sidebar: {
                            collapsed: {
                                use: 768,
                                hideNavbar: !0,
                                hideDivider: !0
                            },
                            expanded: {
                                use: 1440,
                                initial: "remember"
                            }
                        },
                navbar: {
                    title: "The Emergent Game"
                }
            });
        }
    );
```

You can see a reduced case instance of the menu here: [https://emergentgame.com/freeplay-reduced-case.php]

Grateful for any help!

**Comment by FrDH** [comment]
That doesn't work by default, you'll need to change the `href` on the hamburger to target the "page" instead of the menu. You can bind methods to the `open` and `close` hooks using the API:

Here's my js for that:
````js
    var menu = new Mmenu( "#menu", {
        // options
    });
    var API = menu.API;

    var $burger = document.querySelector("#hamburger");

    API.bind("close:finish", function () {
        setTimeout(function () {
            $burger.attr("href", "#menu");
        }, 100);
    });

    API.bind("open:finish", function () {
        setTimeout(function () {
            $burger.attr("href", "#page");
        }, 100);
    });
````

**Comment by jennykb** [comment]
I must be putting it in the wrong place, or not specifying something that needs to be specified. I’m getting this error: "TypeError: undefined is not an object (evaluating 'API.bind’)"

    document.addEventListener(
        "DOMContentLoaded", () => {
            new Mmenu( "#menu", {
	            "dividers": {
                  "addTo": "panels"
               },
                sidebar: {
                            collapsed: {
                                use: 768,
                                hideNavbar: !0,
                                hideDivider: !0
                            },
                            expanded: {
                                use: 1440,
                                initial: "remember"
                            }
                        },
                navbar: {
                    title: "The Emergent Game"
                }
            });
	            
	            var API = menu.API;
	
			    var $burger = document.querySelector("#hamburger");
			
			    API.bind("close:finish", function () {
			        setTimeout(function () {
			            $burger.attr("href", "#menu");
			        }, 100);
			    });
			
			    API.bind("open:finish", function () {
			        setTimeout(function () {
			            $burger.attr("href", "#page");
			        }, 100);
			    });

        }
    );

**Comment by Messa1** [comment]
You need to change 

`new Mmenu( "#menu", {`

`var menu = new Mmenu( "#menu", {`

**Comment by Messa1** [comment]
Check my post here -> for a working example
https://github.com/FrDH/mmenu-js/issues/1190

**Comment by jennykb** [comment]
Thanks, Messa1! I appreciated looking at your code. That took care of the error... but the opening/closing mechanism still isn't working. 
```
document.addEventListener(
       "DOMContentLoaded", () => {
           var menu = new Mmenu( "#menu", {
         onClick : {
           close          : true,
           preventDefault : false,
         },
           "dividers": {
             "addTo": "panels"
          }, sidebar: {
                      collapsed: {
                          use: 768,
                          hideNavbar: !0,
                          hideDivider: !0
                      },
                      expanded: {
                          use: 1440,
                          initial: "remember"
                      }
                  },
          navbar: {
              title: "The Emergent Game"
          }
           });
       
       var API = menu.API;

       var burger = $("#hamburger");

       API.bind("close:finish", function () {
         setTimeout(function () {
           burger.attr("href", "#menu");
         }, 100);
       });

       API.bind("open:finish", function () {
         setTimeout(function () {
           burger.attr("href", "#page");
         }, 100);
       });
       
       }
   );
```
This is happening at `https://emergentgame.com` . If you have any further insights, I'd be grateful!

**Comment by Messa1** [comment]
You need to change

**<div class="page">**

to

**<div id="page">**

**Comment by jennykb** [comment]
Thank you so much! An elemental error on my part... but it still ain't working. Check this out. When I view page source (and, of course, in my original code), I see this: 
```
<body class="freeplay game" onload="shuffle(allCards)"> 
	<div class="page">
		
		<div id="sidebar">

<nav id="menu">
```
But when I look at the code in the inspector, I don't see #page at all, presumably because of the menu's being open...? Am I wrapping the page the wrong way? Am I missing something else obvious? 

<img width="940" alt="Screen Shot 2020-10-13 at 9 46 21 AM" src="https://user-images.githubusercontent.com/35789475/95869397-4f51f400-0d39-11eb-93fe-97e5d1983afb.png">

Ah... as I wrote this I figured it out. I had to add
```
offCanvas: {
                      page: {
                          selector: "#page"
                      }
                  },
```
as well.

Thank you so much! Can I send you a coffee or a beer?

**Comment by jennykb** [comment]
Haha I'll see if my son (in Germany) has any ideas. Really grateful for your help, thank you so much.

**Comment by Messa1** [comment]
Np :) I try to give the community something back. Cause i also need sometimes help :) As long everything works now :)

**Comment by jennykb** [comment]
Hey Matthias! I have a follow-up question for you. I just noticed that, while the sidebar menu is closing properly when the user clicks outside the sidebar on the page, it is ALSO closing — when I don't want it to — when I click on the TEXT of a menu item (as opposed to clicking on the opening caret > ). Any ideas of how I can fix this? Or maybe this is worth opening a new ticket for...

https://emergentgame.com/

**Comment by Messa1** [comment]
You mean something like here in this ticket? https://github.com/FrDH/mmenu-js/issues/242

**Comment by jennykb** [comment]
Thanks for the link! That solution doesn't seem to be working for me, though. When I click on the menu items, the menu still collapses instead of opening the subpanel. Hmmm.

**Comment by jennykb** [comment]
Ah, I figured it out. It was a matter of assigning IDs to the uls and setting the parent li's link tags to the correct anchor.
