### ISSUE TITLE
Remove navbar first panel

### ISSUE THREAD

**Issue by mx928** [FrDH/mmenu-js#1187]
Hello!

How to remove/hide top navbar at first page?

**Comment by FrDH** [comment]
There is no option for that, but I guess you could add a class that hides it after initiating the plugin:
````js
var $menu = document.querySelector("#menu");
new Mmenu($menu, {
    // options
});
$menu.querySelector("mm-navbar").classList.add("mm-hidden");
````
Hope this helps.

**Comment by mx928** [comment]
I get an error with this example - Uncaught TypeError: Cannot read property 'classList' of null

**Comment by FrDH** [comment]
My bad, should be `$menu.querySelector(".mm-navbar")`.
