### ISSUE TITLE
Unfortunately not compatible with ASP.NET MVC

### ISSUE THREAD

**Issue by ghost** [FrDH/mmenu-js#1188]
Please see the link [https://stackoverflow.com/questions/64238800/mmenu-plugin-is-not-used-in-asp-net-mvc-home-index-page](url)

**Comment by msmumbucoglu** [comment]
hi Fred, i opened an issue about mmenu. Can you help me.

**Comment by FrDH** [comment]
You might need to have a look at the [off-canvas configuration](https://mmenujs.com/docs/core/off-canvas.html)
By default, it assumes a (singular) `<div />` to be the "page", with ASP I think it's a `<form />`.

**Comment by msmumbucoglu** [comment]
This is not exactly what I want. mmenu.js adds its own css classes to the body. For example, the mm-wrapper. But asp.net mvc also has the concept of layout. All contents are rendered into a div in the layout. The previous asp corresponds to this masterpage. My aim is to use mmenu in a div. Without breaking the default header and footer of Asp.net mvc, to use mmenu in the rendered part. Do you have a solution for this.

**Comment by FrDH** [comment]
With the off-canvas configuration, you can also specify where the menu should be inserted, defaulting to the `<body>`. Does it help is you override that?
