### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by Sibbo100** [FrDH/mmenu-js#1189]
I'm using the Wordpress plugin on my site and I have the 'Enable navigating with a keyboard.' checkbox enabled but the sub nav does not appear to be accessible via the keyboard or tab controls, I have a hamburger menu that I am using to open and close the mobile navigation (only being used on devices with screens smaller than 1024px). Any ideas what the problem could be?

Site can be viewed here: https://differentminds.scot/

Thank you
Sibbo100

**Comment by FrDH** [comment]
With what browser did you test? I tried Chrome and it appeared to work as intended. For FireFox I think you need to enable tabbing to anchors (as by default it only tabs to form elements).

**Comment by Sibbo100** [comment]
Hi FrDH, I'm trying this on Chrome but using developer tools and the device toolbar as I only want/need the menu on mobile devices, so if I tab through the content on the site and activate the hamburger menu, focus never seems to shift from the hamburger menu, I want/need focus to shift to the actual menu system for accessibility so users can tab through the menu or use the up and down arrows etc.

Thank you
Sibbo100

**Comment by FrDH** [comment]
Did you add the keyboard navigation add-on?
https://mmenujs.com/docs/addons/keyboard-navigation.html

**Comment by Sibbo100** [comment]
Hi FrDH,

Can this be added if I'm using the Wordpress Plugin, or should it already be active through that.

Thank you
Sibbo100

**Comment by FrDH** [comment]
Should be available in the "Accessibility" section on the admin page.
