### ISSUE TITLE
Disable automatic menu open during Load

### ISSUE THREAD

**Issue by arun4927** [FrDH/mmenu-js#1192]
Menu automatically open during load. I want to disable the automatic opening and want it to open only when clicked

**Comment by FrDH** [comment]
The menu will open its hash is in the URL, could that be the case? Without some more information or an online example there is not much I can do for you.

**Comment by arun4927** [comment]
I have read about this "#menu" as many people have mentioned about the same. I have already removed the "#" from the "#menu" still it menu automatically opens during page load. Please let me know if there is any other solution to it.

My webpage is https://wifd.in/coffee_painting

**Comment by arun4927** [comment]
I have read about this "#menu" as many people have mentioned about the same. I have already removed the "#" from the "#menu" still it menu automatically opens during page load. Please let me know if there is any other solution to it.

**Comment by FrDH** [comment]
If there is no "#menu" in the url, the menu should not open (unless you're using the sidebar add-on). Without an online example there is not much I can do for you.
