### ISSUE TITLE
PayPal express checkout issue

### ISSUE THREAD

**Issue by tmccambridge** [FrDH/mmenu-js#1194]
Hi there
Thanks for the WP plugin. I'm experiencing an issue where the menu plugin is causing PayPal express checkout to not load on product or cart page within WooCommerce. I've tried to resolve this, but can't seem to find a way around. Any help?

https://www.happyconfident.com/cart/?add-to-cart=46

**Comment by FrDH** [comment]
Is there still a working example? Issues like this mostly happen due to the plugin wrapping all markup in a single `<div>`,
Have a look at this tutorial:
https://mmenujs.com/tutorials/off-canvas/
