### ISSUE TITLE
Submenu Issue in mobile device

### ISSUE THREAD

**Issue by ektakanojiya** [FrDH/mmenu-js#1197]
I have implemented mmenu.js (5.8.0) in my project.
I have used Keyboard navigation add on to make it accessible using keyboard.
 keyboardNavigation : {  // Enable keyboard focus
          enable: 'default',
          enhance: true
      }

It's working fine in web but in mobile device (with accessibility on) it's not displaying proper focus in sub menu items and also announces  parent menu item names(means traversing in background)

can any one help in this?

**Comment by FrDH** [comment]
Have you tried updating to the latest version?
