### ISSUE TITLE
question about icon for menuitem

### ISSUE THREAD

**Issue by vincedan** [FrDH/mmenu-js#1202]
Hi,   it is obvious that menuitem icon is very important, as you had done in https://mmenujs.com, but not in mmenujs.  in compact display (small device), should have the similar control as sidebar does, I mean -- not display menuitem icon in compact display mode if developer set related css code. wish you could add this feature in mmenujs.
Thanks

**Comment by FrDH** [comment]
I don't understand the question, what are you trying to achieve?
