### ISSUE TITLE
Webpack 5 warning: Should not import the named export 'version'  (imported as 'pack') 

### ISSUE THREAD

**Issue by innesm4** [FrDH/mmenu-js#1203]
**Describe the warning**

https://webpack.js.org/migrate/5/#cleanup-the-code

> Using named exports from JSON modules: this is not supported by the new specification and you will get a warning. Instead of import { version } from './package.json' use import package from './package.json'; const { version } = package;

**To Reproduce**

Using Laravel Mix v6 that uses webpack v5

```
WARNING in ./node_modules/mmenu-js/dist/core/oncanvas/mmenu.oncanvas.js 759:20-32
Should not import the named export 'version' (imported as 'pack') from default-exporting module (only default export is available soon)
```

webpack compiled with 1 warning

Looks to be line 1 of [https://github.com/FrDH/mmenu-js/blob/master/dist/core/oncanvas/mmenu.oncanvas.js](https://github.com/FrDH/mmenu-js/blob/master/dist/core/oncanvas/mmenu.oncanvas.js)

**Comment by twd3** [comment]
Confirmed.

**Comment by FrDH** [comment]
Thanks, I'll remove it.

**Comment by FrDH** [comment]
should be fixed
