### ISSUE TITLE
window.onscroll not work with mmenujs

### ISSUE THREAD

**Issue by Rstcommercial** [FrDH/mmenu-js#1204]
The script window.onscroll = function () {} that without mmenujs works correctly, instead with mmenujs inside the page the script doesn't work and is not processed by the browser.
What can be done?

Thank

**Comment by FrDH** [comment]
That sounds weird. Have you tried it like this?
````js
window.addEventListener("scroll", function() {

});
````

**Comment by Rstcommercial** [comment]
> ```js
> window.addEventListener("scroll", function() {
> ```

Yes i tried and not work! I tried  window.addEventListener and  document.addEventListener. :/

**Comment by Rstcommercial** [comment]
I have put the css <link href="https://www.mysite.it/function/mmenu.css" rel="stylesheet" /> AND <link href="https://www.mysite.it/function/mburger.css" rel="stylesheet" /> in the <HEAD> of page.

And the JS <script src="https://www.mysite.it/function/mmenu.js"></script> OVER the script new Mmenu <script type="text/javascript">new Mmenu( document.querySelector('#menu'), both positioned  in the FOOTER of page before </BODY>

WORK FINE BUT NOT OTHERS ONSCROLL EVENT IN MY PAGE!! How solve? Thanks :P

**Comment by FrDH** [comment]
Is there an online example? I tried adding an onscroll eventlistener and it worked without any issues.

**Comment by Rstcommercial** [comment]
Risoved:
`var myBodyOBJ = document.body || document.getElementsByTagName("body")[0] || document.documentElement;
myBodyOBJ.addEventListener("scroll", function(){ ... });`

Thanks

**Comment by Rstcommercial** [comment]
SOLVED:

The problem was not scroll event BUT THE CSS BODY SET HEIGHT:100%.
Remove Body Height:100%; and put window.addEventListener("scroll", function(){ ... }); THIS WORK FINE!

Best Regards
