### ISSUE TITLE
Trying to change position of search bar

### ISSUE THREAD

**Issue by spohlman** [FrDH/mmenu-js#1205]
I've tried moving the search bar to the bottom using the following code:

  $(".menu-mobile-menu-container").mmenu({
    "navbars": [
    {
        "position": "bottom",
        "content": [
            "searchfield"
        ]
    }
  ]
  });

This change is being applied to another menu that is hidden. The one being displayed doesn't even have my class name.

**Comment by FrDH** [comment]
That looks correct. Is there an online example I could have a look at?

**Comment by spohlman** [comment]
Sorry I forgot to include it in my original post. 
https://stgg.org/
Breakpoint is 1024px.

**Comment by spohlman** [comment]
Was this looked at?

I also tried adding a link to see if it would show up on top of the menu.

$(".menu-mobile-menu-container").mmenu({
                "navbars": [
                {
                        "position": "bottom",
                        "content": [
                        "searchfield"
                        ]
                },
		{
			"position": "top",
			"content": ["<a href='#page'>Menu</a>"]
		}
]
});

In the following image, the div marked red is this hidden menu that has my changes, and the div marked yellow is the one being displayed.

![image](https://user-images.githubusercontent.com/49449895/106282632-de164e00-620e-11eb-9889-a2334f7cb70e.png)

**Comment by FrDH** [comment]
I see you are also using the WP plugin. That is probably the menu displayed (the yellow one). If you want to invoke the js plugin manually (as you did with `jQuery(document).ready(function($) {`, I'd disable the WP plugin.
