### ISSUE TITLE
open mmenu section on mobile device don't scroll page 

### ISSUE THREAD

**Issue by BMMarius** [FrDH/mmenu-js#1206]
On mobile devices when an mmenu submenu section (mm-panel) is open, touching and swiping on that section won't scroll the page up and down.

Version is 8.4.6

**Comment by FrDH** [comment]
is there an online example I could have a look at? I cant reproduce the issue.

**Comment by Bmeist** [comment]
I am having the same trouble.  If you go to https://www.tigernet.com on a mobile device, open the menu, then click Football to open the submenu, you can't touch scroll with any of the football submenu items, only the football menu item itself.

Thanks for any help!

**Comment by BMMarius** [comment]
Hi, in m case it helped to set the scroll fix addon to false:

scrollBugFix: {

    "fix" : false // scroll bug fix options

}



Am Mo., 8. März 2021 um 17:18 Uhr schrieb Bmeist ***@***.***>:
