### ISSUE TITLE
Examples on websites are not correct.

### ISSUE THREAD

**Issue by arrayofletters** [FrDH/mmenu-js#1207]
For instance, on https://mmenujs.com/examples.html#playground

There is no "my-menu" element in the HTML.

Also it would be really helpful if there were some examples on Codepen (or other online dev environment).

**Comment by FrDH** [comment]
Where did you read the examples are the same as the playground?

**Comment by arrayofletters** [comment]
That's not what I said.  Just trying to be helpful...

I was going to purchase this product, I will have to reconsider.
