### ISSUE TITLE
submenu arrow links and counter disappearing on small screens !urgent

### ISSUE THREAD

**Issue by dabricks** [FrDH/mmenu-js#1210]
Hi
I have this issue where on small screens (from 320px up to around 500px) when entering submenus the whole menu gets resized and the page seems to get over the menu hiding both the arrows and counters for the sub-sub-menus. 
I hope I can get your support ASAP. this is a major problem on my site

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
Also, try changing the viewport meta tag, see this issue: 
https://github.com/FrDH/mmenu-js/issues/1153

**Comment by dabricks** [comment]
Hi, have a look here: https://navigiw.com

**Comment by dabricks** [comment]
have tried both :
`<meta name="viewport" content="width=device-width minimum-scale=1.0 maximum-scale=1.0 user-scalable=no" />`
and 
`<meta name="viewport" content="width=device-width initial-scale=1.0" />`
It didn't make a difference, when the menu get first triggered it gets sized right, but when accessing the submenus the scale changes and the arrows diasppear

**Comment by Chriz74** [comment]
I have the same problem. Sizes under 545px have missing arrows ...

**Comment by dabricks** [comment]
Great minimum-scale=1.0 finally fixed it .
thank you all
