### ISSUE TITLE
List Render In Mobile

### ISSUE THREAD

**Issue by ParminderSinghDaffodilsw** [FrDH/mmenu-js#1211]
Hi,

A few months ago I have added the mmenu-light.js in my ASP.Net web forms for desktop and mobile views and it was working as expected.

But now it suddenly stops working in mobile view. It is working in some mobiles and not in some others. It looks unable to load the child list menu. Sometimes it loads but cut off the half. 

I have tried to debug but not found the actual reason. By multiple tries, I found one thing is when we used the large list only then we are getting this issue. Because of the requirements, we have to use the large list in the menubar. It is working fine on desktop but on mobile, it is doing unexpected things.

I have also tried updating the latest js from https://www.mmenujs.com/ but not works.

I have attached some images for reference with different child menu or grandchild menus

If you have any solution please help me to sort it out.
For testing purposes, I have set the list with some testing info that is the same as the original except the redirect URLs and headings are on https://develop4-apprende.n4m.net/Default.aspx.
**The testing is done in Pixel 3, 4, 5, and Samsung android mobiles.**
![HamburgerBarTest1](https://user-images.githubusercontent.com/77195715/107778591-4403e900-6d6a-11eb-8fa6-a7ed464f0ac5.png)
![HamburgerBarTest2](https://user-images.githubusercontent.com/77195715/107778601-45cdac80-6d6a-11eb-82aa-f5b398d1636a.png)
![HamburgerBarTest3](https://user-images.githubusercontent.com/77195715/107778606-46664300-6d6a-11eb-841f-08f5b0c12bbf.png)

Thanks,
Parminder Singh.

**Comment by FrDH** [comment]
Hi,

That looks really weird.
The mmenu light plugin has always been stretching what can be done with CSS only (withouth altering the HTML), but for as far as I know, it always worked on all devices and browsers.

Do the examples on the website work on those devices? 
Is there an online example I could have a look at?
