### ISSUE TITLE
iOS / OS X: No sticky navbar after last element of initial viewport leaves viewport by scrolling

### ISSUE THREAD

**Issue by wmdkdkussin** [FrDH/mmenu-js#1212]
Hi,

we have an issue with iOS (Safari and Chrome Browser) and OS X (only Safari Browser) and mmenu v8.5.

Check the attached video and keep your focus on the navbar (compare screenshot):
![image](https://user-images.githubusercontent.com/6641765/108864051-1f253680-75f2-11eb-8d4b-6f8bf84bc0e2.png)

1st video shows the behavior on Chrome Browser on pc like we want to have it on iOS/OS X: https://user-images.githubusercontent.com/6641765/108862703-c73a0000-75f0-11eb-8521-e191f2764202.mp4

And the 2nd video shows the behavior on iOS/OS X as it is: 
https://user-images.githubusercontent.com/6641765/108862646-b7bab700-75f0-11eb-9346-a4e85c7f2202.MP4

For us it seems like a bug and we would like to have the iOS/OS X navbar stay the whole time while scrolling.

Thanks for your support.

BR, Daniel

**Comment by FrDH** [comment]
That sure is weird.
Do you see the same issues with the provided examples in the download (after adding some more listitems)? Or is there an online example I could have a look at?

**Comment by wmdkdkussin** [comment]
Well, I can't tell you that because no example has enough list items to reproduce our issue.
