### ISSUE TITLE
pageScroll update is not working correctly

### ISSUE THREAD

**Issue by vincentvega123** [FrDH/mmenu-js#1213]
I am trying to use the pageScroll add-on including the update function of the menu-items when scrolling the page. The menu items change the classes while scrolling, but far away from where the elements actually begin and very shortly after each other. Seems like the height of the elements is not calculated properly or something like that.

Additionally scrolling works fine on the desktop, but on my iOS Devices it just jumps to the selected section (no smooth scrolling). This behaviour is same like in your example on your website, so I don't know if it might be a bug, or a simply a missing feature.

I can give you a link to the Website where I tried to get it running. But I don't want to post it here. In case you want to have a look at my example, it would be good if I can send to you in a different way.

**Comment by FrDH** [comment]
The scrolling uses `scrollTo` with ` behavior: 'smooth'`, this might not be supported by all browsers.
For the update function, how large are the sections? try if making them (at least) 100vh helps. Might not be what you need, but would help explain the issue.
Also, have you tried the `updateOffset` config option? It is set to 50 by default.

**Comment by vincentvega123** [comment]
You are right, behaviour: smooth seems not to be supported by safari without a hack yet. Concerning the update-problem I tried what you said. But even with 100vh nothing changes. there are three sections in my page, each of them is higher than 100vh anyway...oh...but has it to be a <section>? I am using div ids to jump... updateOffeset is also set (0).
