### ISSUE TITLE
Conflict with Borlabs Cookie Plugin

### ISSUE THREAD

**Issue by mediumbuddha** [FrDH/mmenu-js#1214]
Hello,

The mmenu WordPress plugin should have the option offCanvas.page.noSelector customisable (https://mmenujs.com/docs/core/off-canvas.html#h2).

Change:
pageSelector: "> div:not(#wpadminbar)"
to:
pageSelector: "> div:not(#wpadminbar)",
				page: {
					noSelector: ["[data-nosnippet]"]
				}

Borlabs Cookie Plugin: https://de.borlabs.io/

Best regards,
Matthias

**Comment by FrDH** [comment]
Thanks, I'll keep this in mind for the next release.
