### ISSUE TITLE
menu width doesn't change after changing SCSS values, GULP build issues

### ISSUE THREAD

**Issue by lix2k3** [FrDH/mmenu-js#1216]
Hello,

I have followed the tutorial on how to change the SCSS variables and then run gulp to build the CSS file. However, the CSS file  never changes. The menu always appears with the same width and color despite my changes.  The files are all in their right folders, following the tutorial on the website precisely.

On another note, the JS file that gets built contains errors.  For example, I get a i is no defined error.

**Comment by FrDH** [comment]
If the compiled js file contains errors, my guess is the build didn't work as intended. Are you getting any errors during the build?
