### ISSUE TITLE
WordPress 5.7 / jquery issue: jQuery.fn.focus() event shorthand is deprecated

### ISSUE THREAD

**Issue by FriendlyWP** [FrDH/mmenu-js#1218]
With the most recent update, WordPress has upgraded its jQuery version and now deprecates the .focus shorthand, so we're seeing a Warning in console when the mmenu WordPress plugin is activated:

`jQuery.fn.focus() event shorthand is deprecated`

To see & track down this error you can install the Enable jQuery Migrate Helper plugin which will log the issues. Since the file is minified I can only see that the error is occuring somewhere in mmenu.js. I'm running version 2.9.2 of your plugin.

Thanks for your help!

**Comment by FrDH** [comment]
Thank you for the heads up. The next version of the WP plugin will no longer be needing jQuery, so that should help :)
