### ISSUE TITLE
RE: mobile 

### ISSUE THREAD

**Issue by poweredbyarc** [FrDH/mmenu-js#1221]
Hey there second level of the menu doesn't seem to be rendering in the word press plugin.  Any help would be appreciated.

![image](https://user-images.githubusercontent.com/74789327/113917529-4fdebb00-97af-11eb-92b2-c61bbd606d49.png)

**Comment by FrDH** [comment]
Hi, 
This is probably due to the HTML not being what the pluginn expects. The plugin expects the HTML to be like this:
```html
<nav>
   <ul>
      <li><a>...</a>
         <ul>...</ul>
      </li>
   </ul>
</nav>
```

If you can, please create a menu that follows this markup, more information can be found [here](https://mmenujs.com/tutorials/off-canvas/the-menu.html)
