### ISSUE TITLE
Need to fix documentation

### ISSUE THREAD

**Issue by vosidiy** [FrDH/mmenu-js#1225]
I tried as per documentation but nothing worked. 
new Mmenu( "#my-menu" );

Then found on demo it uses different code
new Mmenu(document.querySelector('#menu'));

Just because of this I wasted much time

**Comment by FrDH** [comment]
I had a look at the code, and both a string and a HTMLElement should work:
````js
this.node.menu = typeof menu == 'string' ? document.querySelector(menu) : menu;
````
Ofcourse the querySelector you use should match the ID for the element.
