### ISSUE TITLE
scrolling (dragging) of submenus is not working on Safari (iOS)

### ISSUE THREAD

**Issue by joellehelgert** [FrDH/mmenu-js#1227]
Hi there,

For me, it seems like that on Safari there is a scrolling issue. If there are too many entries for the screen, the scrolling won't work (scrolling with a mouse works but not on dragging via touch). I could also reproduce this issue with the example page as you can see in the attached video. In the video, I tried dragging up and down, then scrolling with the mouse wheel and again dragging up and down.

Best regards!

https://user-images.githubusercontent.com/23167586/117282227-c92c0500-ae64-11eb-96b2-5873f42e8236.mov

PS: I think it is not a duplicate of https://github.com/FrDH/mmenu-js/issues/1206, since that issue seems to mean the page is not scrollable anymore and not parts of the mmenu.

**Comment by FrDH** [comment]
Hi,

Does dragging a scrollable element like that work at all in the responsive debugger?
I tried but couldn't drag any page (from any website).

**Comment by joellehelgert** [comment]
Hi!

Yeah, you are right, dragging does not work in the debugger...
The issue on my website is still there (on a real device) but not on your demo page so it must be somewhere in my part of the code! ;) 
Thanks for looking into it!
