### ISSUE TITLE
Worpress Plugin Uncaught TypeError

### ISSUE THREAD

**Issue by schregsimone** [FrDH/mmenu-js#1232]
Hi
After updating my Wordpress installation, theme and plugins the menu doesn't open anymore and I get the following error in my console:
Uncaught TypeError: can't access property "open", api is undefined
Does anyone know how to fix this issue?
Thanks!

**Comment by FrDH** [comment]
Hi,

Please try and re-save the menu settings from the admin page.
Hope this helps.

**Comment by schregsimone** [comment]
Hi,
I could solve the issue by relocating the menu. The css selector of the target menu container was changed by the theme developers. 
Thanks
