### ISSUE TITLE
Using / for division is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by devi4nt** [FrDH/mmenu-js#1233]
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($minWidth, $width)

More info and automated migrator: https://sass-lang.com/d/slash-div

```
    ╷
144 │     @media all and (max-width: $minWidth / $width) {
    │                                ^^^^^^^^^^^^^^^^^^
    ╵
    node_modules/mmenu-js/src/_mixins.scss 144:32                     mm-position-right()
    node_modules/mmenu-js/src/_mixins.scss 91:5                       mm-columns-size()
    node_modules/mmenu-js/src/addons/columns/mmenu.columns.scss 31:1  @import
    node_modules/mmenu-js/src/mmenu.scss 23:9                         @import
    scss/site/_rules.scss 5:9                                         @import
    scss/styles.scss 50:9                                             root stylesheet
```

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

**Comment by devi4nt** [comment]
Any plans to resolve the following warning? There are others being thrown, it looks like there is an automatic migrator documented here (alongside the reasons for the change) https://sasscss.org/documentation/breaking-changes/slash-div

```
$ npm install -g sass-migrator
$ sass-migrator division **/*.scss
```

**Comment by AndersBrohus** [comment]
Looking forward to getting this resolved - Since we are also getting this error with Dart Sass and Webpack 5 :)

**Comment by FrDH** [comment]
Thank you for the heads up, I'll have a look at this later on. Probably will be in the next major release though.

**Comment by binaryben1010** [comment]
Really need this fixed !

**Comment by FrDH** [comment]
This issue should be fixed in version 9.
Please note that this is a major version update and it is not completely backward compatible, for more info see the [changelog](https://mmenujs.com/docs/changelog.html)
