### ISSUE TITLE
Refresh method in API for Angular

### ISSUE THREAD

**Issue by rubenRP** [FrDH/mmenu-js#1238]
I'm using mmenu with Angular. Works fine if the items are an object, but fails if are an observable because the observable resolves after the init of Mmenu.
**Template**

![template](https://user-images.githubusercontent.com/11374916/122252935-035cdd80-cecc-11eb-8551-c301329c4ae0.png)

**Component**

![component](https://user-images.githubusercontent.com/11374916/122252984-0e177280-cecc-11eb-9109-b3ce1354ea15.png)

Is there a workaround to regenerate the menu when triggers the ngOnChanges() event for example?

**Comment by FrDH** [comment]
No, the plugin won't work with observables/
