### ISSUE TITLE
Request: Make docs repository public (as example)

### ISSUE THREAD

**Issue by tacman** [FrDH/mmenu-js#1240]
Awesome library, thanks for making this available!

It seems like the mmenu documentation site is among the best full-features examples.  Is the code available somewhere?  Often I see something in the documentation navigation and wonder how it was done, it'd be great to simple find the page and see the HTML and mmenu calls.

Thanks.

**Comment by tacman** [comment]
Please...?  My implementation is constantly animating, making it unusable for desktop.  But I quite like the way the documentation looks.

**Comment by FrDH** [comment]
Hi, sorry for the late reply. I'm not going to make the docs public, if you have any questions or need help you can always open an issue.
