### ISSUE TITLE
"Searchfield" ad-on: "Cancel" doesn't work when "showSubPanels" is set to true

### ISSUE THREAD

**Issue by kctdfh** [FrDH/mmenu-js#1249]
Hey! Thanks for the amazing library - its been a hit for us.

We have a rather complex and cavernous menu and want to search functionality to "teach" the users where they can find each page as well as a way for them to search by sub-menu name. To achieve this, we're setting the "showSubPanels" option to "true" so that they know which sub-menu to look for the next time they need a page or sub-folder.

The issue is that the cancel button doesn't seem to work without an independent search panel (i.e. `showSubPanels: false`)

I made a fiddle to show what goes wrong:
http://jsfiddle.net/kc_tdfh/s41bj2wd/6/

Imagine that we want to search for "The team". When `showSubPanels: true`, the search doesn't reset and there's an error in the console that refers to this line:
https://github.com/FrDH/mmenu-js/blob/cc566754025757a4f7dcf00f4b807311c15eba5d/src/addons/searchfield/mmenu.searchfield.ts#L307

Is this intended? How can we keep the cancel button but show the results in their own pane?

Cheers

**Comment by FrDH** [comment]
The cancel button indeed was intended to cancel the searchpanel (the panel you get when using the "panel" option).
If you're looking for a button to clear out the searchfield, the the "clear" config option.

````js
new Mmenu("#menu", {
   searchfield : {
      // options
   }
}, {
   searchfield: {
      // config
      clear: true
   }
})
````

Hope this helps
