### ISSUE TITLE
how i can add sidebar icon menu like website mmenu.com ?

### ISSUE THREAD

**Issue by vahidalvandi** [FrDH/mmenu-js#1251]
hello i need create sidebar menu like main website . please help me i cant find in docuent

![Screefffnshot](https://user-images.githubusercontent.com/7871623/132985107-e35bf79c-c354-446c-afee-e7df32a0976f.png)

**Comment by FrDH** [comment]
The menu on the website uses the [icon panels add-on](https://mmenujs.com/docs/addons/icon-panels.html) (to keep the icons in the first panel visible) and the [sidebar add-on](https://mmenujs.com/docs/addons/sidebar.html) (to keep a part of the menu visible even if it's closed).

Hope this helps.

**Comment by vahidalvandi** [comment]
please show with simple demo . i cant show side menu with icon

**Comment by thhkmgl** [comment]
https://mmenujs.com/demo/index.html?demo=sidebar

You can use this demo. 

```php
<i class="fa fa-home"></i> Home
```

Add your icons like this.

Hope this helps.

**Comment by vahidalvandi** [comment]
sidebar not work in rtl !!!
