### ISSUE TITLE
How to use Mmenujs in Vue?

### ISSUE THREAD

**Issue by thhkmgl** [FrDH/mmenu-js#1254]
I'm trying to use Mmenujs in Vue. But I'm getting an error and I couldn't find a solution. I tried everything. I need help!

Error:
7:5  error  'Mmenu' is not defined  no-undef

![image](https://user-images.githubusercontent.com/45882300/134783820-508984dd-4602-4f43-96b1-8d798cff5d95.png)

**Comment by FrDH** [comment]
I'm not a Vue expert, but in general you should import it like this:

`import Mmenu from "./path/to/mmenu.js"`
(imports should always start with either "./" or "../")
