### ISSUE TITLE
lazy sub-menu document and demo

### ISSUE THREAD

**Issue by onlinebizsoft** [FrDH/mmenu-js#1255]
It is a really great option but Im not sure how it works technically. Can you add a bit more information to the document?
Also can you create a demo (or even a comparison when use and not used this addon)? I cant find the demo for this on the example page.

**Comment by FrDH** [comment]
The lazy submenus "simply" wait with initializing the submenu's before its parent is shown.
There is not much to document, you don't need to do anything special for it to work.

That being said, the add-on does have its issues when combined with certain other add-ons and/or options. That, plus the fact it doesn't increase performance all that much, it will very likely be removed in the next major release.
