### ISSUE TITLE
MMENU does not use passisve listeners to improve scrolling performance

### ISSUE THREAD

**Issue by malbezem** [FrDH/mmenu-js#1256]
Lighthouse Report flagged the following performance impacting issue in **mmenu.js** 

> Does not use passive listeners to improve scrolling performance

![grafik](https://user-images.githubusercontent.com/82145026/135597681-2ed76054-f366-4139-af2f-eca8dc69e6bf.png)

The following two code snippets have been marked as problematic and fixed according to [google doc](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools)

```javascirpt
var n, i, s = (n = this.node.menu,
i = "",
n.addEventListener("touchmove", (function(e) { 
    i = "",
    e.movementY > 0 ? i = "down" : e.movementY < 0 && (i = "up")
}
), {passive: true}), // bugfix here
{
    get: function() {
        return i
    }
});
```

```javascirpt
S.node.blck.addEventListener("touchstart", s, {passive: true}), //bugfix here
S.node.blck.addEventListener("touchmove", s, {passive: true}), // bugfix here
```

How can I solve this without having to modify **mmenu.js** on my website?

**Comment by FrDH** [comment]
The listeners arentt passive because they need to prevent the default behavior. Making them passive makes them obsolete.

**Comment by FrDH** [comment]
correct
