### ISSUE TITLE
Add a photo, logo, or image to Header - Can't Figure Out

### ISSUE THREAD

**Issue by twd3** [FrDH/mmenu-js#1258]
I'm trying to figure out how I can add a logo above the title. Home page says "Personalize the menu by adding a photo, a company logo or a full width background image to the menu header". Looked over all the addins and stuff can't figure it out. Can you give me an example?

**Comment by FrDH** [comment]
It's not a build-in thing, but you can use the navbars add-on to add HTML above the panels.
Something like this:
````js
    new Mmenu( "#my-menu", {
       "navbars": [
          {
             "position": "top",
             "content": [
                "<img src='path/to/logo.png'>"
             ]
          },
          {
             "position": "top",
             "content": [
                "prev",
                "title"
             ]
          }
       ]
    });
````

**Comment by twd3** [comment]
Thank you very much for this!
