### ISSUE TITLE
stopping searchfield from searching panels?

### ISSUE THREAD

**Issue by marcelmoreau** [FrDH/mmenu-js#1262]
Awesome plugin. 

Is there any way with version 9 to ensure that searchfield does not automatically search panels on the 'input' event? I have my searchfield's form action going to a URL, and wanted to have nothing happen when users type in the text input

**Comment by FrDH** [comment]
Unfortunately not, the searchfield will always search through the menu.
I'll see if I can add an option for this behavior.

**Comment by FrDH** [comment]
The `searchfield.search` option was added in version 9.2.
Set it to `false` and the searchfield will not search anything.
