### ISSUE TITLE
Hamburger icon has focus after menu is dismissed on iOS

### ISSUE THREAD

**Issue by lumin888** [FrDH/mmenu-js#1265]
Hi guys,

Upgraded to v9.0.1 and notice that when the menu is closed, the hamburger icon has a blue border. See image below. This happens on iOS (possibly on other touch devices?).

I've tried to inspect the CSS and nothing obvious. I've also tried to set the pseudo property focus-outline to none, but the border is still there.

Does anyone have any ideas?

![mmenu](https://user-images.githubusercontent.com/33861348/146517818-00c21af1-9ff5-4fb2-8b01-d268b011237f.png)

**Comment by FrDH** [comment]
The hamburger (or any other link that is set up to open the menu) receives focus after closing the menu. This is to enhance  keyboard navigation following WCAG guidelines.

**Comment by lumin888** [comment]
Thanks for the response. I did find a way to disable it in my case

`div#page-content, a#burger {
    outline: none !important;
}` 

Will close this issue if this is how you intended it.
