### ISSUE TITLE
API calls and hooks not working

### ISSUE THREAD

**Issue by propertunist** [FrDH/mmenu-js#1266]
Hi,
I need to add code to a hook or possibly just run API functions to open/close the menu on my site in order to get the layout to work with the elements on the page. I have not been able to get either the hooks to work or the API calls. I have used the latest version of the code, downloaded from your website.

If I use the gist of the code that is in the examples on your site then I generally get nothing happening as a result. If I use the hook config that is in the examples (For 'openpanel:Before') then the console.log text that is in the function that is run when the event triggers is run once the page loads, but not when I manually open a menu on the page.

I've read around online but haven't seen anything that might be causing this. Where should I look to fix this?

I am developing in Firefox on Fedora, Linux.

Thanks

**Comment by FrDH** [comment]
Here are the API docs: https://mmenujs.com/docs/core/api.html)](https://mmenujs.com/docs/core/api.html

Could you share some code you've already tried?
