### ISSUE TITLE
Compatibilty with Borlabs Cookie Plugin

### ISSUE THREAD

**Issue by mediumbuddha** [FrDH/mmenu-js#1271]
Hi, it looks like mmenu breaks Boarlbs Cookie Plugin (https://de.borlabs.io/borlabs-cookie/).

Here, the fix:

$c[] = '
 			offCanvas: {
-				pageSelector: "> div:not(#wpadminbar)"
+				pageSelector: "> div:not(#wpadminbar)",
+				page: {
+					noSelector: ["[data-nosnippet]"]
+				}
 			}';

Best regards,
M.

**Comment by FrDH** [comment]
Thank you for sharing, the `offCanvas.page.noSelector` config option can indeed be used for issues like this.
Another approach would be to target a single DIV using the `offCanvas.page.selector` config option.
