### ISSUE TITLE
Navbar title not changing in submenu/ Breadcrumbs texts all same

### ISSUE THREAD

**Issue by vincentvega123** [FrDH/mmenu-js#1277]
I updated from 8.x to 9.x today and since then my navbar Title stays always the same when opening a submenu (slidingSubmenus is true). When navbar:title is set to an value "Project XYZ" it always stays the same in the submenu instead of changing to the value of the selected parents menu title. Additionally while testing I also have the same behaviour when activating the breadcrumbs. It ends in Project XYZ / Project XYZ / Project XYZ. I am using mmenu.js 9.0.4. Is that probaly a bug, or have I missed to change something in my config from 8 to 9 concerning that behaviour?

**Comment by vincentvega123** [comment]
I found out, that the problem occurs, while inside my a-tags additional span-tags are used to wrap my texts. If **only span or only a** is used (depending on which behaviour of the menu you want) everything works like before. I don't know if this is simply a bug or a wished behaviour in the new version, and for sure I don't really need a span inside the a-tag – but in the old version this behaviour was different.

**Comment by FrDH** [comment]
The plugin probably assumes there is only text inside the anchor, but I guess an extra span should need to break the whole thing.

I'll have to do some testing.
