### ISSUE TITLE
Aligning the link to open the menu on the right side breaks the closing animation

### ISSUE THREAD

**Issue by vincentvega123** [FrDH/mmenu-js#1278]
I found probably another issue: When aligning the link to open the menu (burger, oder simple a-tag) to the right side of the page brings some unwanted behaviour for the closing animation on my iphone (nearly not to see on the desktop in FF). I tried to align via position: absolute, float: right, table and text-align. All leads to the same behaviour.

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
