### ISSUE TITLE
The menu does not display correctly when set to the right in Versión 9.1.0

### ISSUE THREAD

**Issue by Davox08** [FrDH/mmenu-js#1282]
_mmenu-js Versión: 9.1.0_

The menu is not displayed correctly when it is configured on the right side since it only remains with the measurement established in the `min-width`. For it to work properly I had to reverse the values used in `mmenu-js/src/core/offcanvas/_positions.scss`:

    .mm-wrapper {
	    &--position {
	        &-right {
	            &.mm-wrapper--opened {
	                .mm-slideout {
	                    transform: translate3d(
	                        clamp(
	                            calc(
	                                var(--mm-translate-multiplier) *
	                                    var(--mm-max-size)
	                            ),
	                            calc(
	                                var(--mm-translate-multiplier) * var(--mm-size)
	                            ),
	                            calc(
	                                var(--mm-translate-multiplier) *
	                                    var(--mm-min-size)
	                            )
	                        ),
	                        0,
	                        0
	                    );
	                }
	            }
	        }
	    }
	}
putting `--mm-max-size` first and `--mm-min-size` last

**The error looks like this**

![Captura de pantalla 2022-03-07 024242](https://user-images.githubusercontent.com/42631079/156997389-bf000bc1-a524-4aaf-aea0-58a2ae76a9d5.png)

**Comment by o15a3d4l11s2** [comment]
I think it is similar to https://github.com/FrDH/mmenu-js/issues/1264

**Comment by FrDH** [comment]
thanks, i'll update it asap

**Comment by FrDH** [comment]
should be fixed in 9.1.1
