### ISSUE TITLE
Mmenu WordPress Plugin Page Error

### ISSUE THREAD

**Issue by ChandraGedanggoreng** [FrDH/mmenu-js#1283]
Please fix the link for Mmenu WordPress Plugin Page since it's showing HTTP ERROR 500 when opened.

![Mmenu Error Page](https://user-images.githubusercontent.com/82611315/157300287-7de60ad9-e7a6-4542-9ea1-939d8a180f9a.png)

**Comment by FrDH** [comment]
Thank you, is fixed now.
