### ISSUE TITLE
Download version 3.0.0

### ISSUE THREAD

**Issue by haris2011** [FrDH/mmenu-js#1284]
Hi guys, i wanted to download a new version 3.0.0 on your Site, when i downloaded the file, version 2.9.2 was inside of a download folder. We are using Wordpress Plugin of yours
Where do i get vers. 3.0.0?
BR, Haris

**Comment by FrDH** [comment]
Thank you for bringing this to my attention, I think it was a caching issue... Should be fixed now.
https://mmenujs.com/wordpress-plugin/mmenu.zip?v=3.0.0
