### ISSUE TITLE
Mmenu website

### ISSUE THREAD

**Issue by MikeyJN** [FrDH/mmenu-js#1285]
Hi,

Just to let you know, the main website still has an issue when viewed on a large'ish monitor (typically 17" plus) in that the page loads with the menu open and creates an overflow accompanied with a horizontal scrollbar - see below...

![example](https://user-images.githubusercontent.com/64698829/158034333-6248a84e-f823-466c-b22b-73ff2628540d.jpg)

**Comment by FrDH** [comment]
Thank you for bringing this to my attention.
The website is under construction as we speak so please check back soon :)
