### ISSUE TITLE
SCSS !default variables not overridden

### ISSUE THREAD

**Issue by chriswthomson** [FrDH/mmenu-js#1286]
I have a setup for creating a custom mmenu theme. mmenu.scss is imported into another .scss file after a variables.scss file which contains overrides for the SCSS variables e.g. `$mm_listitemIndent: 0;`

I've been refactoring to handle the changes in v9 (moving old scss variables to css ones), but I cannot get the remaining !default scss variables overridden. Is this something to do with them being referenced as `variables.$mm_listitemIndent` in the mmenu SCSS files?

**Comment by FrDH** [comment]
You could give this approach a try:
https://sass-lang.com/documentation/at-rules/use#configuration or
https://sass-lang.com/documentation/at-rules/use#reassigning-variables

So your scss file would look like this:
````
@use 'path/to/mmenu/src/_variables' with {
    $mm_listitemIndent: 0
};
@import 'path/to/mmenu/mmenu.scss';
````

**Comment by chriswthomson** [comment]
Hi @FrDH,

Excellent thank you, I can confirm that this approach works, although the example should be revised to:

```
@use 'path/to/mmenu/src/_variables' with (
    $mm_listitemIndent: 0
);
@import 'path/to/mmenu/mmenu.scss';
```

(normal brackets not curly ones)
