### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by kennyk3** [FrDH/mmenu-js#1290]
I'm using mmenu.js with Laravel. With the last mmenu update, it keeps throwing this error: 

Uncaught TypeError: Cannot read properties of null (reading 'id')

I've made no changes except for just updating mmenu.js. 

Any suggestions?

**Comment by FrDH** [comment]
Could you show the script you have?

**Comment by thevladdo** [comment]
Anyone solved this problem ?
