### ISSUE TITLE
Safari browser issues - and broken mmenu.js website

### ISSUE THREAD

**Issue by josh-tt** [FrDH/mmenu-js#1292]
Hi there, love the plugin. Purchased, thank you. 

1. Headsup that your Menu site does not work with Safari desktop (M1). You can't open the menus at all. It glitches as you click it and it attempts to update the classes for the menu, but they don't stick and it doesn't open. Safari 15.3

2. On my end I was able to get the plugin working with Safari fine (JS version), though it has some additional issues:

- It's quite slow to open on first click and also very slow to 'close'. Once closed the general page speed is very slow as if there is still some listener doing something while the menu is closed. Resizing the page with the mouse for example is very sluggish with the menu closed. 

I tried various things to fix (using display:none on close - which works to fix issues when applied via inspector, but doesn't work when implemented using hooks). Is there listener running with the menu closed that might be causing the slowdown? 

- Focus states are not visible (despite them being on in Safari) and though they do work, you can't see the focus except on the search field.

**Comment by FrDH** [comment]
Could you show me the site you're working on?
I use safari 15.4 and the site appears to be working as intended (although the iframe examples do sometimes mess up the focus).

**Comment by josh-tt** [comment]
Thanks FrDH. 

I just deleted cache/session storage and I can now open the menu on your mmenu js com site in Safari, though still with some issues outlined below. Something must have gone wrong with the mmenuExpandedState I suppose. I sent you a video by email on 4/5/22 you can check to see the behavior I was having. I will update Safari and see what happens, but for the time being so you're aware:

**on mmenu js com in Safari (m1 15.3) currently I have the following issues:**
- The iFrames have big black boxes around them and sometimes fly off the #page
-  Focus only highlights the search and then stops displaying on focus.
- Missing vertical scroll bar on menu: 
- Scrolling is still very sluggish and transitions are slow as well (flickering a bit). 
Video Example of issues 4-29-22:
https://drive.google.com/file/d/1O3BPKHJX-mWpPCkC8QWENLsOhmrp7tDz/view

My current implementation is local only, but once its online if I'm still noticing issues with it I'll get back in touch. 
Thanks

**Comment by josh-tt** [comment]
Just updated OS 12.3.1 and Safari 15.4 and we're back to the initial issue where menu won't open.

https://user-images.githubusercontent.com/29612594/165889820-7f47ba4f-6c53-43a3-8648-f410a82595c6.mov
