### ISSUE TITLE
Overflow scroll not working like previous version

### ISSUE THREAD

**Issue by seanvandermolen** [FrDH/mmenu-js#1296]
Just updated a site with the latest version of mmenu.  Noticed that overflow is not working like the previous version I was using.

[Watch recording](https://techpad-my.sharepoint.com/:v:/g/personal/sean_cybertechnic_co/EX7NhycR3QREnqgmgXot2-wB49NxTJcmaYFnPGFJ1eOPoA?e=qlcvez)

you can also see it on the [live site](https://dealersupply.com) now.

TY

**Comment by FrDH** [comment]
Sorry for the late response.
What version are you using and what version were you previously using?
Does it help if you update to the latest version of the plugin?
