### ISSUE TITLE
SVG icons issue and strange looking on smartphone

### ISSUE THREAD

**Issue by schel4ok** [FrDH/mmenu-js#1297]
I am trying to apply mmenu on my website and I have few issues:
1) SVG icons doesn't look well in menu item
2) SVG icons doesn't look well in icon bar

![image](https://user-images.githubusercontent.com/10367464/169635801-79d2c30e-c087-458b-82a4-c4f0108daeee.png)

3) On PC mobile menu looks well (except for SVG icons issues), but on smartphone I don't see arrows on the right side. 
![image](https://user-images.githubusercontent.com/10367464/169635847-818020c4-092a-4318-8c7a-0dd05826d227.png)

**Comment by FrDH** [comment]
Is there an online example I could have a look at?
For the icons you might need to add some additional CSS to make them look good. 
For the second issue I think you need to make some adjustments to the viewport meta tag, have a look at the demo files included in the download for an example.

**Comment by schel4ok** [comment]
Here is the online link http://steklo.gq/about-us
The problem not in SVG, but in display css style of `mm-listitem__text`
If I replace `mm-listitem__text` with `flex space-x-2 pl-3 pr-4 py-2` then SVG icon and link text goes in one line.
You can see it from screenshot below. Selected item with my classes and next item with `mm-listitem__text` class.

![image](https://user-images.githubusercontent.com/10367464/169884495-8d2b19ad-d289-49a5-b9b6-42b2c22ab17e.png)

**Comment by schel4ok** [comment]
I managed with css styles to add classes and now svg icons inline with the text.
And I found why mmenu had strange look on smartphone - it was because I didn't add off canvas. 

So when I add this problem disappeared
```
                offCanvas: {
                    // off-canvas options
                  position: "left-front"
                }
            }, {
                offCanvas: {
                    // off-canvas configuration
                    page: {
                        nodetype: "div",
                        selector: "#page",
                    },
                }
            });
```
