### ISSUE TITLE
how to get rid of title Menu in the top?

### ISSUE THREAD

**Issue by schel4ok** [FrDH/mmenu-js#1300]
I cannot find where it is in configuration

![image](https://user-images.githubusercontent.com/10367464/170355237-e8fd308d-4067-4d37-b71b-bf2e531f0dfd.png)

**Comment by DeanSelinger** [comment]
use css
```
.mm-navbar__title {
  display: none;
}
```

**Comment by schel4ok** [comment]
It doesn't work. I don't have `mm-navbar__title` class in html. I just have `mm-navbar__breadcrumbs`, but if I make it hidden, then all breadcrumbs will be hidden
![image](https://user-images.githubusercontent.com/10367464/170811781-1f175691-1aba-439d-a465-63405f40309f.png)

I have another problem. Breadcrumbs are empty. So I just see / / / / above the menu.
You can check here http://steklo.gq/

![image](https://user-images.githubusercontent.com/10367464/170811911-d96d7a79-239d-44ef-90d4-0165581202c1.png)

**Comment by GilbertLC** [comment]
Don't hide anything, just add a space:
document.addEventListener(
        "DOMContentLoaded", () => {
            new Mmenu( "#menu", {
               "navbar": 
                  {
                     title: " ",
                     
                  }
               
            });
        }
    );

**Comment by schel4ok** [comment]
Thanks. It works. First issue is closed.

But second issue still exists - breadcrumbs are not shown.
![image](https://user-images.githubusercontent.com/10367464/171934536-bf988017-c02e-48ca-b69a-c3445bcc1e89.png)

**Comment by FrDH** [comment]
I think it is because your HTML has an additional `<span>` surrounding the text:
````html
<li>
   <a>
      <span> <!-- see if removing this span works -->
         text.
      </span>
   </a>
</li>
````

**Comment by schel4ok** [comment]
you are right. thanks
