### ISSUE TITLE
Duplicate submenu search results when "slidingSubmenus" is false

### ISSUE THREAD

**Issue by hideyuk1-jp** [FrDH/mmenu-js#1306]
After updating to the latest version, when "slidingSubmenus" is false, there are duplicate submenu search results.
The number of duplicates seems to increase with the depth of the submenu.
Is there any option or other way to work around this problem?
Thank you.
![mmenu](https://user-images.githubusercontent.com/40233278/179647897-1bac5d64-45a7-4d8a-8b06-623525a327b1.png)

**Comment by FrDH** [comment]
Should be fixed in the next release.
Thank you for reporting it.
