### ISSUE TITLE
Is slidingSubmenus: false + Selected incompatible?

### ISSUE THREAD

**Issue by bryanbuchs** [FrDH/mmenu-js#1309]
When the menu uses `slidingSubmenus: true` and has a list-item with the `Selected` class, things act as expected; the menu opens directly to the selected item.

https://codepen.io/bryanbuchs/pen/vYReOZG

When setting `slidingSubmenus: false`, the menu opens with a completly blank panel:

https://codepen.io/bryanbuchs/pen/zYWExXJ

Should I be using the `Vertical` class here instead, and if so, where? I've tried adding that classname in place of `Selected`, to the parent `ul`, and to that parent `li` -- no effect.

**Comment by bryanbuchs** [comment]
one more: downgrade to 8.5 works as expected:

https://codepen.io/bryanbuchs/pen/KKoXVVz

**Comment by FrDH** [comment]
Sorry for the late response, this was fixed in version 9.2.0
