### ISSUE TITLE
Sidebar Clickable while collapsed

### ISSUE THREAD

**Issue by drecchia** [FrDH/mmenu-js#1310]
Hi there,
   Is there any way to click on iconbar href while sidebar is collapsed ?
   Looks like "blockMenu" has no impact over this.
   My version 9.1.6

Thanks,
Danilo Recchia

**Comment by FrDH** [comment]
While being closed, the menu has `inert="true"`, ths prevents it from any user interaction (completely intentionally). I'm working on somewhat of a workaround, where clicking the collepsed menu would open the menu. That might help your case.
I would not recommend removing the `inert` attribute, being able to interact with the menu (for example using the tab key) could result in a really bad experience.

**Comment by ppizarror** [comment]
> While being closed, the menu has `inert="true"`, ths prevents it from any user interaction (completely intentionally). I'm working on somewhat of a workaround, where clicking the collepsed menu would open the menu. That might help your case. I would not recommend removing the `inert` attribute, being able to interact with the menu (for example using the tab key) could result in a really bad experience.

That would be awesome, and that is one of the main reasons I don't update because the clickable option of the menu was a really useful feature.

Thanks for your hard work, mmenu is epic!
