### ISSUE TITLE
Menu not working on iPhone 5 

### ISSUE THREAD

**Issue by juergen1964** [FrDH/mmenu-js#1311]
Hi,
i was trying out your new mmenu. Everything is working fine - but: it is not opening/working on my iPhone 5. 

Safari version 12.5 (latest version). 
mmenu version: 9.2.0

This safari version cause a lot of problems i guess. But there will probably no more newer versions/updates for iPhone 5.

I also tryed your homepage with my iPhone - same result - the menu doesn`t open. No clue whats the problem, but maybe it is good for you to know.

There are still a lot of ppl using iPhone 5 i guess even it is old.

Thx so far and have a nice weekend!

**Comment by juergen1964** [comment]
Ok - after a little research i maybe found the issue:

Apparently it is not good practice to use "document.addEventListener()" for mobile devices not just iPhone. They say it is better to select buy individual element. https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Using_Touch_Events.

I opened my menu with a click function - so i will try to change that an see what happen.

https://stackoverflow.com/questions/54236221/responsive-hamburger-menu-not-working-on-mobile-safari/54290816#54290816

see ya

**Comment by juergen1964** [comment]
..me again - sorry.
I am not able to fix the iPhone issue. Even i tryed to make the open/close menu working with using a href like in the dok:

<div id="header">
    <a href="#menu">Open the menu</a>
</div>

Thats also not working, not working at all, even on the desktop. No one else got that problems? The older mmenu is working very nice with no problems.

Ok, now i am out - at least for a few houers :-)

**Comment by FrDH** [comment]
Have you tried an older version of the plugin?

**Comment by juergen1964** [comment]
Hi there,
yes i tried and the older version (not sure but i think it is 8.5) and it works.

Thx

**Comment by FrDH** [comment]
If you need support for older browsers, you probably need to use version 8.
