### ISSUE TITLE
Sliding Sub Menus not working

### ISSUE THREAD

**Issue by Mulegoat** [FrDH/mmenu-js#1315]
Hi there,

I updated my site to the latest version (9.2) and sliding sub menus do not seem to be working. The panels appear but without any animation. You can see the issue on this site by clicking 'Main Menu' . My markup looks right compared to the docs and all the css seems to be imported so I can't figure out why sliding menus aren't working? Any help would be great

[https://staging.reefandrainforest.co.uk/](url)

My JS:

```
import Mmenu from 'mmenu-js';
window.Mmenu = Mmenu;

const initMmenu = () => {

  const menu = new Mmenu( "#menu-location-primary_navigation", {

    "offCanvas": {
      "position": "right-front",
    },
    "theme" : "white",
    "navbars": [
      {
        "position": "top",
        "content": [
          "prev",
          "title",
        ],
      },
    ],
  }, {
      offCanvas: {
        page: {
          selector: "#app",
        },
      },
  });
  const api = menu.API;

  api.bind( "openPanel:before",
    ( panel ) => {
      console.log( "Started opening panel: " + panel.id );
    }
  );

  document.querySelector( ".js-open-mmenu" ).addEventListener("click", () => {
      api.open();
    }
  );

}

function initScript() {
  initMmenu();
}

const main = async (err) => {

  initScript();

}

domReady(main);
```

**Comment by FrDH** [comment]
Sorry for the late reply, but the submenus appear to be working as intended on my end. Tested on FireFox en Chrome
