### ISSUE TITLE
Display error with large menus on chrome based browsers with mmenu

### ISSUE THREAD

**Issue by Hobokens** [FrDH/mmenu-js#1319]
With large menus, the mobile menu remains empty with chrome-based browsers after a certain number of entries. With mmenu-light this error does not occur. In Firefox, the menu is also displayed completely with mmenu.

All browsers have the current version, as well as mmenu and mmenu-light.

**Comment by Hobokens** [comment]
No problem - how can I send you the login to our dev server?

**Comment by FrDH** [comment]
info [at] mmenu [dot] com

**Comment by micka-fdz** [comment]
Hi @Hobokens @FrDH,

Can I have details about this issue and its possible fix?

**Comment by Hobokens** [comment]
@micka-fdz ,
I gave @FrDH access to my development server. 
I'm not sure if it's an issue with mmenu or with some mobile browsers. More than a year ago I had a similar problem with the Chrome browser and mmenu. I reported it to Google, who fixed it after a few months.
https://bugs.chromium.org/p/chromium/issues/detail?id=1233434#c8

**Comment by FrDH** [comment]
I did some testing with a menu containing 1200+ listitems. Chrome appears to have issues rendering that many elements.
When opening devtools, the menu suddenly becomes visible. I don't think there is much I can do about this.
Is there a good reason for having that many menu items?

**Comment by micka-fdz** [comment]
> I did some testing with a menu containing 1200+ listitems. Chrome appears to have issues rendering that many elements.
> When opening devtools, the menu suddenly becomes visible. I don't think there is much I can do about this.

Have you tested on an iPhone browser? The problem appears only in this context.

> Is there a good reason for having that many menu items?

This is an e-commerce website for a client with a large product catalog.

**Comment by Hobokens** [comment]
@micka-fdz I reported this issue for all chrome browsers and safari.
@FrDH It's a website for a university with several departments. The interesting point for me is that with mmenu-light I have no problems with Chrome browsers (~ 450 menu items), only with the Safari browser on iPhones.
