### ISSUE TITLE
Enabled back button functionality manipulates current url-path

### ISSUE THREAD

**Issue by vandres** [FrDH/mmenu-js#1324]
Hi!

We are using the menu and wanted to enable the back button feature. But it leads to some weird behaviour by removing the url-path.  

Our code (we use Vite):

```
// @ts-ignore
import Mmenu from 'mmenu-js/src/mmenu';
document.addEventListener('DOMContentLoaded', () => {
    (window as any).mobileNav = new Mmenu('#mobile-nav', {
        backButton: {
            close: true,
        }
    }, {});
});
```

I recorded a short video to show the behaviour:

https://user-images.githubusercontent.com/1436383/203767808-a38514bb-ae74-405b-81e4-d140838b751d.mov

**Comment by FrDH** [comment]
That's pretty weird.
What browser are you using? I tried but could not reproduce this behavior on Chrome or Firefox.

The add-on alters the url like this:
```js
history.pushState(null, document.title, "#your-nav-id");
```
I guess the third parameter (url) could be prepended with the current url.

**Comment by vandres** [comment]
We figured out, that it is because of the `<base>` element. When it is present, it destroys the url as described.
