### ISSUE TITLE
Core Web Vitals Fixes

### ISSUE THREAD

**Issue by henryklh** [FrDH/mmenu-js#1326]
Can you help to fix the 
[mmenu/mmenu.js:9:1818]
Does not use passive listeners to improve scrolling performance 
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance. [Learn more](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=lr).

**Comment by FrDH** [comment]
It does not use passive listeners because the listeners explicitly need to prevent the scrolling.
Now that (overscroll-behavior)[https://caniuse.com/?search=overscroll-behavior] is becoming more supported, it might replace the need for the scroll listener.

**Comment by FrDH** [comment]
I guess, if you want to, you can disable the `scrollBugFix` add-on:
```js
new Mmenu("#my-menu", {
   scrollBugFix: {
      fix: false
   }
});
```
