### ISSUE TITLE
Iconbar and Position Extension

### ISSUE THREAD

**Issue by craigpotter** [FrDH/mmenu-js#873]
Hi, 

I'm not sure if this is a bug or should be an option, but if you use the new Iconbar with the positioning extension set to right, it displays on the left side. Would make more senses to be displayed on the right. 

[Codepen Example](https://codepen.io/craig-potter/pen/zWdLer)

**Comment by FrDH** [comment]
The iconbar is indeed always positioned at the left, I'll see if it can be positioned on the right w/o breaking other options.

**Comment by FrDH** [comment]
This has been set on hold, as it conflicts with too many other extensions and add-ons.

**Comment by FrDH** [comment]
good news, the next release with have two new options for the iconbar add-on:
use: en/disable the iconbar based on a media query
position: "left" or "right"

**Comment by FrDH** [comment]
In version 8, you can now set the `iconbar.position` option to `"left"` or `"right"`.
http://www.mmenujs.com/documentation/addons/iconbar.html

Please keep in mind that version 8 targets modern browsers and you'll need polyfills for IE11, mor info [here](http://www.mmenujs.com/documentation/).
