### ISSUE TITLE
Dynamic Content & Search Error

### ISSUE THREAD

**Issue by bkeklikoglu** [FrDH/mmenu-js#934]
If I fill menu items with javascript dynamically**, I couldn't find any item via searchfield ?** But, There is no problem on static li items. 
version 7.2

**Comment by FrDH** [comment]
Please provide an online example.

**Comment by bkeklikoglu** [comment]
If you search, it couldn't find anything. Am I missing something? ;

https://jsfiddle.net/berkeke/7zo165tn/

**Comment by bkeklikoglu** [comment]
@FrDH Did you check it?

**Comment by FrDH** [comment]
I think I found the issue, I'll try to fix it shortly.

**Comment by bkeklikoglu** [comment]
Hi @FrDH , How is it going? Could you handle this bug? 
Thanks for your help

**Comment by FrDH** [comment]
try version 7.2.1 
should be fixed

**Comment by bkeklikoglu** [comment]
@FrDH As the bugis almost solved. There is still a little bit bug exist. If I search a text 3-4 times in a row, it brings empty panel. You can test it on same jsfiddle
Thanks,

![error1](https://user-images.githubusercontent.com/29179356/47416241-efde3080-d77d-11e8-9665-753da4364cd5.jpg)
![error2](https://user-images.githubusercontent.com/29179356/47416248-f4a2e480-d77d-11e8-9d1b-f750ebb038b4.JPG)

**Comment by FrDH** [comment]
I tried and sometimes got the same result. Seems to me the results-panel is only empty when you search while it was closing.
Cloud you confirm this?
