### ISSUE TITLE
Version migration notes

### ISSUE THREAD

**Issue by justlevine** [FrDH/mmenu-js#944]
Any chance for releasing version migration docs on updates?

Every time a x.1 release is pushed out, we're usually left scrambling trying to figure out manually what's changed.... especially when it's something big like different class names, or an entirely new build-process, or renaming most the dist files.

🤞

**Comment by FrDH** [comment]
Thank you for the suggestion.
There is a [changelog](http://mmenu.frebsite.nl/documentation/changelog.html), but that's not all that elaborated. I'll see what I can do for the next release.
