### ISSUE TITLE
Show/Hide Navbar object at media query

### ISSUE THREAD

**Issue by robhuska** [FrDH/mmenu-js#948]
So I am trying to hide/show a navbars object at a certain screen size. I see that the extensions have responsive capabilities, but I am not seeing this for addons.  

```
navbars: [
	{
		position: "top",
		content: [
			'<a href="/careers"><i class="ico ico--careers"></i><strong>Careers</strong></a>',
			'<a href="/resources"><i class="ico ico--resources"></i><strong>Resources</strong></a>',
			'<a href="/give"><i class="ico ico--give"></i><strong>Give</strong></a>'
		]
	}
]
```

Since my menu is for both mobile and desktop, this navbar is not necessary on larger screens since these links are in the header on larger screens. But on smaller screens they get hidden from the header, so at that point I would want this navbar to show. I tried just using CSS to hide it, but it doesn't work because there are classes applied that add space for the navbar.

I am sure I could hack together a solution with just CSS, but that just feels wrong... I feel like there is a better way and one hopefully built into your plugin.

Thanks,
Rob

**Comment by FrDH** [comment]
Having responsive options for add-ons has been on the TODO list for quite some time, I'll see if I can implement it in the next release.
For now, I guess you can use the [matchMedia API](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia) to add or remove the needed classnames to the menu, navbars and panels:
````js
var match = window.matchMedia( '(min-width: 900px)' );
match.addListener(
    function( m ) {
      if ( m.matches ) {
         $("#my-menu").addClass( "mm-menu_navbar_top-1" );
         $(".mm-panel").addClass( "mm-panel_has-navbar" );
         $(".mm-navbars_top").removeClass( ".mm-hidden" );
      } else {
         $("#my-menu").removeClass( "mm-menu_navbar_top-1" );
         $(".mm-panel").removeClass( "mm-panel_has-navbar" );
         $(".mm-navbars_top").addClass( ".mm-hidden" );
      }
    }
);
````

**Comment by FrDH** [comment]
good news, this feature will be available in the next release.

**Comment by FrDH** [comment]
In version 8, each navbar object has a `use` option which can be set to a media query:
http://www.mmenujs.com/documentation/addons/navbars.html

Please keep in mind that version 8 targets modern browsers and you'll need polyfills for IE11, mor info [here](http://www.mmenujs.com/documentation/).

**Comment by robhuska** [comment]
Wow, thanks for keeping me up to date on this! This is a great set of features that you are adding. I will be continuing to use this on all my projects that need mobile menus moving forward! Your earlier solution worked great for what I needed so I will probably just keep that in place for now, Thanks again and keep up the good work!
