### ISSUE TITLE
Increase the height of footer.

### ISSUE THREAD

**Issue by upalr** [FrDH/mmenu-js#964]
This is a great plugin however I am really having a hard time figuring out how to make the footer larger in height than other menu items. If I increase the --mm-navbar-size from 44px (default) to 96px, It actually fixes my footer but it also increases the header height. I just want to increase the height of the footer. Is there any way to do that?
Thanks.

**Comment by FrDH** [comment]
For now, all navbars (in the header and the footer) are sized with the same CSS variable (`--mm-navbar-size`). You could try the `height` option to change the size ( 1 * --mm-navbar-size, 2 * mm-navbar-size, etc) for each navbar:
````js
$("#my-menu").mmenu({
    navbars: [{
        position: "bottom",
        size: 2,
        content: [ /* your navbar content */ ]
    }]
});
````

**Comment by upalr** [comment]
I think the [documentation ](https://mmenujs.com/documentation/addons/navbars.html)says the name of the property is `height`, not `size` . If `size `is the right property to increase the size of the navbar could you pls update the [documentation](https://mmenujs.com/documentation/addons/navbars.html).
Thanks for your help.

**Comment by FrDH** [comment]
My bad, it should be `height` as the docs state.
Is there an online example - preferably a jsfiddle or codepen - I could have a look at.

**Comment by FrDH** [comment]
Just FYI:
In the next version, you'll be able to override the `--mm-navbar-size` CSS variable for each navbar without having to change any additional CSS.

**Comment by upalr** [comment]
Awesome. Thanks for integrating this new flexibility. :)

**Comment by FrDH** [comment]
In version 8, you can override the `--mm-navbar-size` CSS variable for each navbar, something like this should work:

````css
#my-menu .mm-navbars_bottom .mm-navbar {
    --mm-navbar-size: 60px;
}
````

Please keep in mind that version 8 targets modern browsers and you'll need polyfills for IE11, mor info [here](http://www.mmenujs.com/documentation/).
