### ISSUE TITLE
I can not find documentation how to use _variables.scss in version 6.0.0

### ISSUE THREAD

**Issue by miladinovicb** [FrDH/mmenu-js#979]
Hi, 

Can help me how I can use _variables.scss in version 6.0.0, because I can not find documentation for that version?

Thank you

**Comment by FrDH** [comment]
Creating a custom build in version 6 wasn't all that easy, I'll try to explain:

1. Add a folder in the same directory as the mmenu package folder and name it "mmenu-custom".
2. In this folder, create a `_variables.scss` and a `_build.json`.
3. Run `gulp custom-css` and `gulp custom-build` in the command line.
