### ISSUE TITLE
Update menu content

### ISSUE THREAD

**Issue by rubinosoft** [FrDH/mmenu-js#980]
Hi, I've tried to update a submenu and after I called initPanels without any change in the menu. Because I would like to buy a license, it is possible to have this functionality working?
Thank you very much and congratulations for the plugin it is terrific!

**Comment by FrDH** [comment]
Have you tried the [dynamic content tutorial](http://mmenujs.com/tutorials/dynamic-content.html)?
Could you share some code? If possible, please create a jsFiddle or codepen.

**Comment by rubinosoft** [comment]
I've tried the dynamic content tutorial: the new ul block is correctly replaced into parent li, but the menu can't refresh. If I try to add (not replace) the block, it is shown in the menu like tje dynamic content examples. There's is a way to refresh the menu?

**Comment by FrDH** [comment]
I don't think I understand what you're trying to accomplish. Could you create a reduces test case, preferrably using jsFiddle or codepen.
