### ISSUE TITLE
concatUmdJS for all addons/wrappers/translations

### ISSUE THREAD

**Issue by mrDinckleman** [FrDH/mmenu-js#981]
Hello.
I try to use your fantastic plugin, and I don't want to use "all" bundle. But importing addons/wrappers/translations require global defined jQuery.
Is it possible to wrap all addons/... with UMD or I have to use my own fork with custom build?

**Comment by FrDH** [comment]
Only if you create a [custom build](https://mmenujs.com/documentation/custom-build.html)

If you're developing for modern browsers, you could also have a look at the [development branche](https://github.com/FrDH/jQuery.mmenu/tree/develop) (which will soon become the default branche).
It no longer has jQuery as a dependency and works with ES6 modules. Documentation for this branche will be available once it become the default branche.

**Comment by mrDinckleman** [comment]
Ok, thanks for advice

**Comment by mrDinckleman** [comment]
I encountered a problem while creating new custom build (PHP 7.3.1, Win 10 Home x64):
```
...\jQuery.mmenu>php bin/build ../custom
PHP Notice:  Only variables should be passed by reference in ...\jQuery.mmenu\bin\build on line 46

Notice: Only variables should be passed by reference in ...\jQuery.mmenu\bin\build on line 46
PHP Notice:  Only variables should be passed by reference in ...\jQuery.mmenu\bin\build on line 46

Notice: Only variables should be passed by reference in ...\jQuery.mmenu\bin\build on line 46
PHP Notice:  Only variables should be passed by reference in ...\jQuery.mmenu\bin\build on line 46

...

PHP Warning:  file_put_contents(...\jQuery.mmenu/../custom/_build.json): failed to open stream: No such file or directory in ...\jQuery.mmenu\bin\build on
 line 65

Warning: file_put_contents(...\jQuery.mmenu/../custom/_build.json): failed to open stream: No such file or directory in ...\jQuery.mmenu\bin\build on line
 65
```
Obviously, path `...\jQuery.mmenu/../custom/_build.json` is not correct, but running command `php bin/build custom` shows the same errors but with correct path.

There were a lot of PHP Notices after I created `custom` directory mannualy, and `custom/_build.json` was created automatically. It's content was different from `src/_build.json`:
```
...
		"core" : [
			"offcanvas",
			"oncanvas",
			"screenreader",
			"scrollbugfix"
		],
...
		"translations" : [ "de", "fa", "nl", "ru" ]
```
Is this error, that `oncanvas` is not first, or not?

**Comment by mrDinckleman** [comment]
Ok, it helped for me. Also I have add a semicolon after `$name = explode( '.', $name )`
What about files order?

**Comment by FrDH** [comment]
The order of the files should not matter for the build process, however it probably will build a .js file that doesn't work. The oncanvas script really needs to be first for any of the other scripts to work.
