### ISSUE TITLE
Documentation is not clear for Magento wrapper

### ISSUE THREAD

**Issue by budoland-ab** [FrDH/mmenu-js#989]
Please update mmenu documentation. Magento version is missing. I can not check if it's for Magento 1 or Magento 2.

**Comment by FrDH** [comment]
It should work with both versions (as it doesn't do all that much):
> Using the "magento" wrapper will set the classNames.selected configuration option to the default classname used by Magento.
Both Magento 1 and 2 use "active" for their selected menu item.
