### ISSUE TITLE
How to close mmenu onclick only for max-width (tablets and mobile)?

### ISSUE THREAD

**Issue by miladinovicb** [FrDH/mmenu-js#991]
Hi,

How I can make option to close mmenu only for some max-width?
I want to prevent close onclick for desktops, but enable for tablets and mobile.

Thank you

**Comment by FrDH** [comment]
Could you specify what you mean with "close onclick"?

**Comment by miladinovicb** [comment]
I want to automatically close mmenu after clicking a link inside it, 
but only for custom screen sizes.

**Comment by FrDH** [comment]
Ok I understand.
The `onClick.close` option is a "value or function" option, meaning if a function is specified, it will be invoked and the return value will be used.
So you could give this a try:
````js
$("#my-menu").mmenu({
   onClick: {
      close: function() {
         return window.innerWidth < 600
      }
   }
});
````
