### ISSUE TITLE
Mobile version differant from the desktop version

### ISSUE THREAD

**Issue by Dirdmaster** [FrDH/mmenu-js#992]
Hey there, 
I'm trying to figure out to do the same thing as this issue https://github.com/FrDH/jQuery.mmenu/issues/66 but I guess the widescreen.css file doesn't exist anymore? 

Any tip how I could make this happens?

Thanks

**Comment by FrDH** [comment]
The widescreen extension was replaced with the (more configurable) [sidebar add-on](http://mmenujs.com/documentation/addons/sidebar.html).
