### ISSUE TITLE
Search results don't include items with submenus

### ISSUE THREAD

**Issue by logiczone** [FrDH/mmenu-js#993]
Back in version 7.0, when I performed a search, the results included both the leaf items AND the parent items that match the search term.  This is no longer the case in 7.3.  The options I used were: 
`                searchfield: {
                    showTextItems: true,
                    panel: {
                        add: true
                    }
                },`
Is this a bug or I need to use different options and/or configurations?

**Comment by FrDH** [comment]
I think it parent should still be included in the searchresults. Is there an online example I could have a look at? Preferrably a jsFiddle or codepen.

**Comment by logiczone** [comment]
OK.  I created 2 codepens. 

[MMenu 7.3](https://codepen.io/anon/pen/WWXXWp)
[MMenu 7.0](https://codepen.io/anon/pen/dLZZBB)

If you search by typing the letter "a" (for about) in both instances, you can see the difference in the search results.  In 7.3, if I type the letters "ab", nothing is returned, whereas in 7.0, it returns the parent menu "About".

**Comment by FrDH** [comment]
Will be fixed in v8.1
