### ISSUE TITLE
Adding .mm-wrapper class to menu's parent

### ISSUE THREAD

**Issue by mrDinckleman** [FrDH/mmenu-js#994]
I found that line in legacy code:
https://github.com/FrDH/mmenu-js/blob/572029a0b0bf7f33e29d69b57c6293e034babd69/src/core/oncanvas/jquery.mmenu.oncanvas.ts#L506
I'n not sure why, but this class isn't added to any element on a page after load either after menu was open.
In new version this line is present too:
https://github.com/FrDH/mmenu-js/blob/c43001f83c3af70929ccde7b0fc342fd70c1a68b/src/core/oncanvas/mmenu.oncanvas.ts#L566
But now, if I use `clone: true` in config, it causes an `Uncaught TypeError: Cannot read property 'classList' of null`

**Comment by Blaaszka** [comment]
Yeah, i have this problem too.

**Comment by FrDH** [comment]
The class is added for (the default) on-canvas behavior and is removed by the off-canvas add-on for off-canvas behavior. Not sure why using the clone option now throws an error, but I'll see if I can fix it.

Thank you for reporting it.

**Comment by FrDH** [comment]
Should be fixed in 8.0.4, sorry for the trouble.
