### ISSUE TITLE
Playground HTML doesn't match what's shown

### ISSUE THREAD

**Issue by Enchiridion** [FrDH/mmenu-js#995]
Firstly, thanks for the great plugin!

I was stumped for a while as to why my menus didn't look like the one in the [examples playground](https://mmenujs.com/examples.html).  Specifically, why the About Us link was split into a link and arrow in my local version, but no split in the demo, the entire link only opens the sub-menu, which is what I wanted.  The problem was the HTML being shown below the example doesn't match what's actually being shown above.

The line: 

`<li><a href="/about">About us</a>`

should be

`<li><span href="/about">About us</span>`

The info on how to get that was hidden under the [styling lists](http://mmenu.frebsite.nl/tutorials/off-canvas/styling-lists.html) tutorial page.  I think this is more a functionality option and not so much stylistic and would benefit from being added as an option to the playground.

**Comment by FrDH** [comment]
Thank you for pointing this out to me, I'll update the HTML in the playground shortly.

**Comment by FrDH** [comment]
Should be fixed now.
