### ISSUE TITLE
mmenu as a Web Component?

### ISSUE THREAD

**Issue by lkraav** [FrDH/mmenu-js#996]
Could be framework-agnostic, or follow some SCSS-based framework like https://github.com/web-padawan/aybolit

https://www.dannymoerkerke.com/blog/web-components-will-replace-your-frontend-framework

https://developers.google.com/web/fundamentals/web-components/best-practices

Your thoughts?

**Comment by lkraav** [comment]
Interestingly, https://github.com/FrDH/mburger-css/blob/master/src/ts/mburger.ts already is a web component, so the concept is clearly not unfamiliar.

Alternatively, can mmenu-js be used as-is inside some layout component Shadow DOM, I wonder?

**Comment by lkraav** [comment]
Here's an example glitch of what I would expect to somehow work https://glitch.com/edit/#!/thinkable-marjoram

**Comment by FrDH** [comment]
Definitely on the TODO list, but the mmenu script is a bit more complex than mburger :)

**Comment by lkraav** [comment]
Will this be re-opened later or a new issue when time is right?
