### ISSUE TITLE
Bootstrap4 wrapper with mmenu 8.0.4 working?

### ISSUE THREAD

**Issue by jmalatia** [FrDH/mmenu-js#997]
Can't seem to get the bootstrap4 wrapper working with version 8.0.4.

I copied the mmenu bootstrap sample (http://mmenu.frebsite.nl/demo/index.html?demo=bootstrap-navbar) to a codepen here:
https://codepen.io/jmalatia/pen/ROEjjv

With the 8.0.4 version mmenu.js from https://cdnjs.cloudflare.com/ajax/libs/jQuery.mmenu/8.0.4/mmenu.js the mmenu doesn't fire and works like normal bootstrap, but if I swap out that js in the code pen with the js in the sample page https://mmenujs.com/mmenu/jquery.mmenu.all.js?v=8.0.0, mmenu works.

Thoughts?  Am I missing something?

**Comment by FrDH** [comment]
Hi, thanks for reporting this issue.

FIrst this I noticed: version 8 only has a wrapper for bootstrap4, therefor the bootstrap4 wrapper was renamed to "bootstrap". I changed this but it seemed to have no effect, I'll have to investigate why it's not working.

As a side note: the version in mmenujs.com (although affixed with "?v=8.0.0") is not version 8, the affix merely shows an unique version
