### ISSUE TITLE
Custom build fail on latest v8 

### ISSUE THREAD

**Issue by 7iomka** [FrDH/mmenu-js#998]
![image](https://user-images.githubusercontent.com/18473137/56907988-12932e00-6aae-11e9-8116-035a1153899a.png)
`(node:9658) [DEP0097] DeprecationWarning: Using a domain property in MakeCallback is deprecated. Use the async_context variant of MakeCallback or the AsyncResource class instead.`
I'm tested with different version of node.js (10.x, 11.x, 12x) on Mac, and it's fail again and again when I try to make custom build.
Please, help me.

**Comment by FrDH** [comment]
Hi, thank you for reporting this issue.
The deprecated warning should not result in the build to fail. I'll have a look at why the build failed.

**Comment by 7iomka** [comment]
in fact, the js file in the dist folder is not generated, only css :(

**Comment by FrDH** [comment]
hmm, I see what's wrong, I think your JS got generated, just not from a custom file into a custom folder. I'll see if I can fix it later on today.

If you want to fix it locally:
In `gulp/js.js`, on line 22, change `dir = dirs(false);` to `dir = dirs(true);`
In `gulp/js.js` on line 24, change `JSpack(cb);` to `series(JSpack)(cb);`

I think that should fix both issues (but not the deprecated warning).

Sorry for the trouble.

**Comment by 7iomka** [comment]
> hmm, I see what's wrong, I think your JS got generated, just not from a custom file into a custom folder. I'll see if I can fix it later on today.
> 
> If you want to fix it locally:
> In `gulp/js.js`, on line 22, change `dir = dirs(false);` to `dir = dirs(true);`
> In `gulp/js.js` on line 24, change `JSpack(cb);` to `series(JSpack)(cb);`
> 
> I think that should fix both issues (but not the deprecated warning).
> 
> Sorry for the trouble.
Thanks!

**Comment by FrDH** [comment]
I implemented the fix in 8.0.5
