### ISSUE TITLE
Legacy Documentation?

### ISSUE THREAD

**Issue by pagegwood** [FrDH/mmenu-js#999]
I work on a number of sites that are still using the legacy version of the plugin and likely will not upgrade anytime soon. It would be great if we could access documentation for each major release.

**Comment by FrDH** [comment]
Hi,
The GitHub branche can be found here:
https://github.com/FrDH/mmenu-js/tree/legacy

The docs:
mmenu.frebsite.nl

And on NPM:
https://www.npmjs.com/package/jquery.mmenu

I just now noticed the readme in the legacy branche contains links to the current documentation, I'll update it shortly.
